BEGIN;
DROP TABLE IF EXISTS agent_routing_state;
DROP TABLE IF EXISTS route_decisions;
DROP TABLE IF EXISTS agent_capacity_slots;
DROP TABLE IF EXISTS agent_sessions;
DROP TABLE IF EXISTS ws_command_dedupe;
DROP TABLE IF EXISTS agent_outbox;
DROP TABLE IF EXISTS traces;
DROP TABLE IF EXISTS runtime_events;
DROP TABLE IF EXISTS continuations;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS route_requests;
DROP TABLE IF EXISTS flow_entry_bindings;
DROP TABLE IF EXISTS flow_versions;
DROP TABLE IF EXISTS flows;
DROP TABLE IF EXISTS import_jobs;
DROP TABLE IF EXISTS agent_states;
DROP TABLE IF EXISTS agent_skills;
DROP TABLE IF EXISTS break_reasons;
DROP TABLE IF EXISTS adapters;
DROP TABLE IF EXISTS channels;
DROP TABLE IF EXISTS queues;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS agents;
DROP FUNCTION IF EXISTS reject_mutation();
COMMIT;
