// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L1rchs5mii6FVzOOdGkD0lRsmW75KjoK0tyWV2ypZLkqulp+irBTJCElQlkA0hJ7AqfmF+zgInZw9nH",
	"Wcqs5Aa+D8gHmXzoablaETNdVjITz+/9/L0RyiSVggmjG1u/N1KqaMIMU/DXTqa0VL9kTE3snxHToeKp",
	"4VI0thqHKf17xkhKR1xQ+4yE8DpRzGRKsIhQTQLBrswZ/hCQoZIJMWNGUsUuuMw0ibk2RDGdSqFZlxwm",
	"3BAjyZCZcAxvDrnSxk7Cun3RaDe4nfrvsKJ2Q9CENbYaOHyj3dDhmCXULtVMUvuLNoqLUePr13ZjTxhu",
	"JvvRETXj2c3gr+TTp/3di1ckVTyhakLO2aRLPmTakAEjlFzQmEfunTf43xdEKhLLS+a3rcn709Mj8qLX",
	"IwEX8MUZj4LS4lO7gHztPGq0G4r9PeOKRY0tozJW3sf/UGzY2Gr8y1pxTWv4q17DhZQ2dzpJ2ZzLOh0z",
	"ElJDYzkiDPdqj4gMGBcjwpNUKsOi7pwDxi9uvNB9GL5YIyx5P2JJKg0T4eRnNnnPaMTU7Lp3Ys6E6YyY",
	"YIoa5k+fNI/f7ZAfNl9ukP/7fza7r1ok0yyykJPQc0aODk9O7X2oSUfTISPN3c3O+vNWl2wTxVIGA9mt",
	"MG3IJTcIaZomzN444aL4W6pRfrEAuExpru33qeIA6zqL3SAB91syZ4qlMZ1sEXtMAcy/8arVJYewLxqT",
	"//73/yJ0oJkwZAxbJwmjQhNKhorpMfkiB0TJS8I1CRUumNFwTEIaxyVYwm+LiyodaudnNqmgBLuiSRrb",
	"t3rrP6z/wNYHnVfh6x7+z+ter9fprW88f7H58tXrH+ig0W4MpUqoaWw1sgygdBan8GL/Igfz0ApfgN24",
	"i8uJw2ACBwpXteZAcw0BkTARpZIL052DM/DW2d2gzr4I4yxiu1zTQcyiOfjz25gJEsBttgnHT0jkvkGM",
	"4kyTZsAEPPpxSGPNgpYFpgqN012yy4bUAk2A75DmzvZpp/dDaz6BcxOe+Qkr9xrhcI0tGC6/poGUMaMC",
	"9njAE27m7OwDveJJlhCRJQOmiBwSbliiLS7hXVmYRwLsVw4/bmx2if92vdebv/jYTl6/4o3NdiPBMRpb",
	"671eu5Fw4f7KN8KFYSOmYCMfacJOGFXheM5udqhmHS40E5obfsGIzgYIsETDd0Qidgd2dQEZchZHpLl/",
	"sP/zHgn+55//Z9DqkmOH8Pm1Xo6lZsR+QUIpDOWOGlzQOGOEisnlmClGmkIay9qG/KojRTwBLD/8pfPi",
	"rb1+GWd2kZYKRREJ0tGZUaMkIFxE7IoMpbIHDTgnQkaoITFVI6Zysq35P5ief8zwn8Us8FCN5iHqoRpR",
	"wf+BfByxo0uOFAMK5QiiRUJY5/HeySnRLKHC8FB3yemY9QXNzFgqbigceyDVyPI9pMv2o923RIcyBXaj",
	"CY0v6UQTxWiUSwV9Efxr51CNOvtR4KmioxLBoRrtSGHYlQlIwqMoZpdUMThgM+Ya15YLL33BNbGXkc8e",
	"UUMJDUOmNWm+O/z0cbfTe01iRs/piJFRRlW0RSgZS214zEgIbKcvQirsMJGyewqV1LpjOcKAjemFJf+D",
	"CWERN3ZTdpmfjg/IgIU00wz+DmXE+kKwCxAPaKRJ8DsezNeyMETNuDVXQMD374LSncCjXy0Hk2Ie/pz8",
	"SvBTcoEvwvE5ugziDMJIc//DUaf3GrAF10UugUbCNQnTsYx+i9gbWwv1RdAlH7hOqAnHLMqHnhGZgI/q",
	"LEVxxL+HYiKLumQPedgWCS563fVgPjbgHs7cAAvx4qs9Wkec7e9vaXSMsoH9K8Tt2H/SNI15CNtf+6Lt",
	"cZWY6u8NppRUQK9Q6hvICEUmCu82Ehpb7GbRGXyMF8o08DHgyb31wUbYeTV8Tjuv6CDsvI5esM7m8CV9",
	"NXgd/hD1WOPrqre+Z9dy7HaFe5xizLjIXAqyi22ThGttYdmDGpJH3UZZMXEX2Cb5Vsj+rm5bEdhtmsxg",
	"cLcBPNYwJWh8wtQFU3t4UDc7WxyofK6ZYFcpCw2LzvC1b3uyn/LlEA3bJbAqdw5wSpYO794OuEpUwYMX",
	"3t2ZEwnvbkMfcODSrcONCyk6Tqarv/SP0ryTmYhutlEhzdkQPi/tUcgznYXjMzqyg33bez5mWmYqZMBn",
	"YKVwLAWTSJUcsHnMBhUAEkqlWGjI/q5lspREfDhkyvLcsuLxoveiDdO86D0HRvG13XAkyilVUh5YYeFu",
	"CZY/XSPlGcgiZ5lmZ1RPRHhmedQlnXzzOyioF2FXIWMRCmabPfLhLVkj6712r9dDTQpZGEijXfLJceiL",
	"XneDwJaI2xLwOyd64TcgdH3NVw1MYjuiqalTWLcFofgbUWzEtVETO70V+uCplXnSXK4ybKSQn4K+o0mT",
	"dUddQsk7xdjJb/unO+/JQPFoxNqEkgN+wX7mhoyoYZd00uqSfWF3sI4ykBWrcmnRbjmXQYUkJ7s/g+yq",
	"aGgsMBF2xUIQSC0Hp3G+6vw5iamINMJlTO1PCY+ZNlI4U0yqZMqUFZAB2PD7M2SvM4pgZIXpIWcKztce",
	"vZ/wnIvI7bvfGCrG9CU34bjfaJN+I+YX7Jwb/MNc8pjLfqPVhfMB4cKJgIykMTWWPJFIMhT+FLM8PjQo",
	"psNO7GHh4gttuJhyVsdtN6wIN7udT5qpzpCGllmGVEjBQxoTXmyyudt7cbbe6a2XBKQ24UmSGavB9QUd",
	"2r2jbt8lOxb4NTeMfPq4/8unPdJEAt8GEbIF8Ar2NLvTLNVMmb44Zwisgyw+9+DdPBpTzchmi1AROWKk",
	"GNCUkBFjwdpSK2WlUo1mkBgAUI95quGjYWYyxcjuyQHJv9TTh+Zvuzi8syhct0BBjWXRja3G//c32vnH",
	"Z/s/vc4PZ59/77VfPv/6P+rPWAz5CIHIStNS0PioBFwo71ZvwAJAB+77LyeHH98SHCNz2DSI5aBLTsY0",
	"ZYAWuNqOnbmjUxbyIQ+75KMkF0xEUuXPyJBfsYiEMs4SoQG2rPA+MWN70yOJUATYBqLR1LH83rAKhN0b",
	"T7vuaTeUiT0XqUxja7P3svc1PwE5+MJCAyeANp4zaqqWmo3exstOb7Ozvnna623B//1b2TITUcM6hoPm",
	"ZxWMQxFP/HnNHLMzTVRmqLyamwzsllDQArI+a/l1VqyQxjFTHao1HwkWlREAtBsqiB+I6Ik2LOmL5vvj",
	"Ntk5/tAmzIRdD9oWjoEKJzQFHTGnXR8PT5dDvVW4AosqgSMv1LS65Igqw2lMMsH/nrG+sNqFJWcCuCuo",
	"K44Ud5GMOs1DW+07kdoQKVhfFFtAhp9aKok2VPtPqUZvSJLFhnfwhb6IuKbJgI8yhMbIopFC+yQwnAtO",
	"SZAfsRv2dO9fT4NpPPuw+6Gzvbt9dLp33Hl30tndsTgmsji2Vzn3pvHSVlELvcI0fcW7XKcxnaDNA4+0",
	"wKMqsnUrCy4xrrfAuEiH4KpnVulk2JVXmqXR/SOJ1xhn7WRSSIOEPp4QLizKgrIkU8MTrg0PO7EMz3Pl",
	"NpSZ1Vacee91mxz+0llf237R6hLUgzryUlil1ivGRAqCe5xWjH+YAov1pYaywljwN3Qx5AoDMLS2NxdV",
	"uHZBIopzqNCmyh18rqFj2yMnes4KRaOSJckJKV0C72tCFUpj4yyhQlvmRwbS6Ba5HEsypiKKGVEys/wK",
	"NEAaAsvqkj0ajt3QAxZLMQLTJLuioYknFnstdtZJK09svZatsyQ96/VebNyUkT8IG0soj2tgDKAAfiQ0",
	"ihTTukqZaMxD9v9WuXK+Ahx0MdOszncih6YTsZgZRoYxHXVzez56ckDERaDXhafA3sQlj2MQUGmaMqos",
	"UjiL+JSroPAMgL4S/HnaD/AjupeMJDpTQxqWXBIw9fT9PnH7x83t3x939j4cdRwGPjSbl8MCaKuos21R",
	"h3wcZRMm7oKT63Mex7oGp+A5ySHMSCd3AB6BcThVcshDzkQ4IVb+ECPLBpIBiyIWETh+Y0nAT3unJUSy",
	"8PWGyIQbSxwBWutQbb2Hj9EDZrnSMKYGOfd2yyoMxsOQnQrJ3dqUfw9t0naEZQcCJAv2vA07Tizz/DqX",
	"BFKl6OT7F4RaRUiFo2eWq5PgaPt0533gLdL6TW5vXkEauoUE5Cn/nYg+B1ybfcOS2VN7F1Pj4FixUKqo",
	"8ITXuIg9IigGAo9ACmxFGgfCTQDJklsRdVWLBwSxC2lqgRD56K0neeiPKQ/doajzJDE8SQxeYrg/MeCh",
	"+dhj5BjT7H9Wr0F6XhGKqCiLRLRGKOrOUPh6ARCmR/HPIlPOkKUACWqad7RzBiQFuVSWkg9kxNmUqvWW",
	"x7FF0hPEl1WuqbSFebrd7C4xmIdrPKIugVguzS8YUVSMGFknzQEbcSGYatlzW++RJruyh9KCqBVymDKx",
	"fbTvQx5mea0mgbO0BGuBC1UKiJZAciRNecfCxogJckAnTJF1HyMhFToiLHnSY6lMJ+QqzLghMjMdOezg",
	"Cp1rAu7RR0Hg0tDsoUjTe3RSGp7TEWuTo5gK0ntuFUPCxFCqkCHHXLcCLI5rOVxVbNrYcFGK4FXbkRH7",
	"0Tv+YBEBErwirIlru1SrFeCQFj40Y+T4cHv3w/YRQRb8nOgMw2pCCw7K0rMXXYJxm9puPYsjoo0Fs8hp",
	"GwkXP66vJfTqx/WelX4+7dvLSRW7AMF6gKHBVpSk50y/gTVdcsWIBoN+ZGVMMcq4HjNN+o1LJcUIF91v",
	"kKbdaWVnLWQ2/kULevBer0fKrs/WFG19PUsknOZyDSI3RVbyz6sAP586GGpYfTTvMLNEARBDG7QZgljZ",
	"PDndPt3zIlk12NK+mGkCkrbFHX91lqRcSB4RSoYyjuVlJ0sB/62Y+XynEr1W5/qzq7gW5R8oRs/P0NPs",
	"PqRxfDhsbP1ttSE+t2uOBEYlOGruZgwzBQ71t/AjHpU/oxeg04mO5ZsoUWAMkzunH3/Er4Iu+WjfsLKB",
	"fdGMmcKRnMC4lO8yMaIjFp2FYyoEi1ff7w5+gFHTtZt2Q2KITsXo5HYeT4ib3l653/rm0q3v4Ue33/x1",
	"xYJUanNWsvOeaY8Fq53ZkdRmv/gccaj+8JymgFCBuspviqafUsKuUq6Yzs/rJZjtDbkc85j5s3FHAycn",
	"JJi39/xR5yPB4CseFbx7dn3Ve0bVdqt+DTECoWJWtkAAAH+m27FV0zAE4NM+yTSwEQ7kIGKGhXAwMSOp",
	"RHY+ZePIKeXzWkoJgLSaCQRffSiJ8FLRNEvPMmHq7Mhl3ww5PT3ICUn5OvMDftXqkt/w+i+bLZJSXZwi",
	"T5g2NEnb8PmAhucjJTMRkZFUMjNcQHaL491u9P/+j/8kQT0CBMQoCmHN9sIW4+Tck9tcdHJLwHOKl+VU",
	"vyQou0ufBuQVReEcYuqkP3pBeUwHPLZ6laNSTnoqsby+6Itnz+CLjpGjUczshraePeuLDgmOGY0mAcZe",
	"4XAxw0D3kFmpsexcgg8+SlP6JhPFV00hic4GHeQ2+o0LrvEJJcA3WjAGshCMU2FWH6VqUgyF+3FyfO5X",
	"tTPgyLihE1COO5oZvxVPnWHcgtKD1GhxlYrybkgT1esOF9xwiqQgnuACEfRwJAt6nfKHQBQ7EPUeGnIp",
	"1blVarmMZofE0Q6Hw5gL5k7Z86JYjoAqWoFSAWrgH3WDgGqVJRbG4PAbEEvo/wnH2Wg33AE02g1cf6Pd",
	"cFOXIKxAevjs2IW2zepYNSdfaFkhFVahZ0gHSoKEc0C698dUE0oCi9t2mADcQmBrAHKqEi4gl4ABulZY",
	"NYv5iNupLbFB4jByrEYKlGtQKwj29XE+fiQTygUZszhlioRjFp472uMwYr33ZOxb3diHQmmcCYgEe7T2",
	"PqdFnUlVmzF3Yo8MDt6ir3O4VyTjlIfnTHXJAaQtOhrqfJGQbrncvv5kLPxOjYVvj/e2f+4cfPq48/5h",
	"PYwxHbCY6LG8FD4FC6lfxPS5kWnVgHTgkPDWuoQnxrUZfUCHcyrvbUkVXJlDm7suFxDktYJJoJmjTprI",
	"A1xPxhbGYA4IZPVBA8VAXFcFDfchHAnGwZ4qygUXIztA9YrnpAB+t6bW/Pqmyd7tra9vs/gc01PfUR6z",
	"6Fhe1gkGQ/gRI8gFoRVKMQDvJGZCvXAWRan4iFv8tl+4WHx7pZbysHAsWUSaMyhsR1hfx0QRsnPyK4nk",
	"pYgljXwG4cZ2NYPwWF66hE10Eq53BlSz6A3Mum7nK3LnIfXNPkf2DHFWmFzHhZ0M0haK18HLDB5wAPi/",
	"nBx+rJMhmE/imTowzOsLXIounl7gUOeyE7MLFuM+NWnudp6/bHVL4l7lq1oxDqJu5xjEIJUTTNkgc0Ea",
	"XoQ7ozzOFGsTPsTXcCHdKV8fmvWXEkU1R4p8nyVUWIUgAsRlV2lMXWUEF1rh1lGd16dOYeiSw7y6aesA",
	"1F083G+RwevnAlkolCrqLlHXp1DSTtVuFNlUsN/FSHQMifA1h3J6ekQ2eq88U0PFDRI2ZhgvINJmm+x2",
	"nr9CVc5ijeX7gBhMXLBYpt4SnVJlNXEjUwdWSP2dnIzb/9vnAIM5+sLnZE6NhSZln1cW46pCKSDLX4ST",
	"NhlkBrNTi5m8IcQiGjeaWKbmZrerdnvuoVRgNXQlLzVaWy3+C+nXF1jerzjTrS7JTwq/EpO+gM/sm2T7",
	"4y6kBDOKggRcuBtQd0smfvvt9sEByT/tCztfeQEsqtUKHNbNCpRGZaEVnyOPuPaIoBpBQRy7ZC9JzaR+",
	"x91VA2LqaPLX2fiXmToLdWnwUwRCZcw7OLiuXCCdV9ShKFVQTukFx0ZRRsI+m6q6UJSbeGeXYsmrK/Vg",
	"lUoks8BTofiBkxZ//nj420dysP9h/3T7dP/w45ZbrSVBJMhvLiglT1vEgENHkl1epcs81EYqF/3kTYP6",
	"jVWPIDCkhCP2RodSMaF5qElTM0YsaHiJMz/JVr0dc45kUJI/8g3U6J2YRLi/qy3pci6JYWZx0fHzNcfK",
	"HTHTK8NTIQdWQWjaK5Mvrt2Y4T0FsdspjPcz5gNnhJ+Ob3aflJO+KInlCFTrUCZJJlyCHklYxLOENC8k",
	"D1nbjmjayBNQspiQmItzcNXk4aJ/z1iGcmkm6uKj63R/XFGeprWy8+EpFWqO2cCfKFzcmSsd9KgNCAg9",
	"ZwA9d+N9250ByIryQ5XiF2V/vccX5zkhw1heYoQ/OK6cMS53sGBEtZBVwF/Z9/ZkqfjeLBU7xx86O+87",
	"vx7u7+zdf1zTB8oF+dWiryfYT+lKjzNdqcK9bm8DKDO4Wbk3L0NSdrEXacQlvRVIPy7P5AFiderrDizO",
	"pYKXqowsTqW+31zlUgWXPKa9hj83U4rFQcpVCuyM9kAwoqQ24KgvSgFHftAz0MJb32VWMXAkI60udsFQ",
	"Au/Op1EFsFUyiZyu8tB8yOIy81Tcaax3kG86S1JXTgOdQv4F2Ym1CIz4NGLClLBpQZEI0O7tR85Hmie7",
	"3IWH7BFh0i0D179hjl0FM6aLFnEQbNz73gdbrkqHZvlu41Eh1TWDtJenal0vO2tetpU/znJ8cQJZg3kd",
	"VoRhDE8Q0mWWdG+b37RQGa+LtZ6P+iW3/lx2+t0j8+0d0zM+45Wdu4+XVV3fmznLpub6Gct+w2XetYUA",
	"PNeDNR+mnVQ6H54f2oTziFDhLo0td2IHuY754fHi0nX17Zvp0AsRpQLV85HjXSwvl1L6ksIUy8szLgYy",
	"E9GZV9NuJBFd4xpHiqbj6ykenheDIQy+r8o1ua0ffkMjjkvFKQk7xWHNXtA+HgLe0bXuZv5l/GIxZ74a",
	"G16eaRZWlvGyV8dvyncPn64kXkzRtoSLffxsfdZl9N0TPiRSA0ysegAY/qak6JfO2/2Dg/2PP92MFvn0",
	"MwDPRm2yGZeKm0nls82llqn5BEs3SoO2c8ifjznHMjNsrsq6HSVcrBmrtTJh1ASrA0JcPlQips5WbsZK",
	"ZiMsX59mg5jrMYuQhlhFl+aWq//lxrE76M7zCVUP8aKeTlgoMmpyNktqE8pr1Y9yIDsXaWaWUcapI5u+",
	"hJy7lBYy/6BB/fjjqgaYUIbSkOFMrd9YFiodQPlW32P1JUd4CBd245yhfyylkwRi+LhOM4NZoH8Mgej9",
	"cefk5/2Dg9uIRLNZsPWqeY2dV8/7ZCFFKo1WhxA5VNW12ZAa+hhkCZFDktBwzAUrxTJB0IydzYVttclu",
	"59VmezoZtC9KWaCtIg10oKjwtfe5y9vAyqRQG10KEmCUUUCkAmzoCxcqRGMsONoXOEfvRXedUKj2EkQZ",
	"FrhlQAWCdvlJCXSCtoXWvgimsMlVToKjRmeb4BdMaRp7rxpCkpmQREYs7gvny163+4d/bfgI+zyErVpM",
	"t2gBY6+pVNO4VMna+S7OQimGMQ8NODGk1mdSWU5f3WTlQRk92rO1of2DIm/IPqzE2Nm/K2diVVY7NNTJ",
	"ZeVRcg946RlcZK2no1q7t6ZPgyerU/FYFro2W0XvgTxj7cXV1drm1VXRLKgvgqL2MMTFlHLTBxNLfJFN",
	"aowHVJkgAzaUrtac4wn7u31RaiiA0bZFWaC8SH/RgKDcf4AbzeIhRhG4AtxrRXF0Xxa7tTCAcmkFZEDZ",
	"1eMOQ1xmRmOfvg8NENggG40gdNkj5YdPJ6fgZ56LnRxCV3UGJATsgWPMLgf4JAkXUuVF+qdZ01RB8tpA",
	"yqJ09I3SqVeIUNy7StW7TISm1kt6KOC8UBbp7J4ckKF7lzS1Ud1nbSKyxP6HKvgLYnfsPyJqWPdZa1aY",
	"ol6wnPIsQWFZqkZZgmJAJgxE3nbW4X4uqOI04mF3aebFLKPJ0rT+gIWeYium9jXLNqnJFJt5uwtDN3WL",
	"dPpZr/ecEfdV3ShZAsaYyhif7Pch1cs1TqFLfh8nRxcLK4Zfdsk7GHs1K+v5m11dwazAzjK7dTF83Qrf",
	"xfXh5T7XC2T2SNGhwfhVVPNdHHchg7omK1amVIYPaWhI89N+9W0XVyGHxKjMjFtdEjgUDfwr0zEAil1w",
	"XYpThoW0XaGF0BRUMGcWJXWjiv93K1+XpGpyvTCxaonvu7ICLY7PetnpbTxwneYbmJoK1lsYm0hTgGz3",
	"vwiLRhCNnHf307rj1UwuyImhI0bW31g6AFHBEF7iap5AqCwwWM2TDIPpUE9AYEEImcGN2wXvLLFr3XXc",
	"zh3d8d2nyiAk3D4mxlKqPatZv+Uisqut6RiW6twEUbZPNOvMDVB4hxtNaAidoabsFG6RNXwUXi817ClB",
	"fclgsQRFb4qBZRPHbBKKJSeLf/Uy/XUA7zrv3g6ob3Iqi0GxzigzexTlo2v7G65c2TyIPEKomZdlclrh",
	"TXlImwsfV6wDcwGFSuMMmeAA4dsKufmvs2A4KLBg0UnPYE0Vx5d96ppyzZxygcJ+HfMO6Ne8Nde+1hmr",
	"F3VL/btSJQcxS6xEG8K5UEMosVygDTwAZFPscTCXq8/K+i7wvaIrzmJXNPLutqVWlTzfa+mbCdOajupR",
	"0m5rtRnr7St+7OWHXwBo9ci4vZTVJc+6G61JhIH7rCOR02AE77X9KuZuY14w6bZYJPlZqZECNW/nzUoH",
	"k5zpE7B153VdSQp5lFOkwYKfNlSZN8QoGjJdBNwTbmpFyzug8xVCvkRcrP/4OjT4Jm7B/NS1oKkeS5NX",
	"aQZNgEVOfqPGnzcU1+jeVs66ds2mmIozvISzFWWbwvCFiYu3koX8ZVQ5zNQEhZBUt9ylfOg9o7EZz7dp",
	"HfALJqAS3piBUuVyzJq7nfVXNZaCokKSNx7S2DLEz1MRdRfLlWc3VN2qZ5ov36I3dL5OKC7fyEPL2uie",
	"1IUkoIvoTfvPcr03XWsvzFsJ12nJRYIeLxoK+3p3kDX6stUlOwXtQV210kv4DYEWkSggcEqCn/ZOydrF",
	"+ppUI73m23K6DsR67XcefQ2W0517a9Vjr2GlCJ/Z5touc1evmspZZHHqN9j1GpNiqSbT+b1dfPe2CZ1z",
	"mHDO13CWM7uiyiHXFhq7T7Km55SkOuBDFk7COC+a7zNydjc7GxYWg5SBvBbk/cmUvCSXtGjn7TTlVMmQ",
	"oZtwwEZUvPH5Bc6rpYmwEAT1SAeQ1ok5QoFdd8wMi8BlkucTl7NAfXNPriHJaKykkJnuFi8nkDZKNDMe",
	"aUJF9bhjUQvLxF0ylmI+63rLJff6JUN/NaoMBsJjHi1K1JCbbBQVEYuq3hH3Biivbvl1OZdlo6JLzZwF",
	"hh9e1UGDkYbGsy9Dc+lrcZQyCpYKm5XGn1ldFXCX8hPXDfQ0984s8Zn47JqCswxLnVeBJnewOl3h8CmK",
	"oz0v8ur3rgwT0bRtccoRg8Vih0omAdhwAiNzYO4LB1o+CJuklGP+GXGdl10mLI1jecmi0opIQo3iVwtd",
	"ItPOtJIDq7YohJLJNQsNFr6UgoILac64OHNLPsN13o3fwsLNtVa42NHhtgyj1kHWER1xYUHvgNeFl+zI",
	"JLHqcaa0VK6ARIqf2AsqfHHYEwPydqGWhvP70DjuC82vpqUG6GLg+a1GLgsBlYErcCfcm3m/vb4IgI8E",
	"xEHChFjCo3iELt9TLOCqLZxDwrtEs6Rd88sXHSasoBeRMDcGyyEJfi/wrk0cG99xgzivK1ZNgXbtloI5",
	"Ig4SdJi3ycTSeiVnWV8YOzJYDMqrQcjokl3ph8Ss/1AKNJP6PWCtrTrQH1N9lkhVg/Wu0JAvzqwYLN2+",
	"6+oUaDJgEyki3wh9xMB7OmSKBH7YAI4VBVNLoQPBrsyZW9X/8yOxDBlzSMMYnC8VU23J8pZz/RoR0hXa",
	"tSuAqtG4urKsUKPClhZSF+FRum1/iL4ep/3SbTfA9Rf1HZyfI6bav3JELeBqEvwZh/kR/FkhVo0G11bg",
	"61LBwA7HZ/JqJn/5Eia/jqOffj3/1413vf0vkn/4sj35yHuXH096Vx9//eXyw67E/38n+cHOX9J/29l/",
	"uf9l++rwdPvqr1/+8uXgNEo+bOyZjxvv+F8nvRf/tnscH5z+mnxM9p7/9cv4y+Fvv1z+28lffrh2RU48",
	"5nYBTPW0wYTjEq1ZPW9qGYfZaJOC1/gKy+2+KFUcPuFiFJe/hlRiK+lgqentqVLTUMzTsRCcvihgWVrC",
	"s2fFIlpb05U7/+M/feXPShFQ+zh/a+YXV7Wz6c5Xk2CqZnVQre45NUn5cXWSvNrm1BeV56VPSuU/QfCb",
	"2nZIhaU5A3uofDRiVra3hBfQwNNidybl/eX1Q0s7nKpS7XZYVBq137llztsKWZu3E9K0yzo9PSjK3+L4",
	"z+BFXza0nVcQhcelz2M54mItliOZGQKl4nXLHs92GZxqRA/k4zM5yi7ULlgshQV18tOskfjOy5nnAYZY",
	"ldvIohh5pXo5dFIqTGW0CqaB64poSb7BngWg30k1suqy71ReqXi3v6vdWRVRiU3oVkfy+KVcqfHRUXRC",
	"2BXXlt+aP2nyxa4qE85b/Q9X6ABAUqpRa8XCDdDZYE5wbC4mkOZu5/ULX4UZmWXbhf+40sozsidp6nOe",
	"lkAhmBU0g5Y/IavNQC937ev7ZWKLUOJs3tWm7zNUIq8JOBXoCcsmR9wMLfF73vKlGEw2ANsegq+VMiZO",
	"E4QeCZaLBXAw2PvvDblYJ9ufTt+TFKLjfM9rTIa0ygy1xxUQJWOGbQR1Su0JuzoTGFxVHhLJMYPmF5T8",
	"tn380VW9olnEDXHynpqQZoAJmPBtF5rNsyhozRMdHqis+4dCp8UCujUl7atV3VEW9cBSrggPyFctCN8l",
	"+yMhXegvFt4uUeQVIft2ysA8ob/ufGolNcfC8xKcZWZuZKlOoNu6K/gMOuN0PXxnN3DtaKrF8bcRJPLu",
	"E8DFag+1YiRQrtKzJTf47zqlz3kEp/KBqps98ibxkngKsS3eag5S/Kzj0Oq73idopX0Mpp9xeD90JD27",
	"SlloFRu3l7MaV/Mt+c7+0GJOO3cmgMgBBh8W6aJDjPNG/ilvMuG9+/4EoUII06Q5yqiKNKEjyoU2ViXK",
	"9QScYk3JOB7Q8JyEsRwMmGp1FxY22XOHMHWhfuJmEdtUTBZO8gXk4U3OvJ17s1oln8ncBJB6N7dfax1W",
	"Yg5KjU0bSyVNFwyD1zUZy7hayotcUm4cGx+w2mZQxccUUkTKVUvaxGentBG4awu7N7d3fmuB/0jVtnkp",
	"8rmmNlM/FFlzaO7GtJvVLJQi0o5dTxWptwSmXSInUHNde1qRixCJ5Yl+oKp+tmJ62ZQ5pFLeBabAy6Fh",
	"yFLja/f+rY+YjDV4wzE1/cbn1sqm8PvPVvvDV1q7ixy4B3LfPJUc+x5Ljl0r7/B2YYtLcxSv7YEv5TRW",
	"gQimyBlAl7zno3FR+N9y8tDKOWN8XLwH4OJkNx+nzKwyCT1TUGk0kAqWSPvT3zMax5MO+ITndSDfrKPP",
	"32lx8hUSQG8fjnnMaMQF03pnzMLzOpcuKDdyiMw04hc8yqhVON13aPQte+/lecOKfSNFozlet3zS+c6o",
	"XcbS6UmWhzxgj5LZ8KhosAzQp84BOOgI63LVjDdXetzx4qpTTfJBcgEyj3XHmc+KaQhw0e71Wk8vkg0V",
	"i7i+7sanxo8GDT9Q5Ujq5psNOJkBhQL54KeVok7a/lrr4VczdUHNvLgyORxizXKvX3mndUmybaP7iBtN",
	"4tzxjraHO+hFaIWIJDWlMLqy6HgX0cSo5C4a41bMBY5w8Rpv30cj95euUB5fy/hi8XqWD2Jh4ewmjtbc",
	"qpTDOB4PUGUrz8M/FfsCWqQ9G54wmUHWJRUhi5FaF/EJdQTynsOpZ3bfLndbwx0WgFuBgAq4LQ1BOHa6",
	"90IrynERPg3RH1yqmiDQfz4bSW64uEcjScUmYuTZrUIm55gvZoetB5VFFSsgAL+kyusUPDj//l9WJvAM",
	"QLed3waNEHWBvoug5ZukemDHjvyF1UDnGKXld/gx5u9+no43Xu7/uDXkPlh03Gx8l8qEwH85y1V9zFeZ",
	"6NYRWoCRu+sQDMMVlqSKxNEm0gIhu2Ih+J+hn1+qZJSFYO1n3W+XSFNIWsvo+QzgzaLqJLUKMr2SQiYT",
	"iNTwSaj4mXahtejjmJbLLOZaSQyOsqxW+ByQnDUA6QWpdH5yiJBnvr/WWUhFBGmE9hur5acxO0OSeeZo",
	"qS7VHvCx3CUCU/LfFdUU6sDqBPMT2UK+t+uaNqIxuZTSWM6S9Z4ER7r1RJgxs+9DqZsu2ZUMA+Kg1y4j",
	"MXSnL9FE4iMryo2Cv6f6PO0GHhqLzthwyEJzJjOTZkZfL9Xh2MHcWiLDcxYRHKsjZMSIG5CcswmaJOAp",
	"ry99lq+mDBgyM6FM6qy/JQWF+Ldy9ZALAtUaiZaoqWjixNu8pSdAB43jycqWYA98J26hpRUc4gJqc324",
	"MhmNz8JYhudnEHlb4/DiwiWB4xxS/UkT9yWBLzHLxu7H0uU1J/ySlJoxdCmJ6aR+a6voFdOkbQay6mhW",
	"FRfn2Ru2ywiIZDzP5PMaR+1Om1r6fXFN2BUNMXqkkNM8ZfPlQ7ipsVzAlMtu9hReWvWyLEOqrhibx1kx",
	"EUxpBIIum65tXG6YKPiVco1+OuFYar8lt43WDS+tbumODy+8vgXQXHeZ7u0yKfTo5+qV1BPfLvkNApNd",
	"Sl8Ajn5uSGoh//T99mllRPvWn7Rv6AQW7IgrFpp4QpopUx1MeAQc73ARMSvAMGFaOI3FjHymtu/VBT3a",
	"0LYdQbyVHQjtGOg3asZsRMNJbahQ2T5xfWmulMg4081SoFaCUTbuJHmOIPn+gXlRM3NM3VozQXGDee7P",
	"EiVayBIj/7wM2vwEtZB1zuPabktYsHradQqvY2BvxT0KZmjfYTtVcshDDi5hBVXgu0/tkVfzvt1VqbkH",
	"6nFUqWc3x6sWSzHCdg+lF6YKwc2pf9e2J5WBw/ouKuE9uQm/nx7K1ywMeDd+wgVFBK+ttleKDk4XhzFs",
	"JNXEyhauvbzTdpDo+m7EhoVjoIAYDRFTMcroyMVGoNJsoL/xO8UYgbJpPmY0jalBnPOqkQ9arORHrFAM",
	"8bv1HJZu4PYewlMvmc76Vpx8ojIB7SYtSk8L0dClFrpJO00fcB25cvf+ku7vxKJzgoxtZlOaNC/HPBy7",
	"UgOumhXGMM8YrtG0+uC2tnMuorJY5e4Iip753dSaLq6L7SUR7kZel+sfgzYsXb3UBYDviWHp0gprVYyC",
	"A/STLTWMFbPM1gAuzFLVVc8aI6dU8sg1hjqrS4nay+2IzZ2jTxgCl9NSw1IrvyY656heEbRaOb5Lowsq",
	"QrR3gK5ektgXiBfOhG9FBrTGFFba5QKJT8BcztRExK7qXaYr2ZCWdssqaTr15Vw8AtXpLHexAGA5tTo7",
	"TkDyqrFgjDJSnjvuaAdcw14hxGtL3tDSWkkwnOOo91mg+pynKXAMnWnQWKPlmhbeWHGw5WNsLyog4VC7",
	"Rg9znXubx+92yA+bLzfI//0/m91XCOodz3xQ1itX9+uLX70DLNOQuvTKsiaMP3qDo74AqTqWl0yBRudV",
	"TcheBh68RYLe+g+99cFG2Hk1fE47r+gg7LyOXrDO5vAlfTV4Hf4Q9VgwJUys8k1ZUsgyOKuZK/oETHm2",
	"k9+SHDrg5b73GH7cJfsijLOIleo05rYeyGD8ae+0mvM9J8bZtW6stztM9RRcsXkg5BdBZJcjXJD6gBVi",
	"m6WaQFKbjmsW5eoX+ArJvQ27nqOaUug4ynVLoGN9TGz2z3WOYN4cAHXV+wIO3EhUJ9QFI3qSJMyoCRoC",
	"7JtYLuSZvyKoefHGderuC6nQPWsX7SLlMGW4I1NtFXwBhTJc8ehpheK7bmwYxoyq67Y0vKbG+sEBjn+p",
	"45JDvLbpjSmvWj51lwgpOtADpS/wLOxam4q1Blz4QPhcM1Ty8g1mS+WdU/Cjvgj6jX4DSn/vHOxtH1dq",
	"wTV943RmNCltwL598ssB+fjp4KD1pi8k9EfL4TDvBgk5cVdQNnWUD5oJLJscdV2Z9M2+GPIr8n4DuL9L",
	"Xrb3UoY0+zGMk3E9hrMCoiDBmyZFX3j7l4sUkDTlHYvEI6tFS7C9E0iQh40NpBmTiIXIqwjtC8FjEjzD",
	"UwlabaIxQRAOq+NO2OICh8bmaIeKZAj1i1nUF6CgX9JJATJk21uSQKlWLGZ2uwmdEBpFhBKjOOYP98Wl",
	"omnKXM0Il+sWc8MUjf2J+HHbVvt3Aj32wRizvqhf56VVUgeMRCxVDAvbDTLjkvDGUkjoKj2Fnbdrerl6",
	"T14ffDinBW+pte5//8d/Fs10b95Kd1HwoWNg12udWWFfmHTyEMzriTfdI2+6q1ahd9gF9ImZPDGT75WZ",
	"3LDZ6+3bub7L4rgDnu6QgS9iuq8rAcMFaR59OiWaJVQYHmpf9OSLtCAAoGHh6PCXznq1GAc5xqF1nviv",
	"MMuaGpm4MIG8bywCMK60BLJwVHfYOvbeee2t+evN+9M+cbc74W730Dt3Yb/cJ9b1xLq+Y9Z1w47KC/sn",
	"z6LEXKp9+G2p9Wzn5ZX1IZ9u/0AK0V23gH7iNnfCbb7r9tRPrOuJdX2vrOumDcy/a+PdSr3Qb0vnWxYm",
	"ViLmZD4tRxZ2u5bVN2x+Nbc1+upXP1NyqJzzWM+9VygmtPx+V26v/ng6qj/JEXciR9xxt/cnzv7E2b9n",
	"zn6tujxz6Xu5Qs7cZjSPTie9SQP7Jyp8J1T4nprrP+lkT5T7n8SceM1UiRulP1TTGVZKG3h8tN5FRO64",
	"pPUbdYKZY0dM3NKZ9ibFG3WCcQhRNDRyqaeaR9APBppxUe1DnBMJLkf3l0/GRzbwaZ9kmunSmEYSPZaX",
	"fYGcZi1hasQIHQ6liqgImceiTEO7AEE0Y+TSwnjFtTjFG3H0Od0qXC2K8jZ8EpHfDNKicuB2sY8TUJkI",
	"ZoyCFxVRyQ1xSbUrMOuyN+DY7KpTpjr5PO72nP5lN1GOwvbBvz4vYWFJg7qONv5DDwIP0YS/nZ/7LJxb",
	"bGVhZoUwOD+8p0M1es+oc65NJV1ihLELHp4AdxpD/Xoq+D9cQnBeK18KS/JIsHaxvhYUjWi6fdF8d/jp",
	"426n97oFABj4dm8BJL4TzUYArVwDLVcUyvR4QE94FMXskiqAc+rQZQxLJuwqjDPNL1g8eVNGtQEzl8yy",
	"DAqNbyL/PrKivqDxJZ1o4lt1lX/tkt3iELZqF5xSRRNmmOqLhGMnt9Iolhgc752UvfyWWhdtI7nBHQY4",
	"aoDpoRE1dEABHCVIC1ZQw2XabSOjDP61c6hGnf0osLjMtZXVoKZPXxRV8O1IlnWf0xHzXcPG0nIL5hrq",
	"EBZBERFLDY4PSH4/fXGoRvvRkd2kHwCqIzk3CLdQgdv06VRbDb+kArxpyn9mk8bXr5CPMJQoKkN9YpDA",
	"8LvDlAniSqY02o1MxXZwY1K9tbY24macDbqhTNbiTIpRxC7WZMpExyVJzQh2DTjyhAo6wviL7aN9uIry",
	"NABUIDsNWBRZZth2qYq+XLMbvi98nlyXbMdx3mpp5/jTbrtcMKRcvb1dTsKExFQrzwwV9d3aWak9k5WG",
	"IjbkglngVNhw6V/+hXyA5RyqEdnXEhOR7C970CjAf04yYSEtmG2gGFiwGZUbMQaHarQjhWFXJrDw6rHJ",
	"iaDTCP0n7RMLnChWgFxeqgEhoIsNoqoYUcYVBE8rxSzAib6oIgUqOAXsG3rOSmUhHY55iH3eJu5fmy1/",
	"gsC9yV7eRmu383wTeO5LbFgSexbrGQDSAVpiwSC2gnKzZT8JguCLtvfwO+kjwe03tki/gU2Mcq0LGxlh",
	"EiaS4/JrETOUx9V3PO0vv5dlPLp45d8jX2F6340rgNmDkipHwlhqFhHLraykz0iQLyhwrK0FjL8vgmLG",
	"0hCQFcpUx9+uu/7EClIFFDmVb3+3AkRvCAe67Yt3SOGaf2DZIu2KHWTCN1ysUnR/ZXZKsiOFJWWQs7Xb",
	"Wf/B3tlGL7+z/V1Nms6nR87ZRLdzAtq28MX4SMDzFuCW20We2dLti4WpLU7OcrJdj6z51n52Ar/Oo6JN",
	"m+/OZn85qHZes9A0p7sbSmA1PdX64ppN1RB7y53E0NPdF3Cfil1wmelCyJltvmXkORO++ZaRZMishF3t",
	"7eX2fZKy0EvjCIpcE20fIg0euLg00J52HK18JzPh2p0nPGbaSMG6/te+sKS0dGhQmQnJGsBbHWlLFRtC",
	"70JY1H7kBLkPMmKxfbhTbojHHV67PPgmXHlINWuToN54ELRcwYe+yK5TbsLNwDVRJVkIWrv0hYdYt9Ym",
	"FsRou+i8NtYs0W0fwKDbPjFJt/ui0ri31S6AouPyuiop/FgLoVTyosbClC98w5UHXGiSgcx82hcRwyrV",
	"kf8gb23VLSXuW6oCMlwiTd4c4fDodP/w4/aBZYWGuQK5HW8RQSIEqJdWqhOQIC/IURq/1Re/vd873qtY",
	"MfZPIIXz46eDgyDf3su8gdD2PkkZkLcLzi4twPKR6AtcCIVMtm4aU6iXtwZtfPRa73nHcfxOqLKoM5L2",
	"0c726fbB4U+d/d29j6f7p3/tHO/9ur/3WzeJgr6AkopY7MUhnDJ8SENDgvmfdo73To4OP57s2TFQxIp5",
	"yJzW6eSk7ZSGY0Y2ur0ZKeny8rJL4eeuVKM1961eO9jf2ft4stfZ6Pa6Y5PEELvJTTwtdlkhqZT5vtXo",
	"de00X9sNK2vRlDe2Gs+7PZgZalTZZa1FMoR/jFhtkA6aJinIRzwk708/HGBXQuAFsfQi/ElIY6pATjvO",
	"C6bYO7KSOKdkZ/ejZQQvNpF9+Z+ATFn1dc2tsTuhSVwK83E9tviIiy45wqaSOfTnHZ5ab7yYxMZcRAQa",
	"NUGfJnh5vUve+i5WZQmqxLzs4jbWARQtglhOiauFe7SqMIDYftTYavzEzK49NaiXh0KHPbqNXs/Lxk5V",
	"tpOswZVt/d5A7l1jTf86I/3mrYcuCnsW0t78/LsVDbCx9bfP7YbOEoiRqQ5gr6QyiBXt6UhbfXO/ItA2",
	"Ptsx18bQm/0fS4ECuOtGr1dU/3KmSd/UGOQ+fsFKlfuwtnkkL4U2itGE+DJRIWcae2oFa9Co6B+Bq13F",
	"UoIrwo/1ane5/gokjvV5F/jebXLpHUL5uhC+XfvirALFVS7S8ad63Nfc8wmeV35OC+80b4kPDdSWXWIZ",
	"nZbeJBpVrRbFIlCxLMw87/ZQKhhMrOxXlEzDaqRkwIVlhR6pt1HCh6JwsWtSZb92tmv7KrTslknKsaUB",
	"Vnm0jEtIS19iRoZWq1Vcn985wrpdWdnnenfuD/Aa6Fs+wb9ufziAg1h8uf4TjetbeLWIHnMvta6bQJcc",
	"cTHCiz6S2owU0ySVMm6TFH44ZhF35ZcKs4y32wcz5fuDwppboQabvefORiEmDteHlMd3hLPHuPF7RNnZ",
	"Zg0112v1F/QFoTFnAlVPNnvPH3YZhwKq0ED34pyKulPXBGsCLwa6fJrVSMrF+lrCDF1jV6nqDDMR5g0j",
	"auHwBCSGtpVly+UAc+uLMwPnAxF6QTn4NLyxYhjLSxJKgQFJUFKtqY3qPmsTkSX2P1TBX7Ec8dD+I6KG",
	"dZ85EQM+H2Q8jpj6kybbvgYIi7iRhegBRf6g4npmpDdlW9UmHDNoUlEPjHtXqXqXH8I9wmR5IqcT1YHD",
	"Kfj1UsU0hlO5L/KafgshYccfcmfBECvAR1XH87pPCUSqx2hV7W3/khVKnd1Jzw3LLV5Zwzbkv2RMTRpf",
	"20tfP+AJNyu/7QLPd7kG9/HK332kCTthVIVj98nnW0LGiv08K03q7Tqr7ps8Ym21hDG8ktoiQlNeiM81",
	"kJgvBpvYy2GuBAOhfIEnULeA/KTW3tLIx2kAbV3hk33Xjx6FKjCbTcN8xT/yt89fp+QrbfKVlmA9B9DP",
	"X68Lorn9HeDAKvA1sbCg0etSEROi2IhroyZEyUvnZ7Qa8L5Te3xXdpqTUudky8sKCklOdn/Om++37YO8",
	"FjsSxwCrVlSMj8OpwhZQyqKG+uGSPZTkbq+3MprcGdWrzJGDQtVfZlTGvs7g1/qdrSHHgxoZwF2Vs+Td",
	"FLBf9H64Oz5R8XPXrHk3w6FzK5qzNzmnAWkWEUeRfxVqn7csE++LqPi+YiWaGubSlc/ti9oBywYgH23S",
	"e9FdJxS0DzNmmvUF2o1QgJVWV6RgVzQyx1AA9FSxjvvYPR1TxIO+ODre/7B9/Ffy895fmzxqkdKQWpKN",
	"55u9TdBIeJJKrbnj9A9FbRC+S1hfT3EW8tW133n0FSmKlVlm+esuPC8jagVTXtQ1BEe4jhzjWx2wXe93",
	"S/J28aMXyz/6KA0Ylh/s2E/k0HTwuJaefbteaPmJmbkn2ntI2oNU/+ak5zHez08s58FWo9/fvXNGvFyG",
	"2wPjfplxQ7zHbIMAb+OGqBTXNvC+CpG1oYzA2vYLyCHxwRFTsaO9H4rgTq+8l2NynJzgiPVARpM69l4p",
	"x3ZP7L225NtK7P1BUcwFHD0Yjl1XHpCCraAdTEkG7VW1ioWBdLNKRilGbLVjr9EmPtea0/JAwjJi+Agu",
	"iAl41S5lTE3HeLWwOvZctKAVgupwCgOq87C6dl8cHhNKKoJJHHPQlBXlrr8rxfBr9I7ozLU+oaIotH3G",
	"I0JjsBuRgb13dK1JM2YqX0khTi2Xot74kF0CEbvrrS7ZgbggTfRYZnHUFwNFRTgmUhSHhDV8U6pc0FTp",
	"yKHEtJOFXmxsPJyA+jbTYI7qqCxm5IK7iJmtkk+2NuC+L3I/aOuNuwDX0M/FYGNkI+HGE8yF4fUrhLY/",
	"FD9EOnlDMRGc0yv49tJZhR37DZf7QHw8PC18BFLgq2BOAEkcnPOWp7lpQTb1Beuhww/lMXInV8qmCXVx",
	"Wl3ijSy+vUQzcEH7P0Lh1wBDQCA4MIIiqLHFvuDPHDnsmZdVf7QMI3AM84daIzIYnPBYnsxNj8bcZC/E",
	"jrRvWHKHRicHTcOYogUE4a71HRihPITmmI4P7tkARQS7dNGQBf9Ba5Fz7CYY7OjDsQIeBbUBM1REeT3i",
	"amyLG/XNbKCJ9H037Me1H+WWhZwuhVTYKVIlL7glDdSgQQaYGE8YRB5AABLefYBluxbYtOzu79eiVS4S",
	"+dD2LNhdnbgLl+5tWaTsFh5mceyAwolHQMNzToAH+1D2r5vKuzeXcj9/J4a0d771oQbzVxuDEb3g3Be1",
	"krMUTlqC/KdYS6IzNaQhgyDmXPUsC0szsvW0tElyYbP02WOUNk9c8DJ0h3PhoXlQNGSYOP8WvIA/Qygx",
	"yPbg1iaUDCoyK7q8m7udV5ttcny4vfth+8iJ58/JzvH+KXnRJvZArsjOhpWeFHne6pLTS0mGMb2Qyp4i",
	"hchargkWkt8iTdoigQ9gzZtKYfYQ9bTtb5+7mL3FIbbbd54iFFG0LwghuPS8VwykARa9v+IY/KQAwXDz",
	"z60M1RyUJod47tmJS53AgiLmW2YGE5pwZkZAYNPQtBPE8fXOes/FnQcgegdExxJWVLm9IlRTu8wgVS4e",
	"BTHr6O92XQP8ynrVpbW+kYHXMZUZbr5Aaq8x7U5Bb2HIREKNNHowsRQD1J4pKRoZuaPhqcVibbS/fJ+u",
	"4iKw5onWXuwvAn1NQTJ0saJClF8gizvjdM5xl5qmR64p2D+FYXoezLSXR3LNsmy8Tp/xlfPuqlTkkR4t",
	"jdt5yK2lBxAfop3y7I2NL5yv0fgHz4vco9qEo1k7ev3l9x5K4rlbUebR2tM9Zaha0+9Ap7hvW/o9VUW/",
	"YwP6EagfQHI9Qqma+r5fJBcdtF1VS/1CFeHOTBVh7W0vFjfn1BGGGsH5rPU5/kXR4pnywbV2/3tUgWrq",
	"5D+0zX8xQfD2/lkVyKce04JwPDC9+KfwDbjruSvPQDlH/1YegjI3/Zb+gSnrzPW9A0BJPh3tbp/uYQxE",
	"X/j0snjiZTkoPrDZ6xEutGE0svT4hRXj6nW9vvhOPQvdYtWk1NaUoc7VF8GUawA1n4qDAd0Czr9AfbEV",
	"e7tc90XhrshzVqyC0naGgzcLUrageskGNGEtOTcq2tgqqmBfzOqCq6qBfZGLhFUOVaqMb9cUztEQ+2JF",
	"FbFOO+wLUA/J9bVDu+XF6iFabaR6FIpiycVzU0VxrWhyt1Q78OStnPbuCFvz5HT7dA/TIF1tkVRaGQSs",
	"EXm6OuRCkv+9STQLpYg0aUIyuH01b27swd1HI57sgVrxfLflVEyY+CyX6IyELvWhcYkgfrAiq9sv7vVC",
	"ZeIED+K+JQg7TS2h2Zk93T+aplqoFLC9aXjFo3kkasW+4Ibn4bV2eZ3pQg85YG20ZsW+vvByX1BsDuwg",
	"Ogshx80y5wtpeTYZyjiWl50sBY2kacF9B+sYPHu2bX/y4mOHu2VF5YITz56VlrLVFx0SfJSY8wKVkuBf",
	"ATwvHvo3pp9Dr4yANJ1krUlQzj4GG6FFTTffixZ8Dh9Nz1U8rM71m6Lpp3T67dLT0ut9sV0+cSFzdpNQ",
	"o/jVAi3MkXIW9UVg1b5gLTAyICnlqqyG5Uf3vCjI1BcBEyM6YtGZy8eueqnAvh4YSX78kezhi0EbKlkE",
	"/k9g4pjrU7q0PM7aWblCKuyWNIuHndI2jSwG6gu/QMiVK4ITipCEYvM5My0Gw6IFJ960l0ptzrhP8pQC",
	"GtOywPK/mJXMgVyX9gKlC3VeUsAn6XoXPdQJcPfHrlKuJnVY8rKW/B5Z9JsmwHevP05P8y2VyLks4GSa",
	"wACpYNEKauU1+cUDK5SLjsSxrtN810tFcvfFTOGdLkE8Bz8w4LqvWFWlB+UTdvJ2mbBQR3AdgakhD4/P",
	"4YTC6QyhtrsagiYoFSkKQzVz4t0lJ3NcVZaYDeboPg8o4hZgsYrkUCvtukqVi3PJ3sXyck8YNXnr374l",
	"FbhNWMv0Ypb3ZIdRayq9zRqrMLPfn0lOwqUadR84VAVXAvWBCLO7LVbVBHx1tSlAC26Vrtwez21DWuoh",
	"xeJPx5VZuVH0G4xA3AiVwwW1CEE4YvrcyBSrL4KCZCRJZZrFQM+sXFJaCEl5eM5Ulxy6Vt6DCQkq3bAC",
	"QnXI4OjmRa6VGqA9xa89nvi10rXcXfRaBQYff8haZbklLK+A7F3Fr9VFbpUv4T7jt2qaED5wFFcF3GpM",
	"naWbeEpPvLv0xEjJNMUExcJkToJPH/d/+bSXl7cSNGGtoJSz6EpqgL00ItyUHA2Z4BdMaRqXymPBfrzI",
	"ayYkkRGL8zpYEEgxL9zq2hb4Bw2DqVCI+QRiOUe/fmRMeeaFATLbTp1HG148QU8s19URsAi+IXQ4xFqD",
	"CY86GmsmvHE6CrwIhb6FJLEUI6bIgJUqXFihQrBLtNOUrUDzI2WmKdyyeJkKIfinCJtZEcbm53UuPOLe",
	"N6Hgf9Qkz2mkrMSm3J3UcK8RKpVN1MaprBKMsjOmYgT0yDf6DKBOriYMKAzhScIiTg2LsVEmXYlMOc+L",
	"r9ZVIjGud4NhSmWpYdEbghPz2HIc7kpGYZZPbhj0elzEQvBpzw8guX9JbG476Ae2A14Hj58ySe8+WqR6",
	"/o8lm7Rsv6sJGemLImaEXDdkpC9KMSNkpZCRynLs9Avl6ZXySvvi1rLnU17p48grvY1Y7qoPrWGJfDCX",
	"3jebPp2kbGXjErYVcaSnsC/VZ8G9LYr9I5MVE1+h7mVeZykvRd3c/3CEcRLb0H1Lk4E0474Ao7vV+HZO",
	"fiUpnWB9XB/QWa61nHfEGFMRxVhxJXX9LqQlEjuIGh275QC8yRu7leBPdCzDjEOpEmq2nj0j2xAtKoe+",
	"QjXSQl108oJsuGrjr8DiM00LT6ChasSMG8LNYzdUTHP8boe8WH/dQz+tK+Ov5GWXvIMAKAvnblIY0a6y",
	"L4bFb13y9vAD7p2L0Rb5dPqu8xqeQd6L4qBr08zIhHqXCR46NFM74AKOkouR3iI7xwfv4NQP3sE9FC3R",
	"Sp/YTXxKNVOmaFsAW5GXKBFl8COLyDmbOAPttFr+3//+X0g/C9V9aW1xLoySURbikIVBoSAuFoz2fLSu",
	"sstxMiacl26DogjPubBL7JJjL9SNWV8AWHGRZoaYSx5COqSdT1vxL6fsHmaf1xT5Rq4iYfNU+8wxSMac",
	"X+a7KIoe7APa5OBEmjktLYLXXrXAGcU1JJLDGeJlnDMPYvsRS1JpLDu2F+PtHB+2/5q3SQtK73R+ZpPA",
	"p6I6EDSyLxJ6bgnb0eHJqaXKatLRdMi6ZJsoljJX9xydbjkfhzM8ZxPnPXSHarmkKnlsXdYMiwi0P7TY",
	"mMVulID7lZkzMPdMtvrCJaTvbnbWn5M1srvZ2XjV6pKP0rCtPEQKLQb2iyKKPaRKcYhacV3ESJB7kX26",
	"xoCF1Le88T3hwMOP8QmhzARUxPpffcGwrQ1WdbOEBwtq07jwTUNHBm/asFKLwPQ3qIBJdiAqEGIHqCGC",
	"sQjd127dThzwqxFSdIrjwAA8qcgl5Qa74zhuZy/9hP+DkZgn3AA2fqBXPMkSstkjH95iZIdF7PVeu9fr",
	"ARJ0ySFIZP9gUR7oN5WZsv4cA1+YNmdGyrPY0rOzTLMzqiciPLMLuqSTlmtj0ReO7ru61VDcmI240K5U",
	"ea+7QeBL4r5E0w5SbgKjKz+Idvvy6qKLE7J7+xUdvhaR3bG/8XGJ8NDtIS+rGeUXh6j7otX1NbdfFVV2",
	"4VM7THuqIDeN8+vtCxxh0xNCxFjyRQ6AaeR5DboE41yQAPd09kUOdOBqpEbc9EWaqVTqnKi8dAGDX+SA",
	"7O9ikE0RI10ppG8HCX7aO+0LJzf4ShEWVTm7oHGJ4bi6w04CB2rtg3fsOBUmiyt5jfGFfRH8ufrxjxbX",
	"gqL5HIt8CePptKae679Z0ET/Yhed6vmUkXTYAmtCHTyXP+oUZCtk4NHv5CVVryczlejfz2zipDv0mt1M",
	"z55yLNeLD11yxFRHyUtsowORuyJv5Kb5FamyAN+EDSPk84103eOgTTSL0XjqO9L8GWf8MSB/t5Ja6RzJ",
	"kYwniVTpmIckAD018HwkAx3JEcJKe8mLjVKAc8INyARaS0XGLLZAjpDohisFDIN4d8GU5d7YaY5rnTHy",
	"L+svN3q+c5ZzC35tNxJ65ft693q9Xp37j12ZtVBfLDr3XJ6yIL2CTIVSX1mcQgEKPrWklpuxzIwVqLqW",
	"plYIKGyhpoh51XDSblx1EEPtxXdc8/O/NfCmKzk8bfew0l7XP6w0XvcPXXP06cdT9cD84xpLz+d7tevk",
	"aHoMHH5eEXCUyRJHJRylt3wRK4Jv9F496JKw2RiGgmMCu0xYhd+wqI0PfTg8cgUfE4Wx9jOCBjR740KD",
	"iCCH3qm45mPXkHnoNyTAYYPii4KXEcfKLNYxGo5LnM+bBO6yZvaq0Wfl8KuExlbDYRg7tWZR0QogbQL9",
	"bCEY3TMfJ5hnJSYRVPlNkDOkNlRpd0MESOZmqZw7g/Xny3V/hwNOI5bywAogd21UuRYOuLv0JucKxD1c",
	"QFJZhZ/W2Mu1y9FcMc+o4To3LYwz2/EvPQXhPJYgHHcldxeA4wHh8cfehAU0ehjPAfQ+Q278kd9nuM2U",
	"oPDAoTY5UNUk+rgWo08RNreLsHkqHlRfPGi38+qlK+tUwYQtVLm8FyiI2JBmsTmDzoNwG1N5nU3sTekD",
	"QFp1iZ5FYkJQcl/MZJneJBlzaamemQ18kyo9nojW09CFksKKVdjL1HJZ6I4nLv8cUTsLj35+sM7cA+09",
	"JP3/o8bn+Bba06E5dyNZ3G9Yjlv791+D/X4lrMoc3yiEZgUMe4qcufvImeLYH0vUTFihp9+yxopfyVMN",
	"9j9spZSyCN0XN5ah+6IqRF9HOu6L1cTjolTJtxWU84Ch6wvKw1hedrwPLZeW54l172J56YjefYp25Wnq",
	"7EHZIOZ6zCLsIum7nT7yqhwkrV32jBB3B7mX15bg5oLG8pTeJzvr47Gz2vu4OyMrQGmk6NB8B3bW0mLv",
	"OI95sZ0Vjvw+jax2gm9kYUVwmgWVd/lZ/5NYWLsPb/Iq4LkGnOeT6xXtXTnULjN2la66XEK6+72YrxYe",
	"Y3uhnHPfAs4SzPrDNhAs3cmjkH1K1qs6M889Evhigm9k4FkBDB+7gedbGmrc8a0kXi210SywzuQ2y76o",
	"s84APi0yzXwLU8V+bjJAW0JurCjvdMou0XJV35A7R3w4hFBAbxWGAOoI65N2H163vg1HXnO634Pk4SyV",
	"XJ3+fI+UrTTDN5Rd3Srmx0gVhgSvjDt5FuLaXa0kLKP0qIngrTB1GWVyCVKOYTN7Irklo3vXdAUsPzTm",
	"EXw8/+Z2YTUjRdMxZAg6J3/TrYzkpTUv8sGgBBTV+gGleQdfVZkHk3gKk6oHPQtyHtQIN9rD3w2ojZJx",
	"PKDh+eMgN8duNfdIb8pTfENZajnBgdQkf+OKdR6etjwI4B8XOyPUJWSlM8QWclYq5ekg+/IGAK95AqXd",
	"HgfAn7jV3CPAl6f4RgBfXcICs4s9u4QL9Ny7mwJ6rGj4gAVVHw+XspTelSUeMH8iDxmMXbkSCILzi7it",
	"nAt3utxpcIqvzaj53J4aRN832g1BE6tVQf5ho11JzwFnW2Nrowc5PjzJEkjxaTfspvCvXCuDLFloaf75",
	"TguOFltdyTYPW15aZtQNukqdUTzDPC/cXgJkIzNtyJArbR6xkQ5M9gUpWFOZgJawptgTrdnRo/WSIfA7",
	"WfORcCFHoNhD2DJXIYbFOz43uwkHhhXe0MYB2XwaywzwOCaUbPR6rUcMyP6QqyI+UPwbUE/vh19KP3/1",
	"L37jEsq5k/7OqifPqOT6+yJqM1KuxrDHIWLhoyNfRZ43ZpNXA0Dmd6opUtEdMsMuU6qNz/L6IgdzM9Dt",
	"CK44xHQyejCd3FaKC80rIxwdnpx2yX5epIEDzaBET0Q4VlLITHuLqMt78z1rhCv2j9/60gHuFLB0gE8Z",
	"959UG+xY3mSPO2ZmTqW1n5jB9f9FDu6T8BaT1Npf80u4rifp++l0w8ubBL5Tk0l4ryiW38FiLIOwsMVk",
	"/Rd85SmY5rEE08CF3F00DYLA4w+k+buHQ49IDjDvM4gGj/o+o2gqhQ4e2BXhAGkWSOCHpyTFR5Ok+LAR",
	"Pn93QD+DZws4yIrhPQU+LYvvQRD850hlm3vg8+OA5hxk76Fowx81CAiuYib65y44zV2H/9wnayrN8I1s",
	"+EvA7ym76+6DhvyRP5bcrr+XCM23zOzCdTzldT3VQK6GXV1PTFLMwjac3vJspuPi5fvk8eVpai6/9POj",
	"T2EqHe8M9z5GH85jMGrOQMEaFh1+HI4ZrEr96ICvVJhZKlIqEStkR6a5n9ER8E7+9iUXgqkbOmkeVHst",
	"bxYakvruP3I4hL5/zVhqA92oYXNrFp5lZoii4UMmgSCAQKlnt7Ay3jUN06YTycwygzXvRZWKaD4SNG7V",
	"ouSKaOIM24/Eg7njVvP4UMWfU0Sa2HAykRcMmky6Hs0XnFZamlvGrr9LHCma9nqELxohP4zBxJ11gZcP",
	"iBCKgXD+OOIoYS2PDxnwjG6aFPaoOED3ASMk7aE9AI2XmWEdX4p9oQfq2L567N98WEdUXeCX9t3qi8tn",
	"IkvsplPmQ6NdC61Gu3FJucF/5dS50W5gwQb7kIqQxfbfn2cLLM9ZQVFOoVjC9Kffo2urfNN35+HCQF4P",
	"ao/f01VdL3bEhs5rNAQk1CkXrDU3Au1O9J0ljrHKRd2nf6wKEQ/rH5ude4pol+8pz9BpcqFTS0KRTKxZ",
	"RM8UeptyZcU3xpOZCWXCWo8aKHcVv2B5QLzfrxkrmY3QfjdVQaRJo4SLNcsryvHzN+YOyw0m0+B4X8LH",
	"dSDi8RtNKvf5mM0ms9BQEYlXlh6Oyx99wxDFihB7ZyGK5d1VKE1+yW0i48hetjPGfh+hi64VTLG3adAd",
	"MWFv3RJfbR8JKO4I8qtufT8gDUHmq5I5DNu/R1rn8gJqwKwcE//IiRyATnm9ldwulXOMRwgh+pzHlY4C",
	"9TGvlKQzAi9+Cj2N8l45/cZ2FOEv/Qb0pY/kpSBSYANzEjFDeQwtA9d38np3Uo3+pPErHD3TDJoIa6n8",
	"xNBXkPhYPDc5YVcQogfzu7wYVxH1h1ZdcKrF9BPc8lOo4WPRx+BC7k4Rc3D56BUw7eHQkwUHmPepUeFR",
	"36cqVWm09MCqlAOkmpL4QFqeQg3/OUMNtQP6GTxbwBFXDDUs8GlZqCGC4D9HqOHcA58fajjnIHsPRRv+",
	"qKGGKFRNa913wWnut04+rLu2Sv7SUvit+UXr75P9lWb4ViUJFoP4Uzjj3Ycz+iN/LOGMukTMvmU4I67j",
	"KZzxKZyxGs54PVEM6yEstct/OyPV6XdgnKLOJPVILO+wersbnGqKUdGEdTDNmTQVs4hzwciAatZqtBuZ",
	"ihtbjTWYtfrdgQxpTCJ2wWKZJgyKKOHbY2PSrbW12L4wltpsve697oEw4s5heqj3jMZm3CaWsAEat4lO",
	"WdiGsjWRDItcaGzBru3JplRjVndwqEY7FuSuTEASHkUxu6SKuY+nWnIzEvxr51CNOvtR4JsqN3c766/a",
	"ZLezsW7/98Wmk2acS35fDBXNO9fWnASa2XyL0Z3jT7tOLFpvE/jv81aXINZBS32WDFgUschSVWecy8Hv",
	"DZpU8r/hg2FMDdrvtltdsh3H5FJxK7V5rNTVHRaCGxTCXFl8cxuG/ei5G8XwMqOo0Bwnb56cbp/udXrr",
	"uevQPfjBpeEjYc0T2lUpq3+YFWKSG1oK3zwZ2NuFtFyPDGUcy8tOlpKf9k67mIYPNsvjvZPTPHO++b83",
	"NbrUL2jcekPSTI/zjphwmHU0ubr1E7uKmu07i8bsPW+0VrXI0rJFFio+TnxKeXGZlRU5aj27GpfKObua",
	"F60uwZB1MpZxVA4w0MSFrKCx3K2nS3xvJejq3cbqadxMEAG3d34jlmopOD4rFfFRpizXqyzURcnPLjRv",
	"jTm71M1WPrcF4VQxbc8nliNuiUsokyQTjn+QhEWckuaF5CFr2zs1bcISyuMWibk4d/zaW6Rd8nN5hXlj",
	"khrIxk7jRLER10ZNyot82SrqPlD/nrxEaPKbck2viRTxxBeAONn9GVpf28O3QhNhVyzMsH3OMaNxPlr+",
	"HEtKxNQ+THjMtJGiespuoXV7gLboloZqKcrrf9XqkvJvuHCpRp3yXWI1HEoCJVGkCSzZ8V1s9vVx/jiS",
	"CeXC9c3HLpUaK1Y4OrDeq9KTUr/22nWX+jQDWMYxeTnTsdkV9ihIjGun3SUYu6yxn6ZUZOfk1y75lGqm",
	"jCbnbIJ4GTRRwmkTsNgVjX8ywS29tLqwZqozpKGFpJAKKQAI8x49ymKSklEW4ogoO/dedNeJFyLXW2+m",
	"bH9ck6InONbhlLBxO7IwbIQ430lomgJeAsWWgrALpiYkwGoPz5xOGOQzvWqRQWbs8B8PT3EfsGO74aJ9",
	"J7Sg2+i9sgOmTuN3pLVLdmia2kUZstkjH96SNbLea/d6PdfHHiG+ygmxwMXXz1///wAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
