// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3rchu3muCrYDk7NWKKpCj5GrlSZ2VJTpQjW44k58w5YUoNdoMk7G6gA6ApMSlP7a95gKl9h32PfZR5",
	"ki18H9A3dpOULMlOTqpm6sRUNxr48N2vv3VCmaRSMGF0Z++3TkoVTZhhCv51kCkt1Q8ZUwv7z4jpUPHU",
	"cCk6e53TlP6SMZLSKRfU/kZCeJwoZjIlWESoJoFg1+YS/xCQiZIJMTNGUsXmXGaaxFwbophOpdBsQE4T",
	"boiRZMJMOIMnJ1xpYz/CBiPR6XW4/fQvsKNeR9CEdfY6uHyn19HhjCXUbtUsUvsXbRQX087Hj73OkTDc",
	"LI6jt9TMlg+DfyXv3h0fzp+RVPGEqgX5wBYD8jrThowZoWROYx65Z17g/z4mUpFYXjF/bE2+u7h4Sx4P",
	"hyTgAt645FFQ2nxqN5DvnUedXkexXzKuWNTZMypj5XP8T8Umnb3Ov2wX17SNf9XbuJHS4S4WKWu5rIsZ",
	"IyE1NJZTwvCsFkRkzLiYEp6kUhkWDVoAjG/ceqPHsHyxR9gy/vi9HLddCT5A3suxv5YcscYLwI23p+cX",
	"ZNsdaxsPQZiIUsmFGbTAG566vBuwH4swziJ2yDUdxyxqgf3fZkyQwH4i6BGOr5DIvYO3wZkmWwET8NM3",
	"ExprFnQJF1X60ANyyCY0iw0J8BmydbB/0R9+3W0nDvfBS//BCplEuFxnD5brebIZSxkzKuCMJzzhpuVk",
	"r+k1T7KEiCwZM0XkhHDDEm0pGO+KpEwh8fqdwx93hwPi390ZDts3H9uPN+94d9jrJLhGZ29naP/FhftX",
	"fhAuDJsyBQd5QxN2zqgKZy2nOaCa9bnQTGhu+JwRnY2RgRAN7xEpAO8Cu7uATDiLI7J1fHL81yMS/Otf",
	"/jXoDsiZ4wL5tV7NpGbEvkFCKQzlQsMicxpnjFCxuJoxxciWkMayxQm/7ksRL8h//+//Q05/6D9+aa9f",
	"xpndZHdA9qOIBOn00qhpEhAuInZNJlJZQE+kSqgIGaGGxFRNmcpJXvNfmW4HM/zPavZ5qqZthHqqplTw",
	"X1EGIHUMyFvFNBPG4jAwfGpmsM+zo/MLollCheGhHpCLGRsJmpmZVNxQAHsg1dTyTJJpFsFLhy+JDmUK",
	"rEoTGl/RhSaK0SiXKCMR/Hv/VE37x1FAZoxGTHkuEZyq6YEUhl2bgCQ8imJ2RRUDAJsZ17i3XPCNBNfE",
	"Xkb+9YgaSmgYMq3J1qvTd28O+8PnJGb0A50yMs2oivYIJTOpDY8ZCWPOhBmJkAq7TKTsmUIlte5LNSVj",
	"NqNzLmF7LOLGHspu893ZCRmzkGaawb9DGbGREGwOooVGmgS/IWA+lgUpNbNuq3DB5++C053DTz8ypbkU",
	"bfRz/iPBV8kcHwTwOb4MohBxZOv49dv+8DlQC+6LXAGPhGsSpm+FxB6xN7Yd6nkwIK+5TqgJZyzKl14S",
	"t1fczIjOUhRl/jlUMVg0IEfXNEljtkeC+XCwE7RTA57h0i2wki4+WtA65mz//pJG9khMG/uvEI9j/5Om",
	"acxDOP72e23B9VuH4YbgP5WSCvgVagxjGaG4pfBsJ6GxpW4WXcLLeKFMgxzb6wx3vh7ujHfD/rPJI9p/",
	"Rsdh/3n0mPWfTJ7SZ+Pn4dfRkHU+bnrrR3YvZ+5UeMaaYMZNErcHYjfbIwnX2uKyRzVkj7qHekbiLrBH",
	"8qOQ40Pds+qTOzRZouBBB2SsYUrQ+JypOVNHCKjbwRYXKsM1E+w6ZaFh0SU+9nkh+y7fDtFwXAK7cnAA",
	"KFk+fPhpyFXiCh698O4uEex3eKDXuHDp1uHGhRR9p9M1X/obaV7JTES3O6iQ5nICr5fOKOSlzsLZJZ3a",
	"xT7vPZ8xLTMVMpAzsFMASyEkUiXHrE3YgOSiJJRKsdCQ40MrZCmJ+GTClJW5dgXPHh8PH/fgM4+Hj0BQ",
	"fOx1HItyCrmUJ1ZZuFuG5aFrpLwEXeQy0+yS6oUIL62MuqKLz34HBfci7DpkLELF7MmQvH5JtsmT4ZAo",
	"eeXlF6iiTnQ96w7IOyen58PBLoGDEXcwkHpOAcOXQfX6mO8dRMV+RFPD1LIY3ReE4t+IYlOujVrYfVjV",
	"D361mk+aa1eGTRVKVbB6NNlig+mAUPJKMXb+t+OLg+/IWPFoynqEkhM+Z3/lhkypYVd00R2QY2FPsIOa",
	"kFWucp3Rnj3XRIUk54d/BQ1W0dBYlCLsmoWgllo5TuN81/nvJKYi0oidMbV/SnjMtJHCGfOpkilTVk0G",
	"lMP3L1HILpmDkVWpJ5wpgK8Fvf/gBy4id+5RZ6IY01fchLNRp0dGnZjP2Qdu8B/misdcjjrdAcAHVAyn",
	"CDKSxtRYJkUiyVAFVMxK+tCgsg4nscDCzefUUPpkp1dXEXqWqCZ8ige0+p4UNH5bOjhqZNXD2s31YS/f",
	"n5++eUlwjczd9DiW4wE5n9GUwZUhGPr2y32dspBPeDggbySZMxFJlf9GJvyaRSSUcZYIDee26uXCzKzg",
	"nko8IWACCO/aOX/rWBXXno2nA/frIJSJvUipTGfvyfDp8GMOATl+z0IDEFCMWhFLTYWLdHaHu0/7wyf9",
	"nScXw+Ee/N8/Or0O2DH2OxE1rG842CZWBT4V8cLDawnMzniufKHyaG7U9jo82lT19UphHRsPuU5jukC7",
	"DvGxuInqdQ0quFIiy5dAlqRPDg92mhDHyemNd5ql0X2D+WPZlPgJnVe5OuGsyAoZF/dSQYPKZn9uQJn9",
	"qZNDy7xxWjIrHa8aEHheE2vX2d9nWUKFJlvWzJJGd60VTmZURDEjSmZWwQJ1kIZ2YT0gRzScuaXHLJZi",
	"Cn4Kdk1DEy+IFMwK1Sam9TC4nVAeN0AD9gt/JDSKFNO6imw05iH7X1VSzXeAi66mpOr3zuXE9CMWM8PI",
	"JKbTQe6GShh1bg13PbpwcFERkSsex8BRaZoyalV+4hw5NQ9X4dACARv8pe6++gb8aPZydKYmNCx50uDT",
	"usa02lgAu0ZrwFFY3RMUx0z1qdZ8KqwybuwXCK+KICvzvdcRpc93Z0QvtGEJYUkaywVj5PjQHkXwXzIG",
	"FqpDXItNJHj35viHd0cWTS0J9UhpU92gLmWOrOYxfLzbdGV3zNDkpLjLKkbtW4wib6bZgom74Fn6A49j",
	"3YBq8DvJb8BIx2EBvcDUT5Wc8JAzES6I5bRiauk4GbMoYhGRFsOMpYxvjy5K+GU1mhdEJtxYJgB+lCYM",
	"3Bniz+jPtGxlElPTI6c/9Hf2u1a4grcOlDApCHKB7Zq3Fj0MdoV1AAFKhjPvw4kTy/0+tnIGqhRdPBDL",
	"73W8I2TZ/SuFNFLwkMbxgnBhoQA+AJkannBteNiPZfgh99mEMrNc1xH5824RXHFkbtkyCd7uXxx8F3j/",
	"gn6Rew/qTp+vazTS7Phtl1hlJpDLL88XC8FVeIJuLMJOuDbHhiXLwHsVU+PQWbFQqqgIbzT4/T09KAaC",
	"S6AaaUWTw+QtwMySrxjVO0sOBIkMlfmCLvLVu59frt2hyLop578/Bnt/XPOhyf4LJrA601xWkhD9K6KE",
	"irIgoQ2iZLBEEM1iEz6PQtPSW87GpAC5Uye1Xk6vUpArxQ0jYxlxVtPbXvI4tnz0HL3Zm9xW6QhtimL5",
	"lNLZeQCbATnG20R5uEO2xmzKhWCqa6G1MyRb7NqCojsgR2IiVZg7KPuaR8zx80fdFy74QfRMZnFEaKyl",
	"/e8rknDxzc52Qq+/2RnaNVPF5iA7x5gHYKUF/cDq2tvzSoxvdYjPKRM3IKQa6uavV6HZjnqGGtYcap9k",
	"FuMA6to+5Vn81vnF/sVRf7iTRwqLaLZ9MNMEhJ+9H51hyMni61zyiFAykXEsr/pZCshlWf6jg0p4sMmr",
	"YndxI+4yVox+uERXnnuRxvHppLP302ZL/NxrAAmsSnDV3IMTZgo8li/hjwgqD6PHoGaJvrCwBNmFQSIH",
	"p2++wbeCAXljn+CCUPugmTGFKzlksu9bRrPCczClUxZdhjMqBIs3P+8BvoApDY2HdktiDKRiHrmTxwvi",
	"Pm+v3B/9ydqjH+FLn374m4qeVGpzWbKdL7Wngs1g9lZqc1y8jjTUDDxD1ZR5AqITqzj+TdH0XUrYdcqV",
	"VdUdvJ52B+ScGXI14zHzsHGgAchZ05ML/xci85Vg8Q1BBc9e3lwbXtJ+3a6fg/s1VMwKLkQAcMe5EyeZ",
	"Qf8ReXdMMmuZAMc20koVFgJgYkZSibKiZnbkLPRRI6cERNrMKsFHH0rruFI0zdLLTJgmjwcGAfvyyvLN",
	"i4uTnJGUrzMH8LPugPwNr/9qq0tSqgso8oRpQ5O0B6+PafhhqmQmIjKVSmaGC0g9Y7q8+n//53+RoJkA",
	"AmIUhbwRe2GrabIVck9WQW4NetZkWc71S8qYu/Q6Im+oZ+UY06Ra0DnlMR3zmJuFF2TOZ14SeSMxEl99",
	"BW/0jZxOY2YPtPfVVyPRJ8EZo9EiwOAWLhczzCQKGZ+zisMOXngjTemdTBRvbQlJdDbuo7TRL1zcQjuF",
	"D+RGF9ZAEYIhAJakUlG1KJbC8zglMXfq2i/gynigc3D59DUz/iieO8O6BacHB6SlVSrKpyFb6DTqc8EN",
	"p8gK4gVuEFEPV7Ko1y+/CEyxD2lFoSFXUn0gKVNcRstL4mqnk0nMBXNQ9rIollPgipmxnNHiG/6jaRHQ",
	"260G9lMHgN+BYK3/TwBnp9dxAOj0Orj/Tq/jPl3CsILo4bUzFztcVuAbIF+o8CEVhAFftZRaUiScU9c9",
	"P6OaUBJY2rbLBODAJGZGDbBTlXAByVoMyLUiqlnMp9x+2jIbZA5TJ2qkQL0G8phIcKzP8vUjmVAuyIzF",
	"KVMknLHwg+M9jiJ2hp/P8I7Q23cpVdQUgjyXylhsA3bmfe0VBS7l4QemBuQEUl8dqTvnLqTsrvfMfK6Q",
	"TUzHLAarRPiEPrzqiOkPRqZVU+wkE81hvZsqTh7zGvNDAelylPbGWQXiLYg4cJmlIJwKitDG2qVNrDMP",
	"lJ7P7C3DNyAg6n35xUJcV7mqexFAgvHUC0W54GJqF6heeEtC6e/Id+G8Ffm91anm0x0YL7P4A2Y5v6I8",
	"ZtGZvGpifxP4I+YiCELJOIs/+KyEMbhFMSvBGkwXEFvgUy5oDG+4lA57l29OLwgLZ5JFZCtiE6YUekMg",
	"g8GusLOD+Ubk4PxHEskrEUsa+UTU3f1qIuqZvHJ5v+iW3OmPqWbRC/jqjv1ekb4PGZT2d9TiIUKHOZpc",
	"2I9B9kvxOLi3wfUOmP79+embJk7JfC5YDWCYHhq4TG+EXuBo5qofszmL8ZyabB32Hz3tDkpCrfJWo7CC",
	"0HiL2Q8ZweANAskC2ZwRnozyOFOsR/gEH8ONVJmN94ytNUVUi6z8LkuosGpPBBTLrtOYuuIMF9Nx+6h+",
	"12fgYSjRkVzTZ5sQ1F083G+RCO6/Zf8Avo/BGqOkRov2U71OkZQH511NRGdMQ2b4ElAuLt6S3eEzkmSx",
	"4X2nnkLej0WKMjkhIT3pkcP+o2eosFqqsSoGEAYTcxbLFJ19mqVUWXvDyNShFbJ9pw3g8X/6OcAo0kj4",
	"1N7aWhoTOVx6Yoy7CqXQXBsmwkWPjDODSc7Fl7y5ZwmNG02sNHNft7t2Zx6i+WvtECWvNPqULP0L6fcX",
	"WO1Jcaa7A5JDCt8Si5GA1+yTZP/NIWSWM6tHS8Hgwt2C2r37eHcX390/OSH5qyNhv1feAIsadR9Hdcv6",
	"iFFZaDLLrxzhWhAxq94VzHFAjpLULJpPPNg0EtfEkz8uB97ycyxv1iU2Hh9qSwfOizfJ7MU64bDt5IKj",
	"DL3x5gptorqfuiMz31yvs8TICso5KPxdSxq381vV0yzcK+UUNGrNBx7SmIQySTLhkgZJwiKeJWRrLnnI",
	"enZF00MGg2JqQWIuPoB3M88F+CVjGWo3mWhK02hSl3FHedLYxv66B0pLcke7hKPdjTf1cAlaFf2OKsXn",
	"EIV1aqS/TOcJI5NYXmEWDDginXGVO8wwl0PI6q1s7Eu9g0DcwXf7b/o/nh4fHPVf7x+/uft43Gtrmf1o",
	"EdNj9B8h/6ox2Fahj9tmY5UJZ5k55yUXZW93kSxZUq6AF+CmTB4IbNKxDmBzLuG1VFGxOmH0c2dkAvkY",
	"aUXknBFmpdGgnWgK8FYSrlx5WxvRLCPzxhmFNeRpStdrvHy8C2sRlm5iRTI1qC/2JefqytOIaur750tq",
	"q8C4XtzCDacxcc97V1K5ehEN7kHn7tPKinyYrDFjbON8sPU5XjdL62pL0/LQKofYE8jCy0u5kc+gE1VI",
	"l4sy+NTEqJX6z4qsg3YEL/kgWxnOkttsY//WLei61fNU9iSt87c003yrT6MdPE4EtILmE/SwO1GRbqKZ",
	"rL2MT9FMbqdtbILBFRC339QPFoztMjO8utQsrOzw6bAJe8ufg1c3Itja3SZcHONrO8tG1J1cyQ/vjt4d",
	"9V8en5wcv/l2swvx6TUAqU5jMg2XiptF5bUna30Wa29Nd0pr9/K7aL/L85BOJjKOWq/zU+XNu/Vy5vxg",
	"/9Wr05PD/nC4sxl8L6wqcAa27W0wfQU4rCBo587lw5f38x0m/o/dtXNhP8+ZhtT0lC4S8P5znWYGM7Ee",
	"hpmc//X45OR2mFskhjWL6gaVWLe9sgkSlxZtuh0otjuQUYPOcRBLDV0usoTICUloOOOClVyU4AsLZcRy",
	"byw5gCQyTcaKCui6MBJgyGLLBChHg7J4KUiAnsGASIUeKOfdo3FeZJZ7dqulikVzFnvMUsVoqU7YufUv",
	"rbIf89CA2SS1vpRqWloit8D8D0UugP2x4lHudRQ17BKqCVsczNXSxQaqFphlUvcjWvA96RatF/J8ksfX",
	"19tPrq+LPjsjERSllwHhupyWOF6kVGt0EGj0Y6tMkDGbSFdd4yjw+HAkSv0UMDxU5NHnPQqK/gvl9gvc",
	"aBZPrLFgV4Ey4e2iNtxXBXdXOv7XFoACTm7uLw9xmxmNfeYm9H9g42w6hVibx8zX784vIJ6SoyipYSiH",
	"kIvOgEZAD55RMWWEAgKRhAup8h4F9byQWj12YwCgqJy9VbLjBp717xiNzawdEU/4nAmmNQa3C4/01mF/",
	"51l32eArko48SdKYz4GjVKy7OVvLpNxSTbteajb0Cb2Q8n1CZVEnt4N6HdBVdSHedWFJ2/8sp1DqRiLP",
	"2x81uV9Tixca3J9FEySfQgohCmCT6MHx+aO1/kcvCLS1ALyec0qCb48uyPZ8Z1uqqd72rURc/ZLe/o1H",
	"H4PPVwgA17CR8bDcTMqFifSmcYMiZKBfEE0TH4GhmtSDSQN89lOjBy36RK4I41cu7Y4qQG7M3buJS/LG",
	"5Vg+crC8l6+fNW3GSEPj5YehH9PNKgVKGFBZdmlTVXBVHJmN/ABl8kUukteIV19aVPCzSalHCXCCPqYZ",
	"FlK+yHJ7VIQOj64NE66nQNgms8EtElhRGYA2GhgZ+IL0kXBc3ruhSEq5QonsehQ5nZ3GsbxiUWlHJKFG",
	"8euV0rOuGJW0lsa4t5LJDTNGC7Fb8A2ranFx6bZ8ifu8GxFn8eZGO1wtE92RYdUmzHqLnQ9ZdMKbfKIH",
	"MknypoguRl5qlliobVhvCBUBkC7gVAQaxyOh+XVdVkFpmOfyGnk7uEsCl6ko3JN53f9IBMC9AuIwYUHk",
	"nCnFIwbB4gvMxNcWz61RRCS2drR7fvq4z4RVzyMC0NTcQH1o8FtBdz3ihMeBW8Rp0JgYAo3NqDI+KyDN",
	"xjEP81YSmCNZ0qtGwtiVrQZFy7tBzBiQQ+mX1Iy4SDnweX8GzEZrQv0Z1ZeJVA1U75KoIERmoCGb3bp9",
	"1vIB8PyO2UKKyLcMmzJQtCdMkcAvGwBYUR2yqkS5+SX5H98QKwYwESWMqeJmgXtsSHbzsqZBcXEVE3YH",
	"FqJud2UJ1RCuLm2ktZEn3rYHok+stm+64wa4fwcjbBdiH4mp79BJ3lrLgWoS/AWX+WaUDYePQrgR+E8L",
	"I1Es7Gi8rv+yxffvw+THWfTtjx/+fffV8Pi95K/f7y/e8OHVm/Ph9Zsff7h6fSjx/19JfnLwffqPg+On",
	"x+/3r08v9q///v779ycXUfJ698i82X3F/74YPv7H4Vl8cvFj8iY5evT397P3p3/74eof599/fePUagRz",
	"r0CmZt5gwlmJ12weOVknYXZ7pJA1vlSmNxKl0pFzLqZx+W1owxjSOMaaof1azRBkZTsRgp8vMpFLW/jq",
	"q2IT3b16CvZ//pdP4a5kc9uf86eW/uLSr7ccfDUJasVHQTVNu/aR8s/Vj+Rp07U3Kr+XXinlcUO9Te3Y",
	"rpff2AKVT6fMapSW8QIZeF7sYFI+X54IXjphrdzInbBIGbfvuW22HYVst52EbNltXVycFHUMuP5X8KDP",
	"/+7lqeDwc+n1WE652I7lVGaGQI2e7lrw7JfRqUH1QDm+VKANImkkgtVaWNCkPy1x77uvS6u1HzSyqCqr",
	"lKFBVA6YPYP+mlU0DVzLEOjkKLGWD7ooqKk10vLGj+Vs3uND7Vuk5olT0AKUktwXlTcmcoI/oQvCrrm2",
	"8tb8mybv7a4y3zzzV9etElBSqml3w4yNByroek0Xlnx0XqXVUMxWredC5cVV4FRqweC2qqVgA3I8FVKh",
	"BwtLbkokvCEoPk17bNMSm+DTKNodz8/z0cvc38hS7qw7uiv1ACOjXgnnfAKuyrlaFrefpjEv1Z1ix5Im",
	"oFb8p8rVeFj8xP9ushIwptLg08BspXpCGTyuyUzG1VQvckVda1QJvbcbireLl+nc0mQ5+6RHfJilB2YV",
	"bayV2do/+FsX6l1UY+VsESqrHaZ5KbLt4OfWtIfVLJQi0q4OrVb3Y2+uV7onKGPR/hJyYk6oWOQLVTWl",
	"DSN3NcOkkqYDn8DLoWHI0ryF3E8jzNfBTP9wRs2o83N3Y1fITQKBX1yDsNtHGz8tMW1tZPLG5bqlSGYV",
	"C+ATOZkMyHd8OitKebiIeGjZ0Qx/Lp57pwvW4YuhmBV+UKyHQg4aX9NE2j/9ktE4XvTBc9rWpOlJExb/",
	"vptcbBD2/fQCEqu0ccG0PrAmZ5P/E0SsnCDnificRxmNoZ80L1z3ZVe3/NCxonuqaNQSnso/2u5DO2Qs",
	"rX9kfXwAa+Qa4rrjdfhegwOwG9cWs2G91gruA2dbUycg80WKftY+puV6RBefIRBbH9ysG5HfSdPdKhZx",
	"fdOD19aPxh2/UAUkTd9bjs4soUJBg/CnjUI0PX+tTd/06Q1N+pCSV316RRdEu4e8Ggw+Mi7I2xnVjOxg",
	"NxE5R80JGm+ARg3mThF5dP88fAn/pX+JQ6swcDEgh9DQrrTko88XBmlNFViTg/FpUmdlvsZNZc4tWOVq",
	"Bz4kfbT39alrlKVOWRWtERtE3qDhzwOVB1RyVuqOOcxNJta6xOTj0gPVLJ22HJeetVszUDTvItvl9prT",
	"2myXu9GcVmTG3Ko3YUs34gNq2FSqBZHKV3o79zZipa+VNSycQeDHNSOmYprRqdOpUyWjLDS3bUdc95rq",
	"9qP/vnWp0kV8us7k7reBn7jCra2zVwfk6ydPd8n/+79PBs/QmOtDfiyLfGJ2KYduJNxYDJK45O1nFitQ",
	"cc7HRFniwzlRFGIK76HNP4QJ/ViKTRqgB7U736hpeulCs4w38vh3ALSbFlw8eGVFGDOqblpT0Z5svazB",
	"LKMLAuZm1Q+AgpXqB+JGRZHAYW1phgvET8pdSmGNooemhQiGfcJF0TqzKbJ7D+0UN8lUv231wKssjvuK",
	"pTENoQfSUhmBqwTfevuuNDPIB5DeSyv6Ib/Flajv1EvUcWmdO1EVOiCpkQm2aSrKFLBmx3XKzARma0V3",
	"0MK17utYa320NE8thuCABpt3QL07iwNR/VZ1ECtrHzamv2ppw/JrraA7/bwg+yPVRtwBs9y4AOEz1xzc",
	"AC/LbrTlXX+peHmjdPm7QZL7TVX/EkHtlL8DlyJ+q+yyFlnv217nbfGf3yq7zKWM5Hll5datI+HSSqn2",
	"BkwiQfS6f/nUd+xp4TsRFmsabPA6EjiAaDthasoInUykimAYocaIaKYhBUEQzRi5guYoZRFbY5i4eksG",
	"jLTXZirH8L4hfxiDQUNe9LIvzoGj7EjEUgCgFORqxsOZX+KKapcJ7Ls0YK8PRlKm+vl33O05FuQGKy2l",
	"1i0VEPy8splLQQL+RY8CD5ED3svhvoznllpZmFkeCPDDezpV0+8wRb2tC4azkxZ+yqEszYosjf+T2LEj",
	"2J7vbAdFcttgJPIZWF1sqlLMQISxjZpNEz9wwt49TpD0iF6UG1g8p45cXOshdh3GmeZzFi9elEltzMwV",
	"YwLXt2abex6N7pFw4yd9M5fyXwfksADCXuOGS3MmE445yaVVlidk+t4vpGVGJtRPRNTQMQV0bJ+SWUxa",
	"s7TMte/BrEeiGDwGnZr8tDHspFIbbAlDK3U+sjK/n5HIR4RWx5WVx1PmBQ1u1KLfUoHeNOV/ZQsc2MXF",
	"RPqxZDQ0RRfuzmnKBDnD6JM1+VVsFzcm1Xvb21NuZtnYGjvbcSbFNGLzbZky0Xfhqs7yLDAL8oQKOkU7",
	"ZP/tMVxF+TPYMlFgS30oF+m5hkI+8OyWHwnvuRmQ/TjO0zcPzt4d9ipNoUsB/l65DRG46kaCi4mi2qew",
	"l1I+qWIkYhMumEVOhUmc//Iv5DVs51RNybGWMdCY/csRFAH510kmLKYFy6UAUAg0LZcUlEenlmt9XKJf",
	"naD/TXsfinPKlob7+WGRbsgfJp1WKaJMK4ieUMbUThP1wbFYfVPgvqEfWClm42jMY+yjHnH/9aTrIQjS",
	"mxxVKqpA5j7FJKjYi9iizMnyAVoSwd+fn77BgoI9+0oQBO+hU+hvZIQMd9TZI6MOJkbmRUqYHIluQddb",
	"tPQYFiNVn/G8v/xclvFo/sw/Rz7C532GbwBf92OLcdRbqThvy4q4IN9Q4ERb143orRSM5UuAn5Kpvr9d",
	"d/0JF2UsyuvFKkj0wtVI3aj0rISD7srsJ8mBFHMcigHRxa/tne0O8zs7PtRkqzTUXfdyBtqz+MX4VMDv",
	"XaAtd4rciTcYiZVePKdn5ZNot0l18jvs822R+u0zvu1fTqrZ3BabWjLGUQNryNMeiRsmaiP1Lo/mH4nK",
	"bP5cyVlO6DXyAxM+obcyr7/IF3bnPk9Z6LVxREWuibY/Ig8eO/8MTCE8cLwShn+6PlL5yEBiZYt2/Atn",
	"PvsAYkAMneKUqbG9l0TOKxE9FGWK0biaTc+ZhiGFKKJiHjKntTs5s5/ScMbI7mC4JGWurq4GFP48kGq6",
	"7d7V2yfHB0dvzo/6u4PhYGaSGHxA3MR1sWWFTMmJvdcZDnYGQ4hTpEzQlHf2Oo8GQ/iy5ZOgcG1HMoT/",
	"mLJGPyQmX1KQLzwk3128PsFMcaClWHoV6DykMVUg587ytMY5Z9DMlVNycPjGEtLjJ66lpPsTXLNV/7fd",
	"HgcLmsQlV6bLe+RTLgbkLSb6uz5AZEubbAxqTPeFFzNsxkVEaJRwQZSMIT9svjMgLxeuWXfb8O6tw/7u",
	"DszLEhFyGtwt3KM1JQB5jqPOXudbZg4t1GqjmneHw9rIU5g3DVe299vqmc/1JigupWvOSCTDzKoQiLs5",
	"/AcVDbqz99PPvY7OEsuPagvYK6ksYlUjOtVWXz+uKASdn+2a2zOo0vx1LVJUOwIWZiBJlYQ5EyA3+dwq",
	"sT7ghIkbkbwS2ihGE2c0MRFypt2Etm3IBfw1cKWyLCW4I9fyeLO73HkGHHun7QK/c4dce4dNY2s3Gxhb",
	"q3ZtuGdsPl/AaeWd5sWxMMp33SWWyWntTYI32885syzF4syjwQ5y1fHClIuvVSaE5TZjLqzw80TtmqT6",
	"AYeADvZtaPSMj1pD2MKJY9oW5UIbPwsWRw9MrFWguP5w5wTrTmVlx83u3APwBuRbhuDf91+fACBWX65/",
	"ReP+Vl4tkkfrpTalSg3IWw4TKGeMvJXaTBXTJJUy7pEU/nDGIu4C+oVZ6yuDgqXcpKDwhlW4wZPho7zT",
	"p6P1CeXxHdHsGR78Hkl2OROt4Xqt/ocpzmgML2DA+JPho4fdximMEMWKspyLLnxfeF9mvArp8s9sxlKW",
	"zLtLXcq2Wq0/WJD5rCvXo7QYupyZmdWdQhxUoKaDPBNLinjRhAxWx/Wamv5UhNgoIpAnli23Clu6GdDA",
	"5WTpxIAnj3F3Td/KT7FdGc0PyLXRS5jpgFIF7K769VccbD/9/LEmYLRZ2nMJKXIQ/PzRKpDOxtatcaPi",
	"ke3ckQPRo1Q2xbz9nZey85x/AVRNyMjTd5eSt06BB4YE7vHHT53O2up528y54LaG/DV3t5WchoWMhdsH",
	"cgjNtfNCaCzCqPDPrbK/YYlKqh2fiun4L2W0uDNe1dxW6mPVM2xUxj4ukenOnW2ioM4GJauK0b5l8ubE",
	"+JIWx3ogUkSg1omxmRZXs2Zow7GJfYcVnrUv1sT74+FjbHAuzYy4ljI5O7c0U7h9QaLo3G8OnUOsegf1",
	"KOMFLhFYAth/c1hQg5YwF0cpFhpyfIjjCSI+AYvSWOEA7clFxLU1eTOuZ5CvAZRD8z0dHxZu5Ebf8ZJu",
	"4QH6cnEc3aeGcQNMvS2GPh4+Xv/KG2nAJfJgKP0tWxIuFg+OD+9cwvTWPoy9XnKJ1EhBee+dgnaWdZD9",
	"okHPzbaLfQ1+sFSxyYZPeMLNxk+7zLBDN8Z84/fe0ISdM6rCmXvl508khA3rPStdL+w+q7HbXD/bLGsK",
	"r6SxpWstBPlzAw3mm8GuGHJCPCJ80QIDdLdSuyhPUTmC3o/OhnIKPMfu40SxKddGLWCYAyYZPIWxhOiz",
	"820eaK51OV4ARfLOGXB++Ne8m0fP/sCuWZgVLusAMzorkYdJLekT0jxblSKPJfepE9VyXx9YJcrpoMGA",
	"dVf1O9KECgRrRu6VLDzXgSKwApZZOVoHZZyoXMrjhtxuB8LI8djbm3ZfprQ+lxPTR3CthX2vWT5+y0wr",
	"RIcPieZ/VG3Kc9y6FnU3PP/GWhQElcLZMiJUKgHuieM2VhtsxHEfFBVdAtgfCxcR9rdk0dgHc719mi7r",
	"ZVj3XS7Pg3l0Po4hBT4KWiMOdNXMNa3Ed7FFZe6HdA1aIfTu0va3oAagOyBel/ZVf1uBS179BmccYpgf",
	"fDkR1PTETGsS/MWN77/0cuIb7AqGetHX3Tbf5r5vD/qnVfGFWBX2QuxKx4Yld2hbOGyaxBQVXcS77u/A",
	"1vAYmlM6/nDPdgYR7MrPEi26y4NR4ILPCSa0+ZSbgEfBgASlKsAgr6prHImSO46g8Q2ygZAK+3yq5Jxb",
	"8qbGjaORAlOCsXMXIwHeX4BlRivMD3uC+zU+yvVlD216wOmaxCBOk3VmBymHn8GnjxfrDELgwzk391Ne",
	"bis4v77R6aRgG7CYamZ+Gyv0T69M62/kF4cZ7pHV8LeKsDDqtCXf32eJky3fb8KnJfeIL/sjp0U3Cv9X",
	"jNrLaEGcAKsGhMt58k67xnT1hzYJHRkt8aAVukaDMVgfVZ2bPrrUSmm8IJoZyLOqyX5kPw5rXaNt7dmT",
	"T6R2uS1tCoFXVoq8PSOJztSEQsFDvqNCAVmhQThzNucxa43ZqSvg/6cwZdtwprc+R2aZSeF1+lqEnFtV",
	"5YC7rEc94tXJg3qcpNK5b/jYOcKM/+HRTcMZLZc/fCgef7fM+4u1wD1nqNrfd6AJfYr1XVc6FQxUQ9PT",
	"dW66rxJysl+IkMbGnWvEiOeaVvQMRuItKFzAcj1BqYYK7PeSiz7WbVeLsaHOu79U5629xWhps6XSG6q4",
	"86/m5dzw1WsMPpan09ULvBs9IPeo9DU0FXho78dqhuA9H8tKny+KowXjeGB+cVPtcDMDdLW+t2SPlioU",
	"NwHzRgbnjzW1bkAs0kFohXLRrtNVRNwWFoh+DnfSbdW77aL12FqZ7s9fLqPyJ3ctUHe6ea1qKi3nqDRp",
	"diOR/uOJ76hJtiD/xz6KQ5PjRZ6y7gNc50egDDw67DrFED58mfNhI0nEDAuNS4z1ixVVQn5zz1eqAOe+",
	"Z9r90r3r0buMgQfL0P2j6ZeFIoB9jmv4iqD5QpSBY9eFXefktdQXvtSRfZlZj4Tn1kFxOLBe3FR6aIw2",
	"lzwilExkHMurfpaCHgF94g/upjk8pPfVG8BX+47Xfl/fFh5IM+/QXTSDr3+r+LGpP3z96dKvld7wbc3P",
	"VzU9x+x7P8BlJHDIyzYMeIE5LiXlqan9+UgsdYonXBPV1LLcN9DuQfJi0Uue65HA3OfSpeWhe2ebut72",
	"msWTfumYRhYLjcRWabzAvjEsSUGn4mb58MHyPBksgjv3Bnlzy/HA9akujHiuS2fRRiqm8xI1X7RUmVNR",
	"bl+9aKKSp43stz6s4Z60vraZEJ9D9WsVAed1BpNPX1qrDN5QXjywGrhyptjqGVGNNV84D6rOjwdLw5x8",
	"B4QqPyhDeMVAJ8dgmqYjWBDs7t4ZCNae+NzZZWCp+XFYvu7XshPoeLjMqO2pcJwBjIX3npTyeAU/pg2W",
	"xoWhitoys3GmoeihrzIYZOfq2h/Sg1mgxSaaQ6O2C1Dp+3mAt4mflqdHFMUYeTgFNxYx/cHIFHu0gNpr",
	"JEllmsV+skB5IyTl4QemBuTU9TYcL0hQae0VEKpDJqxN3xb7LLUL+zMC+uVEQEvXcnfxzwoOfvlBz8p2",
	"S+RaQdm7ioA2xQ3Ll3Cf0cOGln0PHEOsoNsyKr0sj775PeUxVnCoHYXW8/ybx7Eq44JWhbP2nRqPtnu8",
	"yIcRV1bwk/joZII9KxIe9TXTmkvxwukm8CA0URASek4zBcNX5pTHWLchFYT08T6XBuw0xbXqNLAuulVB",
	"lX+KINeGONaet7kSxMPPQuN/1CTOOlFWIkl3J1fuNZ5UOURjVGmT0NHBjOLEs8D3bA2g35ImDDgM4UnC",
	"Ik4NVEr6uYZr2ZTzuPquBeURWDA03t6hylLDohcEP8xjbhbWfIJSaswkLOZLul4rEQu5dmZDc7jn/mV1",
	"a3vdB7b/b0LHD50B+3uK7VTheKsIz2eL1nyKXuMqgdzkeOgre9987mKRso3tN+zv6UBdmHDNqYovi657",
	"yKXEwncMfbpcaY6z93e6A7LvRqWNpZmNBHgrqIjIwfmPJKULbLTk49c0KZr35SW2M5jXASUpqWs8KcVI",
	"BAeI+n175ADc8LuHDeNa4YvYyH3vq6/IPgTH5cQ3MUUk1ASwzOe7BKjVfuUINBgJnHvvnQluxiIu4b5j",
	"D1R85uzVAXm883yIDm7XT0/JqwF5BaVdgibMfRRWtLsciUnxtwF5efoaz87FdI+8u3jVfw6/cQ0DntOU",
	"RYRmRibU+5oQ6Lv25CdcACi5mOo9cnB28gqgfvIKC5Rxfh2Lyq/YQ7xLNVOmKPGHo8grFCkZ/JFF5ANb",
	"OB/IFqJ6j5Ty+LrBSICXy6cTKLuAE6twQt0D3Rh+58IuOiBnXo55POAizcxImCseQoZqlIXQa4lEPnvQ",
	"Y9kjv/tz/isjMU+4gY2/ptc8yRLyZEhev8TogYXBk+EQP41vP+sOyClI9F9ZlA+Sr2Uu7TzCEAvT5tJI",
	"eRlbBLjMNLukeiHCy5Sa2RVddF0DvpFwhOI6RkFbITblQrsmYcPBLoE3iXsTjQlEdQKrK7+IdqfzCoqL",
	"SNkT/oiuRXsY53x+4Rqk4I/uDHnDk2gkGHZSxbM/7g58t6tnRX8beNUu06u1woJuJ/idkcAVnnjYH+OB",
	"38sxUFme96J95iA2qQjwTJfv5Vij/kSziJuRSDOVSp3fqW9N8V6OoVzen4XlqTSV/J3g26OLkXCM1tc/",
	"KGYUZ3MalyjUdfxxGhygtw8T2XUqXAl38hwj2SMR/KX68jfz4WAnKNpms8inm9bT3oZutq/r1l16cIDu",
	"2/yTkXTja2BPfoK6Y9hNKpnlygh61xDwE1SyWnpLC6PcqvJGsoIzdmuz1hN67drNPxkOm1xt7Npsh3q+",
	"als5Y7VXtQFzRfZf5qvISeFVqeB/ZWYsZx1YjtHAHkYNozoeWBHNb/kMhti3dW9Cjpo4JHOMYpLFMbZy",
	"2h0+e9AtYZddN70YeoPLhFXYFYt6+KPjWo6p+OANFkXnz/q00zzP5/gQerE7P9m2D7K5zh0vSIDLBsUb",
	"BSskjhNazGU0nJUYpw8a3eENbhwmK8eJEhpbjYJhkGfbYryVYr1SixLPu5xYzUo8JqiyqyDnZ5BY75cI",
	"kFQD18mkwmwsDHYerde1HStwGqiUJ5YJ3HXY7UY04O7S28gVjHs4G6KsMtc15HJTMjQP2owITGlY3a/j",
	"wD/0Z1zpS4kruSu5u5iSR4QvP5wUFtjocTxH0PuMInmQ32cEqTbB6IGjRzlSNWQkut76nxg0ustkkbVC",
	"r6UQbPDw0aswR50GjF3JlzdswlHGzXWRHX+V/xxBnZWgb4/ltAJ0+JDU9kcN3/hJHfXIzd3w8bvuwXG/",
	"jL9xdN0DW4AboOIfugfHLRh04QxCl9Mm/SLdlA7nr1JgaGAoMKXaeF3+vRy3uqlg2g+W6Nc9VkHdhCmV",
	"peEkABqTt6fnF01dxfRChDMlBY6bAN+as258CYVwuaf4rvcvOiigf9H7lfwr1XoPawm7kWEtAcBvmcH9",
	"fy/H98l4i480WcrFJdyU+/5+Ci94+ZBg7jbYi/fKgfM7WN1OEsZtrjZOf8BH/jRNvxTTFC7k7gxTRIEv",
	"3yz9xeOhJySHmPdpkiKo79MgrcyQfWBz1CHSMpLAH/40RW9liv7iUGYJS1fw3w2N0AIb15mgeIH/HAZo",
	"K8Dbjc8WQA4firL+qGYnXMWS0XkXfPquTc77ZOwNw8Ef2Nxcg35/JrutB93vLM3tZlIHG1ncqjzL9cAg",
	"73Qx93LU2Y9cN51Rh0RKppG8EkQK4lo4YQdL6Fp5kCeGSTX9N41v4epQzOXGPhbTIMtdLl2HlLyf5XhB",
	"Ijah1spf17oSW+b9acV8MVYMXMjdWTGf1pvlAQcZeTzMh0vgD/dpxSCo73XOjv3C5xqyg4jUUMgLrOUP",
	"YMXUOit+BqNGOwxaQtoV4mVDo6ZAznVGDd7nP4dR0wrwdqOmBZDDhyK0P+x0IDjd0kygO2Db91v9BPu+",
	"bdlTa/nQfcqS0hc+k+G0BsX/NJzWg+53Zji1SzZYza6OZF3DB5qwPkb9yJZiMYWZ1mOqWTcfoL4NwKzN",
	"4JQhjUnE5iyWaYJ95Ipx63vb27F9YCa12Xs+fD4Emndbqy+Fc5x7xUzdHozpxWm5kQyL0CCWLWhGxjDt",
	"FqOZLfNu8eVaGjsjwb/3T9W0fxwFPmG7NBi3Vx5x7AbK10a1LkOida6mxobmrpjkZvM08ZhKZtBLDCbQ",
	"ftqAzfKRSrNWm1sV+/UOzt4dOla64xpaP+pWJkKUp0E46zjH7Rdo0xQt9ewLk5iaYuzDfhyTK8Utp/cs",
	"Wlevq2D2kDu/Mct3R3UtDdsOWm8GVLT92yFmpmQ2nfmeZV+7EPvb/YuD74pgtWrrsIRLb9C5bYAhdnAa",
	"VBobbv3HE431s3Mad1+QNNOzPKfRIcWEKcUiu/Z8ONhdPrrrGtVrVkEb7nm3u6lLhJZdIhbfxgsfLi4u",
	"s4p3yJKWd+PCNMu7edwdEPQAkZklrVILMk2uKIe6LqwC9D13fRqKZd66R1LFpeWjyE32D/4GAwUUgA+n",
	"nGXKquGVjTqn0/JG8+TG5a0+6ebftijsx9XGcsotpwxlkmTCSTwChdZkay55yHr2Tk2PsITyuEtiLj4A",
	"z5C5S8gFNss7zJNOGjC7PiiutMnypLh8oJyvq6sOjNMbT4w7syzIr5b/jukiMTUwMyJm2khRhXI+u2b5",
	"DJWS5tL+n3UH5GWlr5LduFTTfvkusaiGlgvdJzF1fZeCY32W/xzJhHJBZixOmfKjvSEbxfGBnWGVn1TK",
	"bRv2XS9OjeMVVak5i8kLvHyRKlQLYR3YgGAxpF5b7lgbJrs7fGbJNK2W6w3IAcWSTeMKEreLUiPXRbUq",
	"/zDL4+PPH/9/AAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
