// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7L1rchtHmii6lbyYc6IBDwCClCjZVDj6UiRlsU2JMknZ093QZSWqEkCaVZnVmVkE0Q6d6F+zgIlZwzn7",
	"OEvpldzI78usB1B48CnKzYiZNlWoyuf3fv7WCGWSSsGE0Y2d3xopVTRhhin4116mtFQ/ZUxN7T8jpkPF",
	"U8OlaOw0jlP6t4yRlI64oPYZCeF1opjJlGARoZoEgl2Zc/whIEMlE2LGjKSKXXKZaRJzbYhiOpVCsy45",
	"TrghRpIhM+EY3hxypY2dhHX7otFucDv132BF7YagCWvsNHD4RruhwzFLqF2qmab2F20UF6PG58/txoEw",
	"3EwPow/UjOc3g7+Sjx8P9y9fklTxhKopuWDTLnmXaUMGjFBySWMeuXde4X+fE6lILCfMb1uTt2dnH8jz",
	"Xo8EXMAX5zwKSotP7QLytfOo0W4o9reMKxY1dozKWHkf/0OxYWOn8W8bxTVt4K96AxdS2tzZNGULLuts",
	"zEhIDY3liDDcqz0iMmBcjAhPUqkMi7oLDhi/uPFCD2H4Yo2w5MOIJak0TITTH9n0LaMRU/Pr3os5E6Yz",
	"YoIpapg/fdI8ebNHvtt+sUX+7//Z7r5skUyzyEJOQi8Y+XB8embvQ007mg4Zae5vdzaftbpklyiWMhjI",
	"boVpQybcIKRpmjB744SL4t9SjfKLBcBlSnNtv08VB1jXWewGCbjfkjlXLI3pdIfYYwpg/q2XrS45hn3R",
	"mPzzH/9N6EAzYcgYtk4SRoUmlAwV02PyqxwQJSeEaxIqXDCj4ZiENI5LsITfFhdVOtTOj2xaQQl2RZM0",
	"tm/1Nr/b/I5tDjovw297+D/f9nq9Tm9z69nz7Rcvv/2ODhrtxlCqhJrGTiPLAErncQov9k9ysAit8AXY",
	"jbu4nDgMpnCgcFUbDjQ3EBAJE1EquTDdBTgDb53fDeocijDOIrbPNR3ELFqAP7+MmSAB3GabcPyERO4b",
	"xCjONGkGTMCj74c01ixoWWCq0DjdJftsSC3QBPgOae7tnnV637UWEzg34bmfsHKvEQ7X2IHh8msaSBkz",
	"KmCPRzzhZsHO3tErnmQJEVkyYIrIIeGGJdriEt6VhXkkwH7l8OPWdpf4bzd7vcWLj+3k9Sve2m43Ehyj",
	"sbPZ67UbCRfuX/lGuDBsxBRs5D1N2CmjKhwv2M0e1azDhWZCc8MvGdHZAAGWaPiOSMTuwK4uIEPO4og0",
	"D48Ofzwgwf/84/8MWl1y4hA+v9bJWGpG7BcklMJQ7qjBJY0zRqiYTsZMMdIU0ljWNuRXHSniKWD58U+d",
	"56/t9cs4s4u0VCiKSJCOzo0aJQHhImJXZCiVPWjAOREyQg2JqRoxlZNtzf/O9OJjhv8sZ4HHarQIUY/V",
	"iAr+d+TjiB1d8kExoFCOIFokhHWeHJyeEc0SKgwPdZecjVlf0MyMpeKGwrEHUo0s30O6bD/af010KFNg",
	"N5rQeEKnmihGo1wq6IvgPzrHatQ5jAJPFR2VCI7VaE8Kw65MQBIeRTGbUMXggM2Ya1xbLrz0BdfEXkY+",
	"e0QNJTQMmdak+eb44/v9Tu9bEjN6QUeMjDKqoh1CyVhqw2NGQmA7fRFSYYeJlN1TqKTWHcsRBmxMLy35",
	"H0wJi7ixm7LL/HhyRAYspJlm8O9QRqwvBLsE8YBGmgS/4cF8LgtD1IxbCwUEfP8uKN0pPPrZcjApFuHP",
	"6c8EPyWX+CIcn6PLIM4gjDQP333o9L4FbMF1kQnQSLgmYTqW0e8Qe2Mbob4MuuQd1wk14ZhF+dBzIhPw",
	"UZ2lKI7491BMZFGXHCAP2yHBZa+7GSzGBtzDuRtgKV58tkfriLP9/TWNTlA2sP8KcTv2T5qmMQ9h+xu/",
	"antcJab6W4MpJRXQK5T6BjJCkYnCu42Exha7WXQOH+OFMg18DHhyb3OwFXZeDp/Rzks6CDvfRs9ZZ3v4",
	"gr4cfBt+F/VY4/O6t35g13LidoV7nGHMuMhcCrKLbZOEa21h2YMakkfdRlkxcRfYJvlWyOG+blsR2G2a",
	"zGFwtwE81jAlaHzK1CVTB3hQNztbHKh8rplgVykLDYvO8bUve7If8+UQDdslsCp3DnBKlg7v3w64SlTB",
	"gxfe3bkTCe9uQ+9w4NKtw40LKTpOpqu/9PfSvJGZiG62USHN+RA+L+1RyHOdheNzOrKDfdl7PmFaZipk",
	"wGdgpXAsBZNIlRywRcwGFQASSqVYaMjhvmWylER8OGTK8tyy4vG897wN0zzvPQNG8bndcCTKKVVSHllh",
	"4W4Jlj9dI+U5yCLnmWbnVE9FeG551IROv/gdFNSLsKuQsQgFs+0eefeabJDNXrvX66EmhSwMpNEu+eg4",
	"9GWvu0VgS8RtCfidE73wGxC6PuerBiaxG9HU1Cmsu4JQ/I0oNuLaqKmd3gp98NTKPGkuVxk2UshPQd/R",
	"pMm6oy6h5I1i7PSXw7O9t2SgeDRibULJEb9kP3JDRtSwCZ22uuRQ2B1sogxkxapcWrRbzmVQIcnp/o8g",
	"uyoaGgtMhF2xEARSy8FpnK86f05iKiKNcBlT+1PCY6aNFM4UkyqZMmUFZAA2/P4c2eucIhhZYXrImYLz",
	"tUfvJ7zgInL77jeGijE94SYc9xtt0m/E/JJdcIP/MBMec9lvtLpwPiBcOBGQkTSmxpInEkmGwp9ilseH",
	"BsV02Ik9LFx8oQ0XU87ruO2GFeHmt/NRM9UZ0tAyy5AKKXhIY8KLTTb3e8/PNzu9zZKA1CY8STJjNbi+",
	"oEO7d9Ttu2TPAr/mhpGP7w9/+nhAmkjg2yBCtgBewZ5md5qlminTFxcMgXWQxRcevJsfxlQzst0iVESO",
	"GCkGNCVkxFiwttRKWalUoxkkBgDUY55q+GiYmUwxsn96RPIv9eyh+dsuDu88CjctUFBjWXRjp/H//ZV2",
	"/v7J/k+v8935p9967RfPPv+P+jMWQz5CILLStBQ0/lACLpR3qzdgAaAD9/2n0+P3rwmOkTlsGsRy0CWn",
	"Y5oyQAtcbcfO3NEpC/mQh13yXpJLJiKp8mdkyK9YREIZZ4nQAFtWeJ+asb3pkUQoAmwD0WjmWH5rWAXC",
	"7o2nXfe0G8rEnotUprGz3XvR+5yfgBz8ykIDJ4A2nnNqqpaard7Wi05vu7O5fdbr7cD//aVsmYmoYR3D",
	"QfOzCsaxiKf+vOaO2ZkmKjNUXs1NBnZLKGgBWZ+3/DorVkjjmKkO1ZqPBIvKCADaDRXED0T0VBuW9EXz",
	"7Umb7J28axNmwq4HbQvHQIUTmoKOmNOu98dnq6HeKlyBRZXAkRdqWl3ygSrDaUwywf+Wsb6w2oUlZwK4",
	"K6grjhR3kYw6zUNb7TuR2hApWF8UW0CGn1oqiTZU+6dUo1ckyWLDO/hCX0Rc02TARxlCY2TRSKF9EhjO",
	"JackyI/YDXt28B9nwSyevdt/19nd3/1wdnDSeXPa2d+zOCayOLZXufCm8dLWUQu9wjR7xftcpzGdos0D",
	"j7TAoyqydSsLLjGu18C4SIfgqudW6WTYtVeapdH9I4nXGOftZFJIg4Q+nhIuLMqCsiRTwxOuDQ87sQwv",
	"cuU2lJnVVpx579s2Of6ps7mx+7zVJagHdeREWKXWK8ZECoJ7nFWMv5sBi82VhrLCWPBXdDHkCgMwtLY3",
	"F1W4dkEiinOo0KbKHXyqoWO7Iyd6zgtFo5IlyQkpXQLva0IVSmPjLKFCW+ZHBtLoFpmMJRlTEcWMKJlZ",
	"fgUaIA2BZXXJAQ3HbugBi6UYgWmSXdHQxFOLvRY766SVJ7Zey9ZZkp73es+3bsrIH4SNJZTHNTAGUAA/",
	"EhpFimldpUw05iH7f6tcOV8BDrqcaVbnO5VD04lYzAwjw5iOurk9Hz05IOIi0OvCU2BvYsLjGARUmqaM",
	"KosUziI+4yooPAOgrwR/nPUDfI/uJSOJztSQhiWXBEw9e79P3P5xc/u3J52Ddx86DgMfms3LYQG0VdTZ",
	"tahD3o+yKRN3wcn1BY9jXYNT8JzkEGakkzsAj8A4nCo55CFnIpwSK3+IkWUDyYBFEYsIHL+xJOCHg7MS",
	"Iln4ekVkwo0ljgCtdai22cPH6AGzXGkYU4Oce7dlFQbjYchOheRuY8a/hzZpO8KqAwGSBXvehR0nlnl+",
	"XkgCqVJ0+vULQq0ipMLRM8vVSfBh92zvbeAt0vpVbm9eQxq6hQTkKf+diD5HXJtDw5L5U3sTU+PgWLFQ",
	"qqjwhNe4iD0iKAYCj0AKbEUaB8JNAMmSWxF1VYsHBLELaWqBEPnorSd56PcpD92hqPMkMTxJDF5iuD8x",
	"4KH52GPkGLPsf16vQXpeEYqoKItEtEYo6s5R+HoBEKZH8c8iU86QpQAJapZ3tHMGJAWZKEvJBzLibEbV",
	"es3j2CLpKeLLOtdU2sIi3W5+lxjMwzUeUZdALJfml4woKkaMbJLmgI24EEy17Llt9kiTXdlDaUHUCjlO",
	"mdj9cOhDHuZ5rSaBs7QEG4ELVQqIlkByJE15x8LGiAlyRKdMkU0fIyEVOiIsedJjqUwn5CrMuCEyMx05",
	"7OAKnWsC7tFHQeDS0OyhSNN7dFIaXtARa5MPMRWk98wqhoSJoVQhQ465aQVYHNdyuKrYtLXlohTBq7Yn",
	"I/a9d/zBIgIkeEVYE9d2qVYrwCEtfGjGyMnx7v673Q8EWfAzojMMqwktOChLz553CcZtarv1LI6INhbM",
	"IqdtJFx8v7mR0KvvN3tW+vl4aC8nVewSBOsBhgZbUZJeMP0K1jThihENBv3IyphilHE9Zpr0GxMlxQgX",
	"3W+Qpt1pZWctZDb+RQt68F6vR8quz9YMbf12nkg4zeUaRG6GrOSfVwF+MXUw1LD6aN5hZokCIIY2aDME",
	"sbJ5erZ7duBFsmqwpX0x0wQkbYs7/uosSbmUPCKUDGUcy0knSwH/rZj5bK8SvVbn+rOruBblHyhGL87R",
	"0+w+pHF8PGzs/HW9IT61a44ERiU4au5mDDMFDvXX8CMelT+j56DTiY7lmyhRYAyTO6fvv8evgi55b9+w",
	"soF90YyZwpGcwLiS7zIxoiMWnYdjKgSL19/vHn6AUdO1m3ZDYohOxejkdh5PiZveXrnf+vbKrR/gR7ff",
	"/HXFglRqc16y855rjwXrndkHqc1h8TniUP3hOU0BoQJ1lV8UTT+mhF2lXDGdn9cLMNsbMhnzmPmzcUcD",
	"JyckmLcP/FHnI8Hgax4VvHt+fdV7TtV2q/4WYgRCxaxsgQAA/ky3Y6umYQjAx0OSaWAjHMhBxAwL4WBi",
	"RlKJ7HzGxpFTyme1lBIAaT0TCL76UBLhRNE0S88zYersyGXfDDk7O8oJSfk68wN+2eqSX/D6J80WSaku",
	"TpEnTBuapG34fEDDi5GSmYjISCqZGS4gu8Xxbjf6P//zv0hQjwABMYpCWLO9sOU4ufDktped3ArwnOFl",
	"OdUvCcru0mcBeU1ROIeYOumPXlIe0wGPrV7lqJSTnkosry/64ptv4IuOkaNRzOyGdr75pi86JDhhNJoG",
	"GHuFw8UMA91DZqXGsnMJPngvTembTBRfNYUkOht0kNvoVy64xieUAN9owRjIQjBOhVl9lKppMRTux8nx",
	"uV/VzoAj44ZOQTnuaGb8Vjx1hnELSg9So8VVKsq7IU1UrztccMMpkoJ4igtE0MORLOh1yh8CUexA1Hto",
	"yESqC6vUchnND4mjHQ+HMRfMnbLnRbEcAVW0AqUC1MB/1A0CqlWWWBiDw29ALKH/E46z0W64A2i0G7j+",
	"Rrvhpi5BWIH08NmJC22b17FqTr7QskIqrELPkA6UBAnngHTvj6kmlAQWt+0wAbiFwNYA5FQlXEAuAQN0",
	"rbBqFvMRt1NbYoPEYeRYjRQo16BWEBzqk3z8SCaUCzJmccoUCccsvHC0x2HEZu/J2Le+sQ+F0jgTEAn2",
	"aO19Tos6l6o2Y+7UHhkcvEVf53CvSMYpDy+Y6pIjSFt0NNT5IiHdcrV9/clY+JUaC1+fHOz+2Dn6+H7v",
	"7cN6GGM6YDHRYzkRPgULqV/E9IWRadWAdOSQ8Na6hCfGtRl9QIdzKu9tSRVcWUCbuy4XEOS1gkmgmaNO",
	"msgDXE/HFsZgDghk9UEDxUBcVwUN9yEcCcbBninKBRcjO0D1ihekAH61ptb8+mbJ3u2tr6+z+ALTU99Q",
	"HrPoRE7qBIMh/IgR5ILQCqUYgHcSM6GeO4uiVHzELX7bL1wsvr1SS3lYOJYsIs05FLYjbG5iogjZO/2Z",
	"RHIiYkkjn0G4tVvNIDyRE5ewiU7Czc6Aaha9glk37XxF7jykvtnnyJ4hzgqT67iwk0HaQvE6eJnBAw4A",
	"/6fT4/d1MgTzSTwzB4Z5fYFL0cXTCxzqTDoxu2Qx7lOT5n7n2YtWtyTuVb6qFeMg6naBQQxSOcGUDTIX",
	"pOFFuDPK40yxNuFDfA0X0p3x9aFZfyVRVAukyLdZQoVVCCJAXHaVxtRVRnChFW4d1Xl96hSGLjnMq5u2",
	"DkDdxcP9Fhm8fi6QhUKpou4KdX0GJe1U7UaRTQX7XY5EJ5AIX3MoZ2cfyFbvpWdqqLhBwsYc4wVE2m6T",
	"/c6zl6jKWayxfB8Qg4lLFsvUW6JTqqwmbmTqwAqpv5OTcft//RRgMEdf+JzMmbHQpOzzymJcVSgFZPmL",
	"cNomg8xgdmoxkzeEWETjRhPL1NzsdtVuzz2UCqyGruREo7XV4r+Qfn2B5f2KM93qkvyk8Csx7Qv4zL5J",
	"dt/vQ0owoyhIwIW7AXW3ZOK33+4eHZH8076w85UXwKJarcBh3bxAaVQWWvE58ohrjwiqERTEsUsOktRM",
	"63fcXTcgpo4mf56Pf5mrs1CXBj9DIFTGvIOD68oF0kVFHYpSBeWUXnBsFGUk7LOZqgtFuYk3dimWvLpS",
	"D1apRDILPBWKHzhp8cf3x7+8J0eH7w7Pds8Oj9/vuNVaEkSC/OaCUvK0RQw4dCTZ5VW6zENtpHLRT940",
	"qF9Z9QgCQ0o4Ym90KBUTmoeaNDVjxIKGlzjzk2zV2zEXSAYl+SPfQI3eiUmEh/vaki7nkhhmFhcdP99w",
	"rNwRM702PBVyYBWEZr0y+eLajTneUxC7vcJ4P2c+cEb42fhm90k56YuSWI5AtQ5lkmTCJeiRhEU8S0jz",
	"UvKQte2Ipo08ASWLKYm5uABXTR4u+reMZSiXZqIuPrpO98cV5WlaazsfnlKhFpgN/InCxZ270kGP2oCA",
	"0HMO0HM33rf9OYCsKD9UKX5Z9td7fHGeEzKM5QQj/MFx5YxxuYMFI6qFrAL+2r63J0vF12ap2Dt519l7",
	"2/n5+HDv4P7jmt5RLsjPFn09wX5KV3qc6UoV7nV7G0CZwc3LvXkZkrKLvUgjLumtQPpxeSYPEKtTX/dg",
	"cS4VvFRlZHkq9f3mKpcquOQx7TX8uZlSLA5SrlJgZ7QHghEltQFHfVEKOPKDnoMW3voqs4qBIxlpdbFL",
	"hhJ4dzGNKoCtkknkdJWH5kMWl5mn4k5jvYN803mSunYa6AzyL8lOrEVgxKcRE6aETUuKRIB2bz9yPtI8",
	"2eUuPGSPCJNuGbj+BXPsKpgxW7SIg2Dj3vc+2HJVOjTLdxuPCqmuGaS9OlXretlZi7Kt/HGW44sTyBrM",
	"67AiDGN4gpAus6R72/ympcp4Xaz1YtQvufUXstOvHplv75ie8xmv7dx9vKzq+t7MeTa10M9Y9huu8q4t",
	"BeCFHqzFMO2k0sXw/NAmnEeECndpbLkTO8h1zA+PF5euq2/fTIdeiigVqF6MHG9iOVlJ6UsKUywn51wM",
	"ZCaic6+m3UgiusY1jhRNx9dTPDwvBkMYfF+Va3JbP/yGRhyXilMSdorDmr+gQzwEvKNr3c3iy/jJYs5i",
	"NTacnGsWVpbxolfHb8p3D5+uJV7M0LaEi0P8bHPeZfTVEz4kUgNMrHoAGP6ipOinzuvDo6PD9z/cjBb5",
	"9DMAz0ZtshmXiptp5bPtlZapxQRLN0qDtnPIX4w5JzIzbKHKuhslXGwYq7UyYdQUqwNCXD5UIqbOVm7G",
	"SmYjLF+fZoOY6zGLkIZYRZfmlqt/d+PYHXQX+YSqh3hZTycsFBk1PZ8ntQnltepHOZCdizQzqyjjzJHN",
	"XkLOXUoLWXzQoH78flUDTChDachwpjZvLAuVDqB8q2+x+pIjPIQLu3HO0D+W0mkCMXxcp5nBLNDfh0D0",
	"9qRz+uPh0dFtRKL5LNh61bzGzqsXfbKUIpVGq0OIHKrq2mxIDX0MsoTIIUloOOaClWKZIGjGzubCttpk",
	"v/Nyuz2bDNoXpSzQVpEGOlBU+Nr73OVtYGVSqI0uBQkwyiggUgE29IULFaIxFhztC5yj97y7SShUewmi",
	"DAvcMqACQbv8pAQ6QdtCa18EM9jkKifBUaOzTfBLpjSNvVcNIclMSSIjFveF82Vv2v3DX1s+wj4PYasW",
	"0y1awNhrKtU0LlWydr6L81CKYcxDA04MqfW5VJbTVzdZeVBGj/Z8bWj/oMgbsg8rMXb235UzsSqrHRrq",
	"5LLyKLkHvPQMLrLW01Gt3VvTp8GT1Zl4LAtd262i90Cesfb86mpj++qqaBbUF0FRexjiYkq56YOpJb7I",
	"JjXGA6pMkAEbSldrzvGEw/2+KDUUwGjboixQXqS/aEBQ7j/AjWbxEKMIXAHujaI4ui+L3VoaQLmyAjKg",
	"7PpxhyEuM6OxT9+HBghskI1GELrskfLdx9Mz8DMvxE4Ooas6AxIC9sAxZpcDfJKEC6nyIv2zrGmmIHlt",
	"IGVROvpG6dRrRCgeXKXqTSZCU+slPRZwXiiLdPZPj8jQvUua2qjuN20issT+hyr4F8Tu2D8ialj3m9a8",
	"MEW9YDnjWYLCslSNsgTFgEwYiLztbML9XFLFacTD7srMi3lGk6Vp/QELPcNWTO1rlm1Skyk293YXhm7q",
	"Fun0s17vGSPuq7pRsgSMMZUxPtrvQ6pXa5xCl/w+To4uFlYMv+qS9zD2al7W8ze7voJZgZ1Vduti+LoV",
	"vonrw8t9rhfI7JGiQ4Pxq6jmuzjuQgZ1TVasTKkMH9LQkObHw+rbLq5CDolRmRm3uiRwKBr4V2ZjABS7",
	"5LoUpwwLabtCC6EpqGDOLErqRhX/71a+LknV5HphYtUS33dlBVoen/Wi09t64DrNNzA1Fay3MDaRpgDZ",
	"7t8Ji0YQjZx399O649VMLsipoSNGNl9ZOgBRwRBe4mqeQKgsMFjNkwyD6VBPQGBBCJnDjdsF76ywa911",
	"3M4d3fHdp8ogJNw+JsZSqgOrWb/mIrKrrekYlurcBFG2TzTrzA1QeIcbTWgInaFm7BRukTV8FF4vNewp",
	"QX3JYLECRW+KgWUTx3wSiiUny3/1Mv11AO86794OqG9yKstBsc4oM38U5aNr+xuuXNkiiPyAULMoy+Ss",
	"wpvykDYXPq5YB+YCCpXGGTLBAcK3FXLzX+fBcFBgwbKTnsOaKo6v+tQ15Zo75QKF/ToWHdDPeWuuQ60z",
	"Vi/qlvp3pUoOYpZYiTaEc6GGUGK5QBt4AMim2ONgIVefl/Vd4HtFV5zHrmjk3W0rrSp5vtfKNxOmNR3V",
	"o6Td1noz1ttX/NirD78A0OqRcXsp60uedTdakwgD91lHImfBCN5r+1Us3MaiYNJdsUzys1IjBWrezpuV",
	"DqY50ydg687rupIU8ihnSIMFP22oMq+IUTRkugi4J9zUipZ3QOcrhHyFuFj/8XVo8E3cgvmpa0FTPZYm",
	"r9IMmgCLnPxGjT9vKK7Rva2cde2aTTEV53gJ52vKNoXhCxMXbyUL+cuocpiZCQohqW65K/nQW0ZjM15s",
	"0zril0xAJbwxA6XK5Zg19zubL2ssBUWFJG88pLFliJ9mIuouVyvPbqi6Vc81X75Fb+h8nVBcvpGHlrXR",
	"PakLSUAX0Zv2z3K9N11rL8xbCddpyUWCHi8aCvt6d5A1+qLVJXsF7UFdtdJL+BWBFpEoIHBKgh8OzsjG",
	"5eaGVCO94dtyug7EeuM3Hn0OVtOde2vVY69hrQif+ebaLnNXr5vKWWRx6lfY9RqTYqkms/m9XXz3tgmd",
	"C5hwztdwlnO7osoh1xYau0+ypheUpDriQxZOwzgvmu8zcva3O1sWFoOUgbwW5P3JlJyQCS3aeTtNOVUy",
	"ZOgmHLARFa98foHzamkiLARBPdIBpHVijlBg1x0zwyJwmeT5xOUsUN/ck2tIMhorKWSmu8XLCaSNEs2M",
	"R5pQUT3uWNTCMnETxlLMZ91sueRev2Tor0aVwUB4zKNFiRpyk42iImJR1Tvi3gDl1S2/LueybFR0qZnz",
	"wPDdyzpoMNLQeP5laC59LY5SRsFSYbPS+HOrqwLuSn7iuoGe5d6ZFT4Tn11TcJZhqfMq0OQOVqcrHD5F",
	"cbRnRV79wZVhIpq1Lc44YrBY7FDJJAAbTmBkDsx94UDLB2GTlHLMPyOu87LLhKVxLCcsKq2IJNQofrXU",
	"JTLrTCs5sGqLQiiZXLPQYOFLKSi4kOaci3O35HNc5934LSzcXGuFyx0dbsswah1kfaAjLizoHfG68JI9",
	"mSRWPc6UlsoVkEjxE3tBhS8Oe2JA3i7U0nB+HxrHfaH51azUAF0MPL/VyGUhoDJwBe6EezPvt9cXAfCR",
	"gDhImBJLeBSP0OV7hgVctYVzSHiXaJa0a37xvMOEFfQiEubGYDkkwW8F3rWJY+N7bhDndcWqKdCu3VIw",
	"R8RBgg7zNplYWq/kLOsLY0cGi0F5NQgZXbIv/ZCY9R9KgWZSvwestVUH+mOqzxOparDeFRryxZkVg6Xb",
	"d12dAk0GbCpF5Buhjxh4T4dMkcAPG8CxomBqKXQg2JU5d6v6f74nliFjDmkYg/OlYqotWd5yrl8jQrpC",
	"u3YFUDUaV1eWFWpU2NJC6iI8SrftD9HX47Rfuu0GuP6ivoPzc8RU+1c+UAu4mgR/xGG+B39WiFWjwbUV",
	"+LpUMLDD8bm8mumffg2Tn8fRDz9f/MfWm97hr5K/+3V3+p73Ju9Pe1fvf/5p8m5f4v+/kfxo70/pX/YO",
	"Xxz+unt1fLZ79edf//Tr0VmUvNs6MO+33vA/T3vP/7J/Eh+d/Zy8Tw6e/fnX8a/Hv/w0+cvpn767dkVO",
	"POZ2AUz1tMGE4xKtWT9vahWH2WqTgtf4CsvtvihVHD7lYhSXv4ZUYivpYKnp3ZlS01DM07EQnL4oYFla",
	"wjffFIto7cxW7vzP//KVPytFQO3j/K25X1zVzqY7X02CmZrVQbW658wk5cfVSfJqmzNfVJ6XPimV/wTB",
	"b2bbIRWW5gzsofLRiFnZ3hJeQANPi92ZlPeX1w8t7XCmSrXbYVFp1H7nlrloK2Rj0U5I0y7r7OyoKH+L",
	"438DL/qyoe28gig8Ln0eyxEXG7EcycwQKBWvW/Z4dsvgVCN6IB+fy1F2oXbBciksqJOf5o3Ed17OPA8w",
	"xKrcRhbFyCvVy6GTUmEqo1UwDVxXREvyDfYsAP1OqpFVl32n8krFu8N97c6qiEpsQrc6kscv5UqNj46i",
	"U8KuuLb81vxBk1/tqjLhvNV/d4UOACSlGrXWLNwAnQ0WBMfmYgJp7ne+fe6rMCOzbLvwH1daeU72JE19",
	"wdMSKATzgmbQ8idktRno5a59fb9M7BBKnM272vR9jkrkNQFnAj1h2eQDN0NL/J61fCkGkw3Atofga6WM",
	"qdMEoUeC5WIBHAz2/ntFLjfJ7seztySF6Djf8xqTIa0yQ+1xBUTJmGEbQZ1Se8KuzgQGV5WHRHLMoPkF",
	"Jb/snrx3Va9oFnFDnLynpqQZYAImfNuFZvMsClqLRIcHKuv+rtBpsYBuTUn7alV3lEU9sJQrwgPyVQvC",
	"d8nhSEgX+ouFt0sUeU3Ivp0ysEjorzufWknNsfC8BGeZmRtZqhPotu4KPoPOOFsP39kNXDuaanH8XQSJ",
	"vPsEcLHaQ60YCZSr9GzJDf5dp/Q5j+BMPlB1sx+8SbwknkJsi7eagxQ/7zi0+q73CVppH4Pp5xzeDx1J",
	"z65SFlrFxu3lvMbVfEu+czi0mNPOnQkgcoDBh0W66BDjvJF/yJtMeO++P0GoEMI0aY4yqiJN6IhyoY1V",
	"iXI9AafYUDKOBzS8IGEsBwOmWt2lhU0O3CHMXKifuFnENhWThdN8AXl4kzNv596sVslnsjABpN7N7dda",
	"h5WYg1Jj08ZSSbMFw+B1TcYyrpbyIhPKjWPjA1bbDKr4mEKKSLlqSZv47JQ2AndtYffm7t4vLfAfqdo2",
	"L0U+18xm6ociGw7N3Zh2s5qFUkTaseuZIvWWwLRL5ARqrmtPK3IRIrE80Q9U1c/WTC+bMYdUyrvAFHg5",
	"NAxZanzt3r/2EZOxBm84pqbf+NRa2xR+/9lqv/tKa3eRA/dA7punkmNfY8mxa+Ud3i5scWWO4rU98KWc",
	"xioQwRQ5A+iSt3w0Lgr/W04eWjlnjI+L9wBcnOzm45SZVSahZwoqjQZSwRJpf/pbRuN42gGf8KIO5Nt1",
	"9PkrLU6+RgLo7cMxTxiNuGBa741ZeFHn0gXlRg6RmUb8kkcZtQqn+w6NvmXvvbxoWLFvpGi0wOuWT7rY",
	"GbXPWDo7yeqQB+xRMh8eFQ1WAfrMOQAHHWFdrprxFkqPe15cdapJPkguQOax7jjzeTENAS7avV7r6WWy",
	"oWIR19fd+Mz40aDhB6ocSd188wEnc6BQIB/8tFbUSdtfaz38aqYuqVkUVyaHQ6xZ7vUr77QuSbZtdB9x",
	"o0mcO97R9nAHvQitEJGkphRGVxYd7yKaGJXcZWPcirnAES5f4+37aOT+0jXK42sZXy5fz+pBLCyc38TR",
	"mluVchjH4wGqbOV5+FOxX0GLtGfDEyYzyLqkImQxUusiPqGOQN5zOPXc7tvlbmu4wwJwKxBQAbeVIQgn",
	"TvdeakU5KcKnIfqDS1UTBPqvZyPJDRf3aCSp2ESMPL9VyOQC88X8sPWgsqxiBQTgl1R5nYIH5x//bWUC",
	"zwB02/lt0AhRF+i7DFq+SKoHduzIX1gPdE5QWn6DH2P+7qfZeOPV/o9bQ+6DRcfNx3epTAj8y1muir/O",
	"Ae492VoYDlamx3U0GMDn7poHw3CFkakijLSJtPDJrlgIrmlo9ZcqGWUhOAJY98vl2BRC2CpSPweT81g8",
	"Ta3uTK+kkMkUgjh8fip+pl3ULbo/ZkU2i9RWSIOjLGscPj0k5xpAlUFgXZw3IuS5b711HlIRQYah/SaL",
	"DU9jdo7U9NyRWV0qS+DDvEu0p+TaKxdaiKVMsdZB6XN4iKVqarUjPBOreen6KHBH2dUG2hHz2H3gkWgT",
	"saTRR7LIVJNLzibz1G/M4uhcx7Juoj2a0hDql9jfyz1AWRyRpg/GBCTT5N+xljHUJYjtEkMax7rW6F1C",
	"zHlZwBdUyPcIuBDGFFp6AgRoMsh4HLkKuyjg26028QqYMIumjSMr73gy4Uy8NTrv0a5VDEjTvdHyAVw4",
	"AFpvIwTOV6RXcGRnc9dF1eb5RVSJ1KIDSKm6gG4bpXG9id7dctHCLS8yvHg2OKWFs/noOZkZbWjpXgn1",
	"k+Zt7FDI3UABdw2fxhKiXF3cwvtpl8G0jvScYjYwWypl7rsWqei6KSUQl3PSvd/OCUp6KsyY2fcBW7tk",
	"XzIMP4XO1gwhvSyBEB/HVG7L/TVVw2o38NBYdM6GQxaac5mZNDP6eolFJ46MbyQytICMY3WEjBhxA5IL",
	"NkUDIDzl9YUG89WUaa3MTCiTOl9LyRxA/Fu5MYZb0hgxRbT0ZMspk3kDXYAOGsfTtf0uHvhO3UJLKzjG",
	"BdRm1nFlMhqfh7EML84hzr3GvcyFK7mAc0j1B0vI4UsCX2JOm92PRZoNp2qSlJox9ASK6bR+a+to8bPS",
	"whxkrcbFRda93TIComSU5816/b52p00t/b4smb2iIcZqFTTYCwu+WA83NXZCmHLVzZ7BS+telpXxqivG",
	"Vo1WKQPDNYEQ56Zr0pibAQsRULm2Wp1wLLXfkttG64aXVrd0J9ouvb4l0Fx3me7tMin06OeqA9UT3y75",
	"BdIAXAJtAGE13JDUQv7Z292zyoj2rT9o3z4N/EURVyy0QkkzZaqD6cWA4x0uImZlFBAHYBqLGflMbd8Z",
	"DzoiotQUQXSjHQiZH7LdZsxGNJzWBuaVrYHX151KacNzvWMF2gAwps2dJM8RJN8/MC9q5o6pW2uUK24w",
	"z7RbYbISsiQbf1oFbX6CWsi64HFtbzMsDz8bqACvYxh9JRgBnD6+n32q5JCHHAIwFPRc6D41I1/P131X",
	"hR0fqKNYpXrkAh92LMUIm6uUXpgpu7ig2mTbnlQG4SF3UXfyySn/9XQsv2YZzrvxyi8p2XltI1mlxOes",
	"Cm/YSKqplS0iaVUGr+0g0fW9vw0Lx0ABMfYopmKU0ZGLREI7lIFu4m8UYwSKFPoI7TSmBnHOq0Y+RLiS",
	"jbRG6dGv1k9fuoHb++NPs0HCDejlh159m+sGSlNMssZKiho+MY5BOptZrrebShTcJeuA7J4LCVVmuVAi",
	"Qfu7/xCdp3rCVJfk1MpCRFQqKQ+pTvCyi+/A3ou5GcmZOKghTW5Qqkt8Nl41yLt0eVAPdEGFgcqhNCM+",
	"4ka3AVotGNM0VfKSRf3GRj+XdSyEU6IzdcmmRIdSsTb55z/+d6tbV+IkqxdszrwuMe97dhKlygS047VE",
	"eFbtgS7e0G3fXR1QZ5SjuvdXlOROzNqnKIrMbUqT5mTMw7ErxeKq/WGOx5xjD11PD+6LuOAiKgvC7o6g",
	"KKTfTa119rr0uSR038grff1j0Ial65cCAvA9NSxdWYGySgPhAP1kK70DxSxzsTRYHXYegf7ClHTJw66A",
	"rFXprhDi7KyEC80j8BlTZUWl2L24RFwrh14UPoHqac17gmbDZ2k2GteZAKpNwO0i/6A943UeDqzRAAOQ",
	"wRRTlsNYQqYPWPqoWbqBkhAZub6B53UZswe5L6m59+EjRkjnzN+w1Cpcic5FQG+5sGwD36XRJRUhGujA",
	"uFRSMZesz3l4rYyL5sPCibdagvb5+aulMAsJ9RE1axk9VzZT5MZ1J18Kl7GUKclfXQyf4PAZSrUBf2AW",
	"y0BG0/UAtcSU6yuPeVpWp/DfxWGAvFbLdHECkhc4d8KBvHCipR1wA9taEW9q8FbK1lpalWKj2lsAgSTy",
	"EA0p9TLuQMlHSCjG7wpEJArEILiQpr2GDU80NnK0a7UJHxIqpmutbEG0my+loC94moIgqDMNhqhotQEF",
	"4bq48vIFt5dVYXL0v0ZYdO3vmydv9sh32y+2yP/9P9vdl0gQOl5CQRWuXCK3L372USSZhvzfl1Z+wSDe",
	"Vzjqc1CWYzlhCgw1XqqCEiAgWu+QoLf5XW9zsBV2Xg6f0c5LOgg730bPWWd7+IK+HHwbfhf1WDCjI6zz",
	"TVkByDI4q7kr+giy9nw73BWJ6CCie6cXftwlhyKMs4iVih3nJlwoA/DDwVm1cMqCRCHX/7jenDjTmHfN",
	"DryQpAvh0Y68y5IcXCqsJ7XpuI6LrgiQbzPQ27Lr+VDTTwRHuW4fESwyDX9CYQ2H+t7KB81J+gIO3Ei0",
	"EqhLRvQ0SZhRU7Tv2Tex5tY3/oqgcNQrQgeaCdMXUqGX2C7ahZtj3Y2OTHWXnDAB1aZcB4ZZO8FX3R04",
	"jBlV1+0LfE1D1DsHOP6ljsuw9EYkbyN92fL1L4iQogPO777As7BrbSrWGnDhs8lyg4+Sk1eYcpy3H8OP",
	"+iLoN/oN6J+xd3Swe1IpqNpENwnRzGhS2oB9+/SnI/L+49FR61VfSGgymsNh3lIZEsuvoPb4KB80E9h7",
	"IOq6XiPbfTHkV+TtFshIrgKIvZcypNmPYZyM6zGcFRAFCXEnUvSFN2u7cDtJU96xSDxiAuMXwdgVStzY",
	"QJoxiVjoVey+EDwmwTd4KkGrTTTq1XBYHXfCFhe4YLH3D0QyhCYALOoLsLtN6LQAGbLrDcRgK1MsZna7",
	"CZ0SGkWEEqM4FuHoi4miacpc4SWXMB6DvBP7E/Hjtq0i77Q+bCY1Zn1Rv84Jj2PLUSKWKobVYQeZcZns",
	"Yymk1eNnsfN2naPXb2zvI/gX9LEv9af/53/+V9GR/ub96JdF8DsGdr3+0xX2hZmbD8G8nnjTPfKmu+q3",
	"fYettJ+YyRMz+VqZyQ07pt++J/qbLI47EMASMnAxzjZHJ2BlIs0PH8+IZgkVhofaVw77VVoQANCwcHT8",
	"U2ezWtGKnODQOq+eo7BUCTUycdE/efN1BGBcaQlk4ajusP/6vfPaW/PXmzd5f+Jud8Ld7qEB/dKm80+s",
	"64l1fcWs6/XJwe6PnaOP7/fe3koHUhIBux4lFlLt4y9LrV2hk5voQ75mzQMpROWO89er3vLEbe6R2/h7",
	"weC3VHHo+3fTvsYQ8HCOpWNu6FW/TmjZE+t6Yl1fK+vaO3nX2Xt7/ZbXX7XxbiYp6X60ipaFibWIOVlM",
	"y5GF3cS6tIw8rdWVaO7srn/1c3X7yoUD6rn3Gtlrq+8Xqh8tvOBSTbs16sY9UKG3JzniTuSIuygX98TZ",
	"nzj774SzX6u43UL6Xi4zt7Cj26PTScEI+mQ7/BJU+K4SmWZyjJ50sifK/S9iTrxmBtSNspqqWUprZQM9",
	"PlrvIiL3XHmXG7VTW2BHTNzSmfYmxRu1U3MIUXQFdBnlmkfQVA06WlLtw2YTCS7HIogW9oVs4OMhyTTT",
	"pTGNJHosJ32BnGYjYWrECB0OpYqoCJnHokxDzx1BNGNkYmG84lqc4Y04+oKcHle1qbwNnxvoN4O0qBze",
	"XuzjFFQmgong4EVFVHJDTKh2VdpdUhYcm111ylQnn8fdntO/7CbKseo++Ncnr+TFfz7VRjPPt4XzH3oQ",
	"uJuOcKsavPlzn4dzi60szKwQBueH93SsRm8ZjeqKyLgIYxc8PAXuNIYmMFTwv7s8/7zhjBSW5JFg43Jz",
	"Iyi6uXX7ovnm+OP7/U7v2xYAYOB7pgZQz4JoNgJo5RpouaJQ684DesKjKGYTqgDOqUOXMSyZsKswzjS/",
	"ZPH0VRnVBsxMmGUZFOrfRP59ZEV9QeMJnWri+12Wf+2S/eIQdmoXnFJFE2aY6ouEYzvU0iiWGJwcnJa9",
	"/JZaF72XucEdBjhqgFnfETV0QAEcJUgLVlDDZdptI6MM/qNzrEadwyiwuMy1ldWgMF5fFK1k7EiWdV/Q",
	"EfOtN8fScgvmutIRFkG5LUsNTo5Ifj99caxGh9EHu0k/AJQYdG4QbqECt+mzJHcafkkFeNOU/8imjc+f",
	"IWtjKFFUhiL/IIHhd8cpE8SVxGq0G5mK7eDGpHpnY2PEzTgbdEOZbMSZFKOIXW7IlImOy6SbE+wacOQJ",
	"FXSE8Re7Hw7hKsrTAFCB7DRgUWSZYdtlIPueB274vvDpr12yG8d5v8K9k4/77XIdoHILlHY5txryza08",
	"M1RU++65pR6HVhqK2JALZoFTYdfCf/s38g6Wc6xG5FBLzFazvxxAtx3/OcmEhbRgvgtxYMFmVO5mHByr",
	"0Z4Uhl2ZwMKrxyYngs4i9B+0TyxwolgBcnkFFoSALnZZrGJEGVcQPK0UswQn+qKKFKjgFLBv6AUr1VZ2",
	"OOYh9lmbuL+2W/4EgXuTg7wX5X7n2Tbw3BfY9Sv2LNYzAKQDtMSCQWwF5WbHfhIEwa/a3sNvpI8Et9/Y",
	"If0GdgLMtS7sBoi51UiOy69FzFAeV9/xtL/8Xpbx6PKlf498hul9S8sAZg9KqhwJY6lZRCy3spI+I0G+",
	"oMCxthYw/r4IihlLQ0CyN1Mdf7vu+hMrSBVQ5FS+w/0KEL0iHOi2r8kjheughXnB2tUwyYTvWlyl6P7K",
	"7JRkTwpLyiCzbb+z+Z29s61efmeH+5o0nU+PXLCpbucEtG3hi/GRgOctwC23izyzpdsXS1NbnJzlZLse",
	"2fD9ce0Efp0fil6nvsWp/eWo2r7UQtOCFqkogdU0Ju2La3YmRewtt+NET3dfwH0qdsllpgshZ76DpZEX",
	"TPgOlkaSIbMSdrVBptv3acpCL40jKHJNtH2INHjg4tJAe9pztPKNzCxTg0wjHjNtpGBd/2tfWFJaOjQo",
	"uIZkDeCtjrSlig2hATAs6jBygtw7GbHYPtwrd5XlDq9deYsmXHlINWuToN54ELRcHZe+yK5TRcbNwDVR",
	"JVkI+qP1hYdYt9Ym1rlpu+i8NpYi0m0fwKDbPjFJt/ui0v2+1S6AouPyuiqVObDESamSTY2FKV/4lqux",
	"u9QkAwU3aF9EDFs9RP6DvD9kt1SPw1IVkOESafIOQ8cfzg6P3+8eWVZomKsy3/EWESRCgHpppegICfI6",
	"O6XxW33xy9uDk4OKFePwFBJd3388Ogry7b3Iu/DtHpKUAXm75GxiAZaPRF/gQihksnXTmELR2Q3ohac3",
	"es86juN3QpVFnZG0j/Z2z3aPjn/oHO4fvD87PPtz5+Tg58ODX7pJFPQF1CXGGk4O4ZThQxoaEiz+tHNy",
	"cPrh+P3pgR0DRayYh8xpnU5O2k1pOGZkq9ubk5Imk0mXws9dqUYb7lu9cXS4d/D+9KCz1e11xyaJIXaT",
	"m3hW7LJCUqmgxU6j17XTfG43rKxFU97YaTzr9mBmKD1nl7URyRD+GLHaIB00TVKQj3hI3p69O8LWvsAL",
	"YulF+NOQxlSBnHaS10Gyd2QlcU7J3v57ywiebyP78j8BmbLq64ZbY3dKk7gU5uMaVfIRF13yATsz59Cf",
	"t0lsvfJiEhtzERHodgjNDuHlzS557VtBliWoEvOyi9vaBFC0CGI5Ja4W7tGqwgBih1Fjp/EDM/v21KCy",
	"LAod9ui2ej0vGztV2U6yAVe281sDuXeNNf3znPR7WNQBye1ZSHvz8+9WNMDGzl8/tRs6SyBGpjqAvZLK",
	"IFa0pyNt9c3DikDb+GTH3BgzGpvx31cCBXDXrV6psKozTUINdK1R7uOXrFSQExuERHIitFGMJsRXfws5",
	"09iYMtiAbn9/D1xJOpYSXBF+rNe7y82XIHFsLrrAt26TK+8QqlKG8O3Gr84qUFzlMh0fp8gtTzX3fIrn",
	"lZ/T0js94pcMmqxAF9JVl1hGp5U3iUZVq0WxCFQsCzPPuj2UCgZTK/sVlRCxpDcZcGFZoUfqXZTwodZj",
	"7Do92q+d7dq+CjUVZJJy7AuExVst4xLS0peYkaHVahXXF3eOsG5XVva53p37A7wG+pZP8M+7747gIJZf",
	"rv9E4/qWXi2ix8JLrWvJ0yUfuBjhRX+Q2owU0ySVMm6TFH44YRF3VdUKs4y32wdzPXCCwppboQbbvWfO",
	"RiGmDteHlMd3hLMnuPF7RNn5jkc112v1F/QFoTFnCqVxtnvPHnYZxwJKFSUSbA+OirpT1wSr5y8Hunya",
	"9UjK5eZGwgzdYFep6gwzEeZdl2rh8BQkhraVZctVPnPrizMD5wOVKmU7YwWUiQilwIAkqJTY1EZ1v2kT",
	"kSX2P1TBv2I54qH9I6KGdb9xIgZWmch4HDH1B012faUUFnEjC9EDak9Ase7MSG/KtqpNOGbQ6akeGA+u",
	"UvUmP4R7hMnyRE4nqgOHM/DrpYppDKdyX+SlOpdCwp4/5M6SIdaAj6qO53WfEohUj9Gq2rv+JSuUOruT",
	"XhiWW7yysQfq708ZU9PG5/bK1494ws3ab7vA832uwX289nfvacJOGVXh2H3y6ZaQsWZTbLRJsMieKKyz",
	"6r7JI9bWSxjDK6mtNDXjhfhUA4n5YkjMNbitPCAAoXyOJ1C3gPykNl7TyMdpAG1d4xOQeQWNUagCs9ks",
	"zFf8I3/99HlGvtImX2kJ1nMA/fT5uiCa298BDqwCXxMLCxq9LhUxgaI42qgpUXLi/IxWAz50ag8QLLQW",
	"OlLqnGx5tVAhyen+j1huh4ZQ1K3oWoLEMcCqFRXj43CmsAWUsqihfrhkDyW52+u1jKZ3RvUqc+SgUPWX",
	"GZWxz3P4tXlna8jxoEYGcFflLHk3Beznve/ujk9U/Nw1a97PcOjciubsTc5pQJpFxFHkX4WWBi3LxPsi",
	"Kr6vWIlmhpm4qth9UTtg2QDko016z7ubhIL2YcZMs75AuxEKsNLqihTsikbmGAqAnirWcR+7p2OKeNAX",
	"H04O3+2e/Jn8ePDnJo9apDSklmTr2XZvGzQSnqRSa+44/UNRG4TvEtbXU5ylfHXjNx59RopiZZZ5/roP",
	"z8uIWsGU5zWFqBxcR47xrQ/Yh2hgtyRvHz96vvqj99KAYfnBjv1UDk0Hj2vl2bfrhZYfmFl4or2HpD1I",
	"9W9Oeh7j/fzAch5sNfrD/TtnxKtluAMw7pcZd30PoLywNkSluN6791WIrA1lBDZ2n0MOiQ+OmIkd7X1X",
	"BHd65b0ck+PkBEesobRhDXuvlGO7J/ZeW/JtLfb+oCjmAo4eDMeuKw9IwdbQDmYkg/a6WsXSQLp5JaMU",
	"I7besddoE59qzWl5IGEZMXwEF8QEvGyXMqZmY7xaWPR+IVrQCkF1OIUB1XlYXbsvjk8IJRXBJI45aMqK",
	"ctcknWL4NXpHdOY6GlFR1M8/5xGhMdiNyMDeO7rWpBkzla+kEKdWS1GvfMgugYjdzVaX7EFckCZ6LLM4",
	"6gtXmFeK4pCw0HNKlQuaKh051OJ2stDzra2HE1BfZxrMUR2VxYxcchcxs1PyydYG3PdF7gdtvXIX4Lri",
	"uhhsjGwk3HiCuTS8fo3Q9ofih0gnbygmgnN6Dd9eOq+wY9P+cnuX98dnhY9ACnwVzAkgiYNz3vI0Ny3I",
	"pkHe2xDjZZA7uVI2TaiL0+oSb2TxXWOagQva/x5K0gYYAgLBgREUQY0t9gV/5Mhhz72s+r1lGIFjmN/V",
	"GpHB4ITH8mRuejTmJnshdqRDw5I7NDo5aBrGFC0gCHetr8AI5SE0x3R8cM8GKCLYxEVDFvwHrUXOsZtg",
	"sKMPxwp4FNQGzFAR5fWIq7EtbtRX84Em0jeosB/XfpRbFnK6FFJhp0iVvOQRNqkAjgBMjCcMIg8gAAnv",
	"PsCyXUtsWnb392vRKheJfGh7FuyuTtyFS/e2LFJ2Cw+zOHZA4cQjoOE5J8CDfSj7103l3ZtLuZ++EkPa",
	"G9/RVIP5q43BiF5w7otayVkKJy1B/lOsJdGZGtKQQRBzrnqWhaU52XpW2iS5sFn67DFKm6cueBmaPrrw",
	"0DwoGjJMnH8LXsCfIZQYZHtwaxNKBhWZFV3ezf3Oy+02OTne3X+3+8GJ58/I3snhGXneJvZArsjeFrQk",
	"IM9aXXI2kWQY00up7ClSiKyFgvjUZHqHNGmLBD6ANe8Vh9lD1NO2v37qYvYWh9hu31COUETRviCE4NLz",
	"FlCQBli09Itj8JMCBMPNP7MyVHNQmhziuecnLjX4C4qYb5kZTGjCmRkBgU1DL14Qxzc7mz0Xdx6A6B1A",
	"E2u7osrtFaGa2mUGqXLxKIhZR3+362fgV9arLq31hQy8jqnMcfMlUnuNaXcGegtDJhJqpNGDqaUYoPbM",
	"SNHIyB0NTy0Wa6P95ft0FReBtUi09mJ/EehrCpKhixUVovwSWdwZp3OOu9I0PXK9/v4lDNOLYKa9OpJr",
	"nmXjdfqMr5x3V6Uij/RoadzNQ24tPYD4EO2UZ29sfO58jcY/eFbkHtUmHM3b0esvv/dQEs/dijKP1p7u",
	"KUPVmn4HOsV929LvqSr6HRvQP4D6ASTXI5Sqqe/7q+Sig7araqlfqCLcmasirL3txeLmgjrCUCM4n7U+",
	"x78oWjxXPrjW7n+PKlBNnfyHtvkvJwje3j+vAvnUY1oQjgemF/8SvgF3PXflGSjn6N/KQ1Dmpl/SPzBj",
	"nbm+dwAoyccP+7tnBxgD0Rc+vSyeelkOig9s93qEC20Yhf5dz60YV6/r9cVX6lnoFqsmpW7FDHWuvghm",
	"XAOo+VQcDOgWcP4F6out2Nvlui8Kd0Wes2IVlLYzHLxakrIF1Uu2oLdyyblR0cbWUQX7Yl4XXFcN7Itc",
	"JKxyqFJlfLumcIGG2Bdrqoh12mFfgHpIrq8d2i0vVw/RaiPVo1AUSy6emyqKG0WTu5XagSdv5bR3R9ia",
	"p2e7ZweYBulqi6TSyiBgjcjT1SEXkvyvbaJZKEWkSROSwe2rec9yD+4+GvH0ANSKZ/stp2LCxOe5RGck",
	"iZhhoXGJIH6wIqvbL+7bpcrEKR7EfUsQdppaQrM3f7q/N021UClge7PwikfzSNSKQ8ENz8Nr7fI6s4Ue",
	"csDaas2LfX3h5b6g2BzYQXQWQo6bZc6X0vJsMpRxLCedLAWNpGnBfQ/rGHzzza79yYuPHe6WFZULTnzz",
	"TWkpO33RIcF7iTkvUCkJ/grgefHQvzH7HHplBKTpJGtNgnL2MdgILWq6+Z634HP4aHau4mF1rl8UTT+m",
	"s2+XnpZe74vd8okLmbObhBrFr5ZoYY6Us6gvAqv2BRuBkQFJKVdlNSw/umdFQaa+CJgY0RGLzl0+dtVL",
	"Bfb1wEjy/ffkAF8M2lDJIvD/BCaOuT6lS8vjrJ2VK6TCbkmzeNgpbdPIYqC+8AuEXLkiOKEISSg2nzPT",
	"YjAsWnDqTXup1OY87xYvBbTvZQHBnrWFOZDr0l6gdKHOSwr4JF3vooc6Ae7+2FXK1bQOS17Ukt8PFv1m",
	"CfDd64+z03xJJXIhCzidJTBAKli0hlp5TX7xwArlsiNxrOss3/VKkdx9MVd4p0sQz8EPDLjuK1ZV6UH5",
	"hJ28XSYs1BFcR2BqyMPjczihcDpHqO2uhqAJSkWKwlDNnHh3yekCV5UlZoMFus8DirgFWKwjOdRKu65S",
	"5fJcsjexnBwIo6av/du3pAK3CWuZXczqxv0wak2lt3ljFWb2+zPJSbhUo+4Dh6rgSqA+EGF2t8WqmoCv",
	"rjYFaMGt0pXb47ltSEs9pFj86bgyKzeKfoMRiBuhcrigFiEIR0xfGJli9UVQkIwkqUyzGOiZlUtKCyEp",
	"Dy+Y6pJj18p7MCVBpRtWQKgOGRzdosi1UgO0p/i1xxO/VrqWu4teq8Dg4w9Zqyy3hOUVkL2r+LW6yK3y",
	"Jdxn/FZNE8IHjuKqgFuNqbN0E0/piXeXnhgpmaaYoFiYzEnw8f3hTx8P8vJWgiasFZRyFl1JDbCXRoSb",
	"kqMhE/ySKU3jUnks2I8Xec2UJDJicV4HCwIpFoVbXdsC/6BhMBUKsZhArObo14+MKc+8NEBm16nzaMOL",
	"p+iJ5bo6AhbBN4QOh1hrMOFRR2PNhFdOR4EXodC3kCSWYsQUGbBShQsrVAg2QTtN2Qq0OFJmlsKtipep",
	"EIJ/ibCZNWFscV7n0iPufREK/ntN8pxFykpsyt1JDfcaoVLZRG2cyjrBKHtjKkZAj3yjzwDq5GrCgMIQ",
	"niQs4tSwGBtl0rXIlPO8+GpdJRLjejcYplSWGha9Ijgxjy3H4a5kFGb55IZBr8dFLASf9uIAkvuXxBa2",
	"g35gO+B18Pgpk/Tuo0Wq5/9YsknL9ruakJG+KGJGyHVDRvqiFDNC1goZqSzHTr9Unl4rr7Qvbi17PuWV",
	"Po680tuI5a760AaWyAdz6X2z6bNpytY2LmFbEUd6CvtSfRbc66LYPzJZMfUV6l7kdZbyUtTNw3cfME5i",
	"F7pvaTKQZtwXYHS3Gt/e6c8kpVOsj+sDOsu1lvOOGGMqohgrrqSu34W0RGIPUaNjtxyAN3lrvxL8iY5l",
	"mHEoVULNzjffkF2IFpVDX6EaaaEuOnlBNly18Vdg8ZmmhSfQUDVixg3h5rEbKqY5ebNHnm9+20M/rSvj",
	"r+SkS95AAJSFczcpjGhX2RfD4rcueX38DvfOxWiHfDx70/kWnkHei+Kga9PMyIR6lwkeOjRTO+ICjpKL",
	"kd4heydHb+DUj97APRQt0Uqf2E18TDVTpmhbAFuRE5SIMviRReSCTZ2BdlYt/+c//hvpZ6G6r6wtzoVR",
	"MspCHLIwKBTExYLRgY/WVXY5TsaE89JtUBThORd2iV1y4oW6MesLACsu0swQM+EhpEPa+bQV/3LK7mH2",
	"WU2Rb+QqEjZPtc8cg2TMxWW+i6LowSGgTQ5OpJnT0iJ47WULnFFcQyI5nCFexgXzIHYYsSSVxrJjezHe",
	"zvFu9895m7Sg9E7nRzYNfCqqA0Ej+yKhF5awfTg+PbNUWU07mg5Zl+wSxVLm6p6j0y3n43CGF2zqvIfu",
	"UC2XVCWPrcuaYRGB9ocWG7PYjRJwvzJzDuae6U5fuIT0/e3O5jOyQfa3O1svW13yXhq2k4dIocXAflFE",
	"sYdUKQ5RK66LGAlyL7JP1xiwkPqWN74nHHj4MT4hlJmAilj/3hcM29pgVTdLeLCgNo0L3zR0ZPCmDSu1",
	"CEx/gwqYZA+iAiF2gBoiGIvQfe3W7cQBvxohRac4DgzAk4pMKDfYHcdxO3vpp/zvjMQ84Qaw8R294kmW",
	"kO0eefcaIzssYm/22r1eD5CgS45BIvs7i/JAv5nMlM1nGPjCtDk3Up7Hlp6dZ5qdUz0V4bld0IROW66N",
	"RV84uu/qVkNxYzbiQrtS5b3uFoEvifsSTTtIuQmMrvwg2u3Lq4suTsju7Wd0+FpEdsf+ysclwkO3h7ys",
	"ZpRfHKLu81bX19x+WVTZhU/tMO2Zgtw0zq+3L3CEbU8IEWPJr3IATCPPa9AlGOeCBLin81/lQAeuRmrE",
	"TV+kmUqlzonKCxcw+KsckMN9DLIpYqQrhfTtIMEPB2d94eQGXynCoipnlzQuMRxXd9hJ4ECtffCOHafC",
	"ZHEl32J8YV8Ef6x+/L3FtaBoPsciX8J4Nq2p5/pvFjTRv9hFp3o+ZSQdtsCaUAfP5Y86BdkKGXj0e3lJ",
	"1evJTCX69yObOukOvWY307NnHMv14kOXfGCqo+QE2+hA5K7IG7lpfkWqLMA3YcMI+XwjXfc4aBPNYjSe",
	"+o40f8QZvw/I36ykVjpH8kHG00SqdMxDEoCeGng+koGO5Ahhpb3k5VYpwDnhBmQCraUiYxZbIEdIdMOV",
	"AoZBvLtkynJv7DTHtc4Y+bfNF1s93znLuQU/txsJvfJ9vXu9Xq/O/ceuzEaoL5edey5PWZBeQ6ZCqa8s",
	"TqEABZ9aUsvNWGbGClRdS1MrBBS2UFPEvGo4aTeuOoih9uI7rvn5Xxt405UcnrZ7WGmv6x9WGq/7h645",
	"+uzjmXpg/nGNpefTvdp1cjQ9AQ6/qAg4ymSJoxKO0lu+iBXBt3ovH3RJ2GwMQ8ExgV0mrMJvWNTGhz4c",
	"HrmCj4nCWPs5QQOavXGhQUSQQ+9U3PCxa8g89CsS4LBB8UXBy4hjZRbrGA3HJc7nTQJ3WTN73eizcvhV",
	"QmOr4TCMndqwqGgFkDaBfrYQjO6ZjxPMsxKTCKr8JsgZUhuqtLshAiRz81TOncHms9W6v8MBpxFLeWQF",
	"kLs2qlwLB9xdepNzBeIeLiCprMLPauzl2uVorlhk1HCdm5bGme35l56CcB5LEI67krsLwPGA8Phjb8IC",
	"Gj2M5wB6nyE3/sjvM9xmRlB44FCbHKhqEn1ci9GnCJvbRdg8FQ+qLx6033n5wpV1qmDCDqpc3gsURGxI",
	"s9icQ+dBuI2ZvM4m9qb0ASCtukTPIjEhKLkv5rJMb5KMubJUz9wGvkiVHk9E62noUklhzSrsZWq5KnTH",
	"E5d/jaidpUe/OFhn4YH2HpL+/17jc3wL7dnQnLuRLO43LMet/euvwX6/ElZlji8UQrMGhj1Fztx95Exx",
	"7I8laias0NMvWWPFr+SpBvvvtlJKWYTuixvL0H1RFaKvIx33xXricVGq5MsKynnA0PUF5WEsJx3vQ8ul",
	"5UVi3ZtYThzRu0/RrjxNnT0oG8Rcj1mEXSR9t9NHXpWDpLXLnhPi7iD38toS3ELQWJ3S+2RnfTx2Vnsf",
	"d2dkBSiNFB2ar8DOWlrsHecxL7ezwpHfp5HVTvCFLKwITvOg8iY/638RC2v34U1eBTzXgPNicr2mvSuH",
	"2lXGrtJVl0tId78W89XSY2wvlXPuW8BZgVm/2waCpTt5FLJPyXpVZ+a5RwJfTPCFDDxrgOFjN/B8SUON",
	"O761xKuVNpol1pncZtkXddYZwKdlppkvYao4zE0GaEvIjRXlnc7YJVqu6hty54gPhxAK6K3CEEAdYX3S",
	"7sPr1rfhyBtO93uQPJyVkqvTn++RspVm+IKyq1vF4hipwpDglXEnz0Jcu6uVhGWUHjURvBWmrqJMLkHK",
	"MWxmTyS3ZHTvmq6A5YfGPIKPF9/cPqxmpGg6hgxB5+RvupWRvLTmZT4YlICiWj+gNO/gqyrzYBJPYVL1",
	"oGdBzoMa4UZ7+LsBtVEyjgc0vHgc5ObEreYe6U15ii8oS60mOJCa5G9csc7D05YHAfyTYmeEuoSsdI7Y",
	"Qs5KpTwdZF/eAOA1T6C02+MA+FO3mnsE+PIUXwjgq0tYYnaxZ5dwgZ57d1NAjxUNH7Cg6uPhUpbSu7LE",
	"A+ZP5CGDsStXAkFwfhG3lXPhTlc7Dc7wtTk1n9tTg+j7RrshaGK1Ksg/bLQr6TngbGvsbPUgx4cnWQIp",
	"Pu2G3RT+K9fKIEsWWpp/utOCo8VW17LNw5ZXlhl1g65TZxTPMM8Lt5cA2chMGzLkSptHbKQDk31BCjZU",
	"JqAlrCn2RGt29Gi9ZAj8TtZ8JFzIESj2ELbMdYhh8Y7PzW7CgWGFN7RxQDafxjIDPI4JJVu9XusRA7I/",
	"5KqIDxT/BtTT++FX0s+f/YtfuIRy7qS/s+rJcyq5/rqI2pyUqzHscYhY+OjIV5Hnjdnk1QCQxZ1qilR0",
	"h8ywy5Rq47O8fpWDhRnodgRXHGI2GT2YTW4rxYXmlRE+HJ+edclhXqSBA82gRE9FOFZSyEx7i6jLe/M9",
	"a4Qr9o/f+tIB7hSwdIBPGfefVBvsWN5kjztmZkGltR+YwfX/SQ7uk/AWk9TaX/NLuK4n6evpdMPLmwS+",
	"U5NJeK8olt/BciyDsLDlZP0nfOUpmOaxBNPAhdxdNA2CwOMPpPmbh0OPSA4w7zOIBo/6PqNoKoUOHtgV",
	"4QBpHkjgh6ckxUeTpPiwET5/c0A/h2dLOMia4T0FPq2K70EQ/NdIZVt44IvjgBYcZO+haMPvNQgIrmIu",
	"+ucuOM1dh//cJ2sqzfCFbPgrwO8pu+vug4b8kT+W3K6/lQjNl8zswnU85XU91UCuhl1dT0xSzMI2nN7q",
	"bKaT4uX75PHlaWouv/Tzo09hKh3vHPc+QR/OYzBqzkHBBhYdfhyOGaxK/eiAr1SYWSpSKhErZEemuZ/R",
	"EfBO/vaEC8HUDZ00D6q9ljcLDUl99x85HELfv2YstYFu1LC5DQvPMjNE0fAhk0AQQKDUs1tYGe+ahmnT",
	"iWRmmcGG96JKRTQfCRq3alFyTTRxhu1H4sHcc6t5fKjizykiTWw4mchLBk0mXY/mS04rLc0tY9dfJY4U",
	"TXs9wheNkB/GYOLOusDLB0QIxUA4fxxxlLCWx4cMeEY3TQp7VByg+4ARkvbQHoDGy8ywji/FvtQDdWJf",
	"PfFvPqwjqi7wS/tu9cXlM5EldtMp86HRroVWo92YUG7wr5w6N9oNLNhgH1IRstj+/Wm+wPKCFRTlFIol",
	"zH76Nbq2yjd9dx4uDOT1oPb4PV3V9WJHbOi8RkNAQp1ywVoLI9DuRN9Z4RirXNR9+seqEPGw/rH5uWeI",
	"dvme8gydJhc6tSQUycSGRfRMobcpV1Z8YzyZmVAmrPWogXJf8UuWB8T7/ZqxktkI7XczFUSaNEq42LC8",
	"ohw/f2PusNpgMguO9yV8XAciHr/RpHKfj9lsMg8NG3RARYR39yUk4JmQ57w0KnHrwp7PZbK9Q5DTY5Ow",
	"zGhDMY2vVs4aKsZ85y3Q1/6gSUhTGnIzJWMZR622/U0QDJi3qpynK4xQTYJcrAigiRE+dzZuLgj1H8bE",
	"KYIuhu557ztohpI32fCVzSi2WSDSfoyb7URch1IIoHYgANaFne3iiTwuHDVSCRLJiSDN/KRar+rvhigW",
	"M6q/DkUCdsd1ftf5NTdz6XMDZc+NYuMPp16cMarw3D39mYylrso3TESWjzqEGmdiRLL0dsxjA1qdPQ5i",
	"ccJ0ljCdH0BK1QWLCAWlKz+HS9bB9mzCyg3NETPnkUmGbZIqmaTm3LAr0yYJFRmNz2maKnlJ4zb55z/+",
	"dwvalWdpGk89BQlpiv00MEcdgl5hXNf7ixs7sYTszkuqOPhzqIhcS+HKEM51xYU2jEbQzocnTpbBkXFb",
	"SaYhjciHzzo1KHBmmhpCcZoNEo68/BCu655S1GaneWDf9ioCBYvKLUqvSnRdAeREpKkyyBouwn0JNJbr",
	"ICi1viY6JaQhDjRAOkagb3ry5bbcLiyb0BlF0fBByRbCDDC+MiaBn9jTMbeJZXh8OxpWtgKubTA5KX/0",
	"BbMyKna7O8vKKO+uolzlcm2byDiy8q3zP38d2Rqu+12xt1lpfcSEvXVLDLR9JKCeNYgruvX1SPGQV7eu",
	"ZoeZivdImV0qZA2YldMAH7leB6BTXm8lnV3lAvgjhRAuRhtWQtALs3120ZrQ4aIDm9SCpnosje8sKNXo",
	"D5rE/LIws6CK889//LeL5olYasZtfBupAzyP8JD+oMnp0a5Vu9rzyoBug2A0ZnGUK2QLkm1OcPZT2M09",
	"CxT5PAt4rT8F3X1AQnbJsPMgUxgmXFyVJ9Uy1eSSs8mdmy9r4Utf8DjWK9PIKEnnbMj4aVUz7jd2owh/",
	"6TdIpGQKio0UBBodkogZymPowr25l5eQRvCEr3D0TDNNQvBS+ImhVTfx6S1ucsKuIOsF5nep5q7JwHet",
	"OhC0nOQUt/yUvfNYXBxwIXfn23Bw+eh9GtrDoUdzB5j36aTAo75P70Sld+kDeyccINV0mQLS8pS986+Z",
	"vaMd0M/h2RKOuGb2ToFPq7J3EAT/NbJ3Fh744uydBQfZeyja8HvN3kGhataRdRec5n5bT8G6axtPrewu",
	"1VrcB+o+2V9phi9V5Ws5iD9lCN19hpA/8seSIaRLxOxLZgjhOp4yhJ4yhKoZQtcTxbDE2MpQly9nBD37",
	"Coyf1Jk8H0kwC6ze7ganmmFUNGEdrBxEmopZxLlkZEA1azXajUzFjZ3GBsxa/e5IhjQmEbtksUwTBnVJ",
	"8e2xMenOxkZsXxhLbXa+7X3bA2HEncPsUG8Zjc24TSxhAzRuE52yEE2ckQyL8kIaXLvanmxKNbqEg2M1",
	"2rMgd2UCkvAoitmEKuY+BmLlSxbB6//ROVajzmEUkDFcoeUAmy/bZL+ztWn/9/m2k2ZclOuhGCrqWyKz",
	"mpNAM5vv2r938nHfiUWbbQL/fdbqEsQ6YhfGkgGLIhZZquqMczn4vUKTSv5v+GAYU4P2u91Wl+zGMZko",
	"bqU2j5W6usNCcIPa8muLb27DsB+9cKNoxTaKCs1x8ubp2e7ZQae3mUfjuQffucpWSFjzGlGqVChrmBVi",
	"khtaCqKzMLRs0rK3S2m5HhnKOJaTTpaSHw7OuljZCmyWJwenZ3kxqub/2tbo9bykcesVSTM9zpvMw2HW",
	"0eTq1k/tKmq27ywa8/e81VrXIkvLFlkooj71VZqKy6ysyFHr+dW46ijzq3ne6hLMAoUIrXJMi674uKlb",
	"T5f4dqVWoNJtLEjMzRQRcHfvF2KploLjs1IRH2XKcr3KQl3i6fxC827z80vdbuVzWxBOFdP2fGI54pa4",
	"hDJJMuH4B0lYxClpXkoesra9U9MmLKE8bpGYiwvHr71F2tUTKq8w7/VXA9kuqkyxEddGTcuLfNEqSqn5",
	"6DMlJwhNflMo/mkiRTz1NdVO93+0x2VZgbFCE2FXLMywI+UJo0UsW/4cq7TF1D5MeMy0kaJ6ym6hdXt4",
	"rRi9sDRUS1Fe/8tWl5R/w4VLNeqU7xILTFISKIkiTWDJjm8MeahP8seRTCgXZMziFDqOsvBCYxE4Rwc2",
	"e1V6ApOf4Nx1687iC48EAJZxTF7kB8ssL+NMu1p5BYmBf35r6SGEqGhsUS8V2Tv9uUs+ppopo8kFmyJe",
	"Bk2UcNoELHZFL81McEsvrS6smeoMaWghKaRCCgDCvO2lspikZJSFOCLKzr3n3U3ihcjN1qsZ2x/XXhi0",
	"ojyUtpewcTuyMGyEON9JaJoCXgLFloKwS6amJMACat84nTDIZ3rZIoPM2OHfH5/hPmDHdsNFR3zo6rzV",
	"e2kHTJ3G70hrl+zRNMWAr+0eefeabJDNXrvX6yFwu06mVU6INeM+f/r8/wcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
