// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	OrgHeaderScopes orgHeaderContextKey = "OrgHeader.Scopes"
)

// Defines values for AgentStatus.
const (
	AgentStatusBreak    AgentStatus = "Break"
	AgentStatusEngaged  AgentStatus = "Engaged"
	AgentStatusNotReady AgentStatus = "NotReady"
	AgentStatusOffline  AgentStatus = "Offline"
	AgentStatusReady    AgentStatus = "Ready"
	AgentStatusWrapUp   AgentStatus = "WrapUp"
)

// Valid indicates whether the value is a known member of the AgentStatus enum.
func (e AgentStatus) Valid() bool {
	switch e {
	case AgentStatusBreak:
		return true
	case AgentStatusEngaged:
		return true
	case AgentStatusNotReady:
		return true
	case AgentStatusOffline:
		return true
	case AgentStatusReady:
		return true
	case AgentStatusWrapUp:
		return true
	default:
		return false
	}
}

// Defines values for BulkImportFailedRowError.
const (
	BulkImportFailedRowErrorImportFailed BulkImportFailedRowError = "import_failed"
)

// Valid indicates whether the value is a known member of the BulkImportFailedRowError enum.
func (e BulkImportFailedRowError) Valid() bool {
	switch e {
	case BulkImportFailedRowErrorImportFailed:
		return true
	default:
		return false
	}
}

// Defines values for ChannelType.
const (
	Chat  ChannelType = "chat"
	Email ChannelType = "email"
	Voice ChannelType = "voice"
)

// Valid indicates whether the value is a known member of the ChannelType enum.
func (e ChannelType) Valid() bool {
	switch e {
	case Chat:
		return true
	case Email:
		return true
	case Voice:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	ErrorCodeCrossOrg            ErrorCode = "cross_org"
	ErrorCodeDuplicateCode       ErrorCode = "duplicate_code"
	ErrorCodeDuplicateExternalId ErrorCode = "duplicate_external_id"
	ErrorCodeImmutableField      ErrorCode = "immutable_field"
	ErrorCodeImportFailed        ErrorCode = "import_failed"
	ErrorCodeInternal            ErrorCode = "internal"
	ErrorCodeInvalidBody         ErrorCode = "invalid_body"
	ErrorCodeInvalidId           ErrorCode = "invalid_id"
	ErrorCodeInvalidOrgId        ErrorCode = "invalid_org_id"
	ErrorCodeInvalidReference    ErrorCode = "invalid_reference"
	ErrorCodeInvalidTransition   ErrorCode = "invalid_transition"
	ErrorCodeInvalidValue        ErrorCode = "invalid_value"
	ErrorCodeNotFound            ErrorCode = "not_found"
	ErrorCodeRateLimited         ErrorCode = "rate_limited"
	ErrorCodeVersionConflict     ErrorCode = "version_conflict"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeCrossOrg:
		return true
	case ErrorCodeDuplicateCode:
		return true
	case ErrorCodeDuplicateExternalId:
		return true
	case ErrorCodeImmutableField:
		return true
	case ErrorCodeImportFailed:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeInvalidBody:
		return true
	case ErrorCodeInvalidId:
		return true
	case ErrorCodeInvalidOrgId:
		return true
	case ErrorCodeInvalidReference:
		return true
	case ErrorCodeInvalidTransition:
		return true
	case ErrorCodeInvalidValue:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeRateLimited:
		return true
	case ErrorCodeVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Alive HealthResponseStatus = "alive"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Alive:
		return true
	default:
		return false
	}
}

// Defines values for ImportEntityType.
const (
	Adapters     ImportEntityType = "adapters"
	Agents       ImportEntityType = "agents"
	BreakReasons ImportEntityType = "break_reasons"
	Channels     ImportEntityType = "channels"
	Queues       ImportEntityType = "queues"
	Skills       ImportEntityType = "skills"
)

// Valid indicates whether the value is a known member of the ImportEntityType enum.
func (e ImportEntityType) Valid() bool {
	switch e {
	case Adapters:
		return true
	case Agents:
		return true
	case BreakReasons:
		return true
	case Channels:
		return true
	case Queues:
		return true
	case Skills:
		return true
	default:
		return false
	}
}

// Defines values for InvalidTransitionErrorResponseError.
const (
	InvalidTransition InvalidTransitionErrorResponseError = "invalid_transition"
)

// Valid indicates whether the value is a known member of the InvalidTransitionErrorResponseError enum.
func (e InvalidTransitionErrorResponseError) Valid() bool {
	switch e {
	case InvalidTransition:
		return true
	default:
		return false
	}
}

// Defines values for PostInteractionState.
const (
	PostInteractionStateNotReady PostInteractionState = "not_ready"
	PostInteractionStateReady    PostInteractionState = "ready"
)

// Valid indicates whether the value is a known member of the PostInteractionState enum.
func (e PostInteractionState) Valid() bool {
	switch e {
	case PostInteractionStateNotReady:
		return true
	case PostInteractionStateReady:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessCheck.
const (
	ReadinessCheckDegraded ReadinessCheck = "degraded"
	ReadinessCheckOk       ReadinessCheck = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessCheck enum.
func (e ReadinessCheck) Valid() bool {
	switch e {
	case ReadinessCheckDegraded:
		return true
	case ReadinessCheckOk:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessResponseStatus.
const (
	ReadinessResponseStatusDegraded ReadinessResponseStatus = "degraded"
	ReadinessResponseStatusOk       ReadinessResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the ReadinessResponseStatus enum.
func (e ReadinessResponseStatus) Valid() bool {
	switch e {
	case ReadinessResponseStatusDegraded:
		return true
	case ReadinessResponseStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for VersionConflictErrorResponseError.
const (
	VersionConflictErrorResponseErrorVersionConflict VersionConflictErrorResponseError = "version_conflict"
)

// Valid indicates whether the value is a known member of the VersionConflictErrorResponseError enum.
func (e VersionConflictErrorResponseError) Valid() bool {
	switch e {
	case VersionConflictErrorResponseErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAdapter409JSONResponseBodyError.
const (
	UpdateAdapter409JSONResponseBodyErrorVersionConflict UpdateAdapter409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateAdapter409JSONResponseBodyError enum.
func (e UpdateAdapter409JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateAdapter409JSONResponseBodyErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAgent409JSONResponseBodyError.
const (
	UpdateAgent409JSONResponseBodyErrorVersionConflict UpdateAgent409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateAgent409JSONResponseBodyError enum.
func (e UpdateAgent409JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateAgent409JSONResponseBodyErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateBreakReason409JSONResponseBodyError.
const (
	UpdateBreakReason409JSONResponseBodyErrorVersionConflict UpdateBreakReason409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateBreakReason409JSONResponseBodyError enum.
func (e UpdateBreakReason409JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateBreakReason409JSONResponseBodyErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateChannel409JSONResponseBodyError.
const (
	UpdateChannel409JSONResponseBodyErrorVersionConflict UpdateChannel409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateChannel409JSONResponseBodyError enum.
func (e UpdateChannel409JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateChannel409JSONResponseBodyErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateQueue409JSONResponseBodyError.
const (
	UpdateQueue409JSONResponseBodyErrorVersionConflict UpdateQueue409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateQueue409JSONResponseBodyError enum.
func (e UpdateQueue409JSONResponseBodyError) Valid() bool {
	switch e {
	case UpdateQueue409JSONResponseBodyErrorVersionConflict:
		return true
	default:
		return false
	}
}

// Defines values for UpdateSkill409JSONResponseBodyError.
const (
	VersionConflict UpdateSkill409JSONResponseBodyError = "version_conflict"
)

// Valid indicates whether the value is a known member of the UpdateSkill409JSONResponseBodyError enum.
func (e UpdateSkill409JSONResponseBodyError) Valid() bool {
	switch e {
	case VersionConflict:
		return true
	default:
		return false
	}
}

// Adapter An adapter registry row. Adapters represent integration points (e.g. a FreeSWITCH bridge, a LiveKit gateway). In v0.1 this is a catalog row only — no SDK contract, no execution. Real adapter execution lands in a later milestone.
type Adapter struct {
	// AdapterType Identifier for the adapter kind (e.g. "freeswitch", "livekit", "twilio"). Free text — the platform does not restrict values in v0.1.
	AdapterType string `json:"adapter_type"`

	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code string `json:"code"`

	// Config Free-form JSONB configuration blob. Shape is adapter-type-specific. No vendor-specific fixed columns — everything goes in this field.
	Config    *map[string]interface{} `json:"config,omitempty"`
	CreatedAt *time.Time              `json:"created_at,omitempty"`
	Enabled   bool                    `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id UUIDv7 `json:"id"`

	// Name Display name for this adapter configuration.
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId     UUIDv7     `json:"org_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Version Monotonically increasing optimistic-lock version counter (CAT-08, OQ-1/A4). Server-owned. Mismatch on update returns HTTP 409.
	Version int `json:"version"`
}

// Agent An agent in the catalog. Agents are the humans (or bots) who handle routed interactions. Each agent belongs to exactly one org.
type Agent struct {
	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Email Agent email address.
	Email openapi_types.Email `json:"email"`

	// Enabled Soft-delete flag. `false` means the agent is disabled and will not appear in default list responses (CAT-09). Use `?include_disabled=true` to surface disabled agents.
	Enabled bool `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id UUIDv7 `json:"id"`

	// Name Display name of the agent.
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId UUIDv7 `json:"org_id"`

	// Skills Skills assigned to this agent with proficiency ratings. Embedded on detail GET responses only; omitted from list responses (CAT-10 list items are flat, OQ-1A). Not present on create/list responses.
	Skills    *[]AgentSkillAssignment `json:"skills,omitempty"`
	UpdatedAt *time.Time              `json:"updated_at,omitempty"`

	// Version Monotonically increasing optimistic-lock version counter (CAT-08). Must be included in `PATCH` requests; mismatch returns HTTP 409.
	Version int `json:"version"`
}

// AgentListItem Flat agent record returned in list responses. Skills are intentionally omitted (OQ-1A resolution — embed skills only on detail responses).
type AgentListItem struct {
	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string              `json:"code"`
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Email     openapi_types.Email `json:"email"`
	Enabled   bool                `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id   UUIDv7 `json:"id"`
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId     UUIDv7     `json:"org_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Version   int        `json:"version"`
}

// AgentSkillAssignment A skill assigned to an agent with a proficiency rating.
type AgentSkillAssignment struct {
	// Name Skill name — included on GET detail responses, omitted on write bodies.
	Name *string `json:"name,omitempty"`

	// Proficiency Agent proficiency rating on this skill. Inclusive range 1 (beginner) to 10 (expert). The OpenAPI schema intentionally omits `minimum`/`maximum` so the oapi-codegen Layer 1 validator does NOT short-circuit out-of-range values with HTTP 400. The handler (catalog package, Plan 03-09) enforces the 1-10 range and returns HTTP 422 with `ErrorCode=invalid_value` when the value is out of range — see ROADMAP Phase 3 success criterion 4. Clients should still display min=1/max=10 in UI to prevent obvious mistakes; the wire shape distinguishes "wrong value" (422 invalid_value) from "wrong type" (400 invalid_body).
	Proficiency int `json:"proficiency"`

	// SkillId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	SkillId UUIDv7 `json:"skill_id"`
}

// AgentState The full agent state record (STATE-01). Returned by the status PATCH on success to avoid a follow-up GET (OQ-3C resolution).
type AgentState struct {
	// AgentId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	AgentId UUIDv7 `json:"agent_id"`

	// BreakReasonId The break reason for the current Break state (STATE-04). Non-null only when `status == Break`. Null in all other states.
	BreakReasonId *UUIDv7 `json:"break_reason_id,omitempty"`

	// EngagedChannel The channel type the agent is currently engaged on (STATE-05). Non-null only when `status == Engaged`. Null in all other states.
	EngagedChannel *ChannelType `json:"engaged_channel,omitempty"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId UUIDv7 `json:"org_id"`

	// PostInteractionState The target state after WrapUp expires (STATE-06). Set while Engaged. Null when not in Engaged or WrapUp state.
	PostInteractionState *PostInteractionState `json:"post_interaction_state,omitempty"`

	// StateVersion Monotonically increasing version counter (STATE-08). Incremented on every state mutation. UI uses this to detect stale polling responses.
	StateVersion int `json:"state_version"`

	// Status Agent availability status values (STATE-01).
	//
	// **Agent-toggleable:**
	// - `Ready` — available to receive interactions
	// - `NotReady` — unavailable (no sub-reasons; contrast with Break)
	// - `Break` — temporary unavailability with a configurable reason
	//
	// **System-set:**
	// - `Engaged` — currently handling an interaction (system-initiated only)
	// - `WrapUp` — post-interaction after-contact work period (system-initiated)
	// - `Offline` — agent is logged out or timed out (system-initiated)
	Status    AgentStatus `json:"status"`
	UpdatedAt *time.Time  `json:"updated_at,omitempty"`

	// WrapupUntil Server-owned TTL for the WrapUp state (STATE-07). When now() passes this timestamp, the background goroutine fires the WrapUp → `post_interaction_state` transition. Null in all other states.
	WrapupUntil *time.Time `json:"wrapup_until,omitempty"`
}

// AgentStatus Agent availability status values (STATE-01).
//
// **Agent-toggleable:**
// - `Ready` — available to receive interactions
// - `NotReady` — unavailable (no sub-reasons; contrast with Break)
// - `Break` — temporary unavailability with a configurable reason
//
// **System-set:**
// - `Engaged` — currently handling an interaction (system-initiated only)
// - `WrapUp` — post-interaction after-contact work period (system-initiated)
// - `Offline` — agent is logged out or timed out (system-initiated)
type AgentStatus string

// BreakReason A configurable reason an agent can enter the Break state. Each reason has a `routable` flag that determines whether the agent is eligible for routing while on break. The `IsRoutable` domain helper checks this (STATE-10).
type BreakReason struct {
	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DisplayOrder Sort position in the break reason picker. Lower values appear first.
	DisplayOrder int  `json:"display_order"`
	Enabled      bool `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id UUIDv7 `json:"id"`

	// Name Display label shown on the agent desktop.
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId UUIDv7 `json:"org_id"`

	// Routable Whether an agent on this break reason is eligible for routing. `true` → agent can still receive interactions (e.g. "Short break"). `false` → agent is unavailable (e.g. "Lunch", "Training").
	Routable  bool       `json:"routable"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Version   int        `json:"version"`
}

// BulkImportFailedRow A failed row in a bulk import batch (IMP-04). The original row content is NOT echoed (deferred to v0.2 IMP-11 error CSV download — OQ-2A resolution). Row numbers are 1-based; row 1 is the first data row after the header in CSV, or the first array item for JSON.
type BulkImportFailedRow struct {
	// Error Always `import_failed` for row-level errors (D-36).
	Error BulkImportFailedRowError `json:"error"`

	// Field The field name that caused the failure, if field-level.
	Field *string `json:"field,omitempty"`

	// Reason Human-readable explanation of the failure.
	Reason string `json:"reason"`

	// Row 1-based row number of the failed record.
	Row int `json:"row"`
}

// BulkImportFailedRowError Always `import_failed` for row-level errors (D-36).
type BulkImportFailedRowError string

// BulkImportResult HTTP 207 multi-status body for bulk import (IMP-05, D-37).
//
// NOT an error envelope — separate top-level schema. The `failed[]` items
// use the error envelope shape internally for consistency, but the
// top-level response is its own schema.
//
// HTTP 200 when all rows succeed (no `failed` entries). HTTP 207 when any
// rows fail AND at least one row succeeds. HTTP 422 when ALL rows fail
// (no rows succeeded).
type BulkImportResult struct {
	// Failed Structured errors for each failed row. Empty when all rows succeed.
	Failed []BulkImportFailedRow `json:"failed"`

	// Succeeded UUIDv7 IDs of successfully created/updated records.
	Succeeded []UUIDv7 `json:"succeeded"`
}

// Channel A channel in the catalog. Channels represent a logical communication medium (voice, chat, email). They link to a default queue for unrouted interactions.
type Channel struct {
	// ChannelType Supported channel types in v0.1.
	ChannelType ChannelType `json:"channel_type"`

	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// DefaultQueueId Default queue for interactions arriving on this channel when no flow route is configured. Null means no default queue.
	DefaultQueueId *UUIDv7 `json:"default_queue_id,omitempty"`
	Enabled        bool    `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id   UUIDv7 `json:"id"`
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId     UUIDv7     `json:"org_id"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`

	// Version Monotonically increasing optimistic-lock version counter (CAT-08, OQ-1/A4). Server-owned. Mismatch on update returns HTTP 409.
	Version int `json:"version"`
}

// ChannelType Supported channel types in v0.1.
type ChannelType string

// CreateAdapterRequest defines model for CreateAdapterRequest.
type CreateAdapterRequest struct {
	AdapterType string `json:"adapter_type"`

	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code string `json:"code"`

	// Config Free-form JSONB configuration blob. Null to leave empty.
	Config  *map[string]interface{} `json:"config,omitempty"`
	Enabled *bool                   `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`
	Name       string  `json:"name"`
}

// CreateAgentRequest Request body for creating an agent.
type CreateAgentRequest struct {
	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code string `json:"code"`

	// Email Agent email address.
	Email openapi_types.Email `json:"email"`

	// Enabled Initial enabled state. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`

	// Name Display name.
	Name string `json:"name"`

	// Skills Initial skill assignments. Omit to create with no skills.
	Skills *[]AgentSkillAssignment `json:"skills,omitempty"`
}

// CreateBreakReasonRequest defines model for CreateBreakReasonRequest.
type CreateBreakReasonRequest struct {
	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code         string `json:"code"`
	DisplayOrder int    `json:"display_order"`
	Enabled      *bool  `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`
	Name       string  `json:"name"`
	Routable   bool    `json:"routable"`
}

// CreateChannelRequest defines model for CreateChannelRequest.
type CreateChannelRequest struct {
	// ChannelType Supported channel types in v0.1.
	ChannelType ChannelType `json:"channel_type"`

	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code           string  `json:"code"`
	DefaultQueueId *UUIDv7 `json:"default_queue_id,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`
	Name       string  `json:"name"`
}

// CreateQueueRequest defines model for CreateQueueRequest.
type CreateQueueRequest struct {
	AcwSec       int           `json:"acw_sec"`
	ChannelTypes []ChannelType `json:"channel_types"`

	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code    string `json:"code"`
	Enabled *bool  `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`
	Name       string  `json:"name"`
	Priority   int     `json:"priority"`
}

// CreateSkillRequest defines model for CreateSkillRequest.
type CreateSkillRequest struct {
	// Code User-facing canonical identifier. Required on create, immutable
	// after (passing a different code in PATCH returns HTTP 422 with
	// ErrorCode=immutable_field).
	Code        string  `json:"code"`
	Description *string `json:"description,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`

	// ExternalId Optional caller-assigned identifier from an external system. See entity schema.
	ExternalId *string `json:"external_id,omitempty"`
	Name       string  `json:"name"`
	SkillType  string  `json:"skill_type"`
}

// ErrorCode Closed enum of machine-readable error codes (D-36, D-75, ROADMAP Phase 3
// criterion 4). Clients branch on this value — never on `reason` or HTTP
// status alone.
//
// Phase 04.1 added `duplicate_code`, `duplicate_external_id`, and
// `immutable_field` to support the universal `code` identity model
// (D04_1-16, D04_1-20).
type ErrorCode string

// ErrorResponse Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type ErrorResponse struct {
	// Error Closed enum of machine-readable error codes (D-36, D-75, ROADMAP Phase 3
	// criterion 4). Clients branch on this value — never on `reason` or HTTP
	// status alone.
	//
	// Phase 04.1 added `duplicate_code`, `duplicate_external_id`, and
	// `immutable_field` to support the universal `code` identity model
	// (D04_1-16, D04_1-20).
	Error ErrorCode `json:"error"`

	// Reason Human-readable contextual detail for debugging. Clients MUST NOT branch on this value — it is subject to change across minor versions.
	Reason string `json:"reason"`

	// RequestId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	RequestId *UUIDv7 `json:"request_id,omitempty"`
}

// HealthResponse Liveness check response (D-17).
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// ImportEntityType The catalog entity type being imported.
type ImportEntityType string

// ImportJob A persisted import job record (IMP-06). Created by the import endpoint; queryable via `GET /v1/orgs/{org_id}/imports/{id}`.
type ImportJob struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// EntityType The catalog entity type being imported.
	EntityType ImportEntityType `json:"entity_type"`

	// Errors Structured errors for failed rows; same shape as BulkImportResult.failed.
	Errors     *[]BulkImportFailedRow `json:"errors,omitempty"`
	FailedRows int                    `json:"failed_rows"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id UUIDv7 `json:"id"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId         UUIDv7 `json:"org_id"`
	SucceededRows int    `json:"succeeded_rows"`
	TotalRows     int    `json:"total_rows"`
}

// InvalidTransitionErrorResponse HTTP 409 response for invalid agent-state transitions (STATE-03, D-37).
// Extends the canonical error envelope with `from` and `to` — the
// requested state pair that is not in the allowed transition matrix.
type InvalidTransitionErrorResponse struct {
	Error InvalidTransitionErrorResponseError `json:"error"`

	// From Agent availability status values (STATE-01).
	//
	// **Agent-toggleable:**
	// - `Ready` — available to receive interactions
	// - `NotReady` — unavailable (no sub-reasons; contrast with Break)
	// - `Break` — temporary unavailability with a configurable reason
	//
	// **System-set:**
	// - `Engaged` — currently handling an interaction (system-initiated only)
	// - `WrapUp` — post-interaction after-contact work period (system-initiated)
	// - `Offline` — agent is logged out or timed out (system-initiated)
	From   AgentStatus `json:"from"`
	Reason string      `json:"reason"`

	// RequestId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	RequestId *UUIDv7 `json:"request_id,omitempty"`

	// To Agent availability status values (STATE-01).
	//
	// **Agent-toggleable:**
	// - `Ready` — available to receive interactions
	// - `NotReady` — unavailable (no sub-reasons; contrast with Break)
	// - `Break` — temporary unavailability with a configurable reason
	//
	// **System-set:**
	// - `Engaged` — currently handling an interaction (system-initiated only)
	// - `WrapUp` — post-interaction after-contact work period (system-initiated)
	// - `Offline` — agent is logged out or timed out (system-initiated)
	To AgentStatus `json:"to"`
}

// InvalidTransitionErrorResponseError defines model for InvalidTransitionErrorResponse.Error.
type InvalidTransitionErrorResponseError string

// PaginatedList Common cursor-based pagination envelope (CAT-10). Reused across all
// six catalog entity list endpoints via `allOf` with an entity-specific
// `items` property override.
//
// The cursor is an opaque base64-encoded composite of `{created_at, id}`.
// Cursor internals are not part of the public contract — clients MUST
// treat it as an opaque string. Do not parse or construct cursor values.
type PaginatedList struct {
	// HasMore `true` when there are more results beyond this page. Prefer `has_more` over checking `next_cursor != null` for clarity.
	HasMore bool `json:"has_more"`

	// Items The current page of results.
	Items []interface{} `json:"items"`

	// NextCursor Opaque base64 cursor for the next page. `null` when this is the last page. Pass as `?cursor=<value>` on the next request.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PatchAgentStatusRequest Request body for agent-state transitions (STATE-02, STATE-03, STATE-04,
// STATE-05). Single transition per call (OQ-3A resolution).
//
// **Allowed agent-initiated transitions** (STATE-02):
// - `NotReady` → `Ready`
// - `Ready` → `NotReady`
// - `Ready` → `Break` (requires `break_reason_id`)
// - `Break` → `Ready`
// - `Break` → `NotReady`
// - `WrapUp` → `Ready`
// - `WrapUp` → `NotReady`
//
// **System-only transitions** (cannot be triggered via this endpoint):
// - `Ready` → `Engaged` (requires `engaged_channel`)
// - `Engaged` → `WrapUp`
// - `WrapUp` → `Ready` / `WrapUp` → `NotReady` (via TTL goroutine)
// - `* → Offline`, `Offline → NotReady` (login/logout events)
//
// A transition not in the allowed matrix returns HTTP 409 with
// `InvalidTransitionErrorResponse` (STATE-03, D-37).
type PatchAgentStatusRequest struct {
	// BreakReasonId Required when `to == Break` (STATE-04). Must reference a `break_reason` belonging to the same org. Cross-org break reason IDs return HTTP 422 (not a not_found — the entity may exist, it's just unauthorized for this org).
	BreakReasonId *UUIDv7 `json:"break_reason_id,omitempty"`

	// Force Admin override (D-84). When `true`, bypasses the transition matrix (skips HTTP 409 `invalid_transition`). Cross-row probes still run: a missing or cross-org `break_reason_id` still returns HTTP 422 (D-84 Pitfall 3). v0.1 stub auth allows any caller to pass `force=true`; v1 AUTH phase restricts to `org_admin` role. Use sparingly — every `force=true` call emits a WARN-level audit log entry (`state.force.applied`).
	Force *bool `json:"force,omitempty"`

	// PostInteractionState May be set while `status == Engaged` (STATE-06). Specifies the target state when WrapUp expires. Ignored on other transitions.
	PostInteractionState *PostInteractionState `json:"post_interaction_state,omitempty"`

	// To Agent availability status values (STATE-01).
	//
	// **Agent-toggleable:**
	// - `Ready` — available to receive interactions
	// - `NotReady` — unavailable (no sub-reasons; contrast with Break)
	// - `Break` — temporary unavailability with a configurable reason
	//
	// **System-set:**
	// - `Engaged` — currently handling an interaction (system-initiated only)
	// - `WrapUp` — post-interaction after-contact work period (system-initiated)
	// - `Offline` — agent is logged out or timed out (system-initiated)
	To AgentStatus `json:"to"`
}

// PostInteractionState The state the agent transitions to after the WrapUp period ends (STATE-06). Set by the agent while Engaged. Applied by the system when WrapUp expires.
type PostInteractionState string

// Queue A queue in the catalog. Queues hold interactions waiting to be assigned to an agent. Queues have a channel type, priority, and an after-contact work (ACW) timer.
type Queue struct {
	// AcwSec After-contact work (ACW / WrapUp) timer in seconds. When an interaction ends, the agent enters WrapUp for this many seconds.
	AcwSec int `json:"acw_sec"`

	// ChannelTypes Channel types this queue accepts (e.g. ["voice", "chat"]).
	ChannelTypes []ChannelType `json:"channel_types"`

	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Enabled   bool       `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id   UUIDv7 `json:"id"`
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId UUIDv7 `json:"org_id"`

	// Priority Queue priority. Higher values indicate higher priority. Used by the routing engine to break ties among equally-skilled agents.
	Priority  int        `json:"priority"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Version   int        `json:"version"`
}

// ReadinessCheck Status of an individual readiness check.
type ReadinessCheck string

// ReadinessResponse Deep readiness check response (D-17).
type ReadinessResponse struct {
	Checks struct {
		// Db Status of an individual readiness check.
		Db         ReadinessCheck `json:"db"`
		Migrations struct {
			// Version Current applied migration version from the schema_migrations table.
			Version int `json:"version"`
		} `json:"migrations"`

		// Redis Status of an individual readiness check.
		Redis ReadinessCheck `json:"redis"`
	} `json:"checks"`
	Status ReadinessResponseStatus `json:"status"`
}

// ReadinessResponseStatus defines model for ReadinessResponse.Status.
type ReadinessResponseStatus string

// Skill A skill in the catalog. Skills are assigned to agents with a proficiency rating.
type Skill struct {
	// Code User-facing canonical identifier (D04_1-01). Required, immutable
	// after create. Composite UNIQUE (org_id, code). Used as the upsert
	// key for bulk import (Phase 5) and cross-reference target for
	// nested relationships and future DSL references.
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Description Optional long-form description.
	Description *string `json:"description,omitempty"`
	Enabled     bool    `json:"enabled"`

	// ExternalId Optional caller-assigned identifier from an external system
	// (HR, CRM, etc.). Used for sync mapping only — NOT the upsert
	// key for bulk import (use `code` for that). Partial unique
	// within an org when present. v0.1 supports at most one
	// external source per entity per org; multi-source
	// disambiguation deferred to v0.2 via `external_source TEXT`.
	ExternalId *string `json:"external_id,omitempty"`

	// Id A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	Id   UUIDv7 `json:"id"`
	Name string `json:"name"`

	// OrgId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	OrgId UUIDv7 `json:"org_id"`

	// SkillType Category or domain of the skill (e.g. "technical", "language", "product"). Free text — the platform does not restrict values.
	SkillType string     `json:"skill_type"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	Version   int        `json:"version"`
}

// UUIDv7 A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
// Version must be 7 or higher; UUIDv4 and lower are rejected.
// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
type UUIDv7 = openapi_types.UUID

// UpdateAdapterRequest Request body for updating an adapter. Include `version` from the last GET response for optimistic concurrency (CAT-08).
type UpdateAdapterRequest struct {
	AdapterType *string `json:"adapter_type,omitempty"`

	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code *string `json:"code,omitempty"`

	// Config Free-form JSONB configuration blob. Null to clear.
	Config  *map[string]interface{} `json:"config,omitempty"`
	Enabled *bool                   `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`

	// Version Current optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// UpdateAgentRequest Request body for updating an agent. Include `version` from the last GET response for optimistic concurrency (CAT-08).
type UpdateAgentRequest struct {
	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code    *string              `json:"code,omitempty"`
	Email   *openapi_types.Email `json:"email,omitempty"`
	Enabled *bool                `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`

	// Skills Full-replacement skill assignment array (PUT semantics on the join table — OQ-1A resolution). Replaces the entire set atomically. Omit to leave skills unchanged.
	Skills *[]AgentSkillAssignment `json:"skills,omitempty"`

	// Version Current optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// UpdateBreakReasonRequest defines model for UpdateBreakReasonRequest.
type UpdateBreakReasonRequest struct {
	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code         *string `json:"code,omitempty"`
	DisplayOrder *int    `json:"display_order,omitempty"`
	Enabled      *bool   `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Routable   *bool   `json:"routable,omitempty"`

	// Version Optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// UpdateChannelRequest Request body for updating a channel. Include `version` from the last GET response for optimistic concurrency (CAT-08).
type UpdateChannelRequest struct {
	// ChannelType Supported channel types in v0.1.
	ChannelType *ChannelType `json:"channel_type,omitempty"`

	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code           *string `json:"code,omitempty"`
	DefaultQueueId *UUIDv7 `json:"default_queue_id,omitempty"`
	Enabled        *bool   `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`

	// Version Current optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// UpdateQueueRequest defines model for UpdateQueueRequest.
type UpdateQueueRequest struct {
	AcwSec       *int           `json:"acw_sec,omitempty"`
	ChannelTypes *[]ChannelType `json:"channel_types,omitempty"`

	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code    *string `json:"code,omitempty"`
	Enabled *bool   `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Priority   *int    `json:"priority,omitempty"`

	// Version Optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// UpdateSkillRequest defines model for UpdateSkillRequest.
type UpdateSkillRequest struct {
	// Code Must equal the stored value (immutable post-create in v0.1, D04_1-02).
	// Passing a different value returns HTTP 422 with
	// ErrorCode=immutable_field. The field is accepted in the PATCH
	// body to preserve symmetry with the Create*Request shape; absent
	// or matching values are no-ops. Rename support deferred to v0.2.
	Code        *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	Enabled     *bool   `json:"enabled,omitempty"`

	// ExternalId Mutable external-system mapping (D04_1-07). Pass a string to
	// (re)bind to an external row; pass JSON null to clear the
	// binding; omit the field to leave unchanged.
	ExternalId *string `json:"external_id,omitempty"`
	Name       *string `json:"name,omitempty"`
	SkillType  *string `json:"skill_type,omitempty"`

	// Version Optimistic-lock version. Mismatch → HTTP 409.
	Version int `json:"version"`
}

// VersionConflictErrorResponse HTTP 409 response for optimistic concurrency mismatches (CAT-08, D-37).
// Extends the canonical error envelope with `current` — the server-side
// record as of the moment of the conflict. The UI uses `current` to show
// a diff/merge affordance so the user can see what changed.
type VersionConflictErrorResponse struct {
	// Current The complete server-side entity record at the time of the conflict. Schema depends on which entity was being updated — see per-entity response schemas.
	Current interface{}                       `json:"current"`
	Error   VersionConflictErrorResponseError `json:"error"`
	Reason  string                            `json:"reason"`

	// RequestId A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
	// Version must be 7 or higher; UUIDv4 and lower are rejected.
	// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
	RequestId *UUIDv7 `json:"request_id,omitempty"`
}

// VersionConflictErrorResponseError defines model for VersionConflictErrorResponse.Error.
type VersionConflictErrorResponseError string

// CursorQuery defines model for CursorQuery.
type CursorQuery = string

// EntityIdPath A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
// Version must be 7 or higher; UUIDv4 and lower are rejected.
// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
type EntityIdPath = UUIDv7

// EntityTypeQuery The catalog entity type being imported.
type EntityTypeQuery = ImportEntityType

// ImportJobIdPath A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
// Version must be 7 or higher; UUIDv4 and lower are rejected.
// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
type ImportJobIdPath = UUIDv7

// IncludeDisabledQuery defines model for IncludeDisabledQuery.
type IncludeDisabledQuery = bool

// LimitQuery defines model for LimitQuery.
type LimitQuery = int

// NameSearchQuery defines model for NameSearchQuery.
type NameSearchQuery = string

// OrgIdPath A UUIDv7 (RFC 9562 §5.7) time-ordered unique identifier.
// Version must be 7 or higher; UUIDv4 and lower are rejected.
// Example: `01901b2c-7f3a-7abc-8d4e-5f6a7b8c9d0e`
type OrgIdPath = UUIDv7

// SchemaVersionQuery defines model for SchemaVersionQuery.
type SchemaVersionQuery = string

// BadRequest Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type BadRequest = ErrorResponse

// InternalServerError Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type InternalServerError = ErrorResponse

// InvalidOrgID Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type InvalidOrgID = ErrorResponse

// NotFound Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type NotFound = ErrorResponse

// RequestEntityTooLarge Canonical error envelope (D-35). Present on every 4xx/5xx response.
// `request_id` is omitted on bypass routes that run before the RequestID
// middleware (e.g. responses from the OrgContext middleware itself for
// missing/malformed X-Org-Id).
type RequestEntityTooLarge = ErrorResponse

// orgHeaderContextKey is the context key for OrgHeader security scheme
type orgHeaderContextKey string

// ListAdaptersParams defines parameters for ListAdapters.
type ListAdaptersParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// UpdateAdapter409JSONResponseBodyError defines parameters for UpdateAdapter.
type UpdateAdapter409JSONResponseBodyError string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// CreateAgent409JSONResponseBody defines parameters for CreateAgent.
type CreateAgent409JSONResponseBody struct {
	union json.RawMessage
}

// UpdateAgent409JSONResponseBodyError defines parameters for UpdateAgent.
type UpdateAgent409JSONResponseBodyError string

// ListBreakReasonsParams defines parameters for ListBreakReasons.
type ListBreakReasonsParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// UpdateBreakReason409JSONResponseBodyError defines parameters for UpdateBreakReason.
type UpdateBreakReason409JSONResponseBodyError string

// BulkImportCatalogJSONBody defines parameters for BulkImportCatalog.
type BulkImportCatalogJSONBody = []interface{}

// BulkImportCatalogParams defines parameters for BulkImportCatalog.
type BulkImportCatalogParams struct {
	// Entity The catalog entity type being imported.
	Entity EntityTypeQuery `form:"entity" json:"entity"`

	// SchemaVersion CSV schema version for import validation (IMP-08). Required when `Content-Type: text/csv`. Mismatched version returns HTTP 400 with supported versions listed. Example: `v0.1`.
	SchemaVersion *SchemaVersionQuery `form:"schema_version,omitempty" json:"schema_version,omitempty"`
}

// ListChannelsParams defines parameters for ListChannels.
type ListChannelsParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// UpdateChannel409JSONResponseBodyError defines parameters for UpdateChannel.
type UpdateChannel409JSONResponseBodyError string

// ListQueuesParams defines parameters for ListQueues.
type ListQueuesParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// UpdateQueue409JSONResponseBodyError defines parameters for UpdateQueue.
type UpdateQueue409JSONResponseBodyError string

// ListSkillsParams defines parameters for ListSkills.
type ListSkillsParams struct {
	// Cursor Opaque pagination cursor returned as `next_cursor` from the previous list response. Omit to fetch the first page.
	Cursor *CursorQuery `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return per page. Defaults to 25. Maximum 100.
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// IncludeDisabled When `true`, include disabled entities (`enabled=false`) in list responses. Default `false` (CAT-09).
	IncludeDisabled *IncludeDisabledQuery `form:"include_disabled,omitempty" json:"include_disabled,omitempty"`

	// Name Case-insensitive substring search on the `name` field (ILIKE `%?%`). Returns entities whose name contains the value anywhere (not prefix-only — OQ-4B resolution). Add `pg_trgm` index for performance at larger catalog sizes.
	Name *NameSearchQuery `form:"name,omitempty" json:"name,omitempty"`
}

// UpdateSkill409JSONResponseBodyError defines parameters for UpdateSkill.
type UpdateSkill409JSONResponseBodyError string

// CreateAdapterJSONRequestBody defines body for CreateAdapter for application/json ContentType.
type CreateAdapterJSONRequestBody = CreateAdapterRequest

// UpdateAdapterJSONRequestBody defines body for UpdateAdapter for application/json ContentType.
type UpdateAdapterJSONRequestBody = UpdateAdapterRequest

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = CreateAgentRequest

// UpdateAgentJSONRequestBody defines body for UpdateAgent for application/json ContentType.
type UpdateAgentJSONRequestBody = UpdateAgentRequest

// PatchAgentStatusJSONRequestBody defines body for PatchAgentStatus for application/json ContentType.
type PatchAgentStatusJSONRequestBody = PatchAgentStatusRequest

// CreateBreakReasonJSONRequestBody defines body for CreateBreakReason for application/json ContentType.
type CreateBreakReasonJSONRequestBody = CreateBreakReasonRequest

// UpdateBreakReasonJSONRequestBody defines body for UpdateBreakReason for application/json ContentType.
type UpdateBreakReasonJSONRequestBody = UpdateBreakReasonRequest

// BulkImportCatalogJSONRequestBody defines body for BulkImportCatalog for application/json ContentType.
type BulkImportCatalogJSONRequestBody = BulkImportCatalogJSONBody

// CreateChannelJSONRequestBody defines body for CreateChannel for application/json ContentType.
type CreateChannelJSONRequestBody = CreateChannelRequest

// UpdateChannelJSONRequestBody defines body for UpdateChannel for application/json ContentType.
type UpdateChannelJSONRequestBody = UpdateChannelRequest

// CreateQueueJSONRequestBody defines body for CreateQueue for application/json ContentType.
type CreateQueueJSONRequestBody = CreateQueueRequest

// UpdateQueueJSONRequestBody defines body for UpdateQueue for application/json ContentType.
type UpdateQueueJSONRequestBody = UpdateQueueRequest

// CreateSkillJSONRequestBody defines body for CreateSkill for application/json ContentType.
type CreateSkillJSONRequestBody = CreateSkillRequest

// UpdateSkillJSONRequestBody defines body for UpdateSkill for application/json ContentType.
type UpdateSkillJSONRequestBody = UpdateSkillRequest

// AsErrorResponse returns the union data inside the CreateAgent409JSONResponseBody as a ErrorResponse
func (t CreateAgent409JSONResponseBody) AsErrorResponse() (ErrorResponse, error) {
	var body ErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromErrorResponse overwrites any union data inside the CreateAgent409JSONResponseBody as the provided ErrorResponse
func (t *CreateAgent409JSONResponseBody) FromErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeErrorResponse performs a merge with any union data inside the CreateAgent409JSONResponseBody, using the provided ErrorResponse
func (t *CreateAgent409JSONResponseBody) MergeErrorResponse(v ErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVersionConflictErrorResponse returns the union data inside the CreateAgent409JSONResponseBody as a VersionConflictErrorResponse
func (t CreateAgent409JSONResponseBody) AsVersionConflictErrorResponse() (VersionConflictErrorResponse, error) {
	var body VersionConflictErrorResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVersionConflictErrorResponse overwrites any union data inside the CreateAgent409JSONResponseBody as the provided VersionConflictErrorResponse
func (t *CreateAgent409JSONResponseBody) FromVersionConflictErrorResponse(v VersionConflictErrorResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVersionConflictErrorResponse performs a merge with any union data inside the CreateAgent409JSONResponseBody, using the provided VersionConflictErrorResponse
func (t *CreateAgent409JSONResponseBody) MergeVersionConflictErrorResponse(v VersionConflictErrorResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t CreateAgent409JSONResponseBody) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *CreateAgent409JSONResponseBody) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
