// Auto-generated by scripts/gen-validators.mjs — do not edit manually.
// Re-run with: pnpm --filter @open-routing/ui gen:validators

export { default as CreateAgentRequest } from './CreateAgentRequest.js';
export { default as UpdateAgentRequest } from './UpdateAgentRequest.js';
export { default as CreateSkillRequest } from './CreateSkillRequest.js';
export { default as UpdateSkillRequest } from './UpdateSkillRequest.js';
export { default as CreateQueueRequest } from './CreateQueueRequest.js';
export { default as UpdateQueueRequest } from './UpdateQueueRequest.js';
export { default as CreateChannelRequest } from './CreateChannelRequest.js';
export { default as UpdateChannelRequest } from './UpdateChannelRequest.js';
export { default as CreateAdapterRequest } from './CreateAdapterRequest.js';
export { default as UpdateAdapterRequest } from './UpdateAdapterRequest.js';
export { default as CreateBreakReasonRequest } from './CreateBreakReasonRequest.js';
export { default as UpdateBreakReasonRequest } from './UpdateBreakReasonRequest.js';
export { default as PatchAgentStatusRequest } from './PatchAgentStatusRequest.js';
