// Generated by @lit/localize-tools — do not hand-edit locale lists.
// Wave 1 scaffold: source and target locales for configureLocalization.

export const sourceLocale = 'en' as const;
export const targetLocales = ['vi'] as const satisfies readonly string[];
export type LocaleCode = typeof sourceLocale | (typeof targetLocales)[number];
